CREATE TABLE BI_ADMIN_GEOMETRY_WORLD
   (	AREA_ID NUMBER(10,0),
	ISO_COUNTRY_CODE VARCHAR2(3),
	FEATURE_TYPE_NAME VARCHAR2(35 CHAR),
	ADMIN_LEVEL NUMBER(1,0),
	NAME VARCHAR2(60 CHAR),
	LANGUAGE_CODE VARCHAR2(3 CHAR),
	PARENT_AREA_ID NUMBER(10,0),
	GEOMETRY MDSYS.SDO_GEOMETRY
   ) ;
  CREATE UNIQUE INDEX IPK_BI_ADMIN_GEOMETRY_WORLD ON BI_ADMIN_GEOMETRY_WORLD (AREA_ID)
  ;
ALTER TABLE BI_ADMIN_GEOMETRY_WORLD ADD CONSTRAINT PK_BI_ADMIN_GEOMETRY_WORLD PRIMARY KEY (AREA_ID)
  USING INDEX IPK_BI_ADMIN_GEOMETRY_WORLD  ENABLE;
CREATE UNIQUE INDEX IPK_BI_ADMIN_GEOMETRY_WORLD ON BI_ADMIN_GEOMETRY_WORLD (AREA_ID)
  ;

