CREATE TABLE FLT_OCCR_BK
   (	FLT_NUM NUMBER,
	ACFT_NUM VARCHAR2(50),
	LEG_DEP_DT VARCHAR2(50),
	LEG_ORIG_CDE VARCHAR2(50),
	LEG_DEST_CDE VARCHAR2(50),
	ACFT_TYPE_CDE VARCHAR2(50),
	ACTL_ARR_GATE VARCHAR2(50),
	ACTL_DEP_GATE VARCHAR2(50),
	ACTL_SWA_EQPT_TYPE_CDE VARCHAR2(50),
	ALT_ARPT_CDE VARCHAR2(50),
	SCHD_DEST VARCHAR2(50),
	ACFT_TERM_IND VARCHAR2(50),
	ACFT_ORIG_IND VARCHAR2(50),
	ACTL_TM_OUT_CENT NUMBER,
	ACTL_TM_OUT_LCL NUMBER,
	ACTL_TM_IN_CENT NUMBER,
	ACTL_TM_IN_LCL NUMBER
   ) ;

