CREATE TABLE GNC_LEASE_ANSWER_DATA
   (	LEASE_CLAUSE_ID VARCHAR2(50),
	QID NUMBER,
	Q_TYPE VARCHAR2(50),
	ANS_VALUE VARCHAR2(500),
	ANS_LABEL VARCHAR2(500),
	ANSWER_ID NUMBER,
	SELECTED VARCHAR2(50)
   ) ;

