CREATE GLOBAL TEMPORARY TABLE M2_D8EB5$$
   (	RID VARCHAR2(20),
	MIN_D1 NUMBER,
	MAX_D1 NUMBER,
	MIN_D2 NUMBER,
	MAX_D2 NUMBER,
	MIN_D3 NUMBER,
	MAX_D3 NUMBER
   ) ON COMMIT PRESERVE ROWS
  MONITORING ;

