CREATE TABLE MIGRLOG
   (	ID NUMBER NOT NULL ENABLE,
	PARENT_LOG_ID NUMBER,
	LOG_DATE TIMESTAMP (6) NOT NULL ENABLE,
	SEVERITY NUMBER(4,0) NOT NULL ENABLE,
	LOGTEXT VARCHAR2(4000),
	PHASE VARCHAR2(100),
	REF_OBJECT_ID NUMBER,
	REF_OBJECT_TYPE VARCHAR2(4000),
	CONNECTION_ID_FK NUMBER,
	 CONSTRAINT MIGRLOG_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE,
	 CONSTRAINT MIGR_MIGRLOG_FK FOREIGN KEY (PARENT_LOG_ID)
	  REFERENCES MIGRLOG (ID) ENABLE
   ) ;
CREATE INDEX MIGRLOG_PERF_IDX ON MIGRLOG (REF_OBJECT_ID, SEVERITY)
  ;

