CREATE TABLE MIGR_GENERATION_ORDER
   (	ID NUMBER NOT NULL ENABLE,
	CONNECTION_ID_FK NUMBER NOT NULL ENABLE,
	OBJECT_ID NUMBER NOT NULL ENABLE,
	OBJECT_TYPE VARCHAR2(4000) NOT NULL ENABLE,
	GENERATION_ORDER NUMBER NOT NULL ENABLE,
	 CONSTRAINT MIGR_GENERATION_ORDER_UK UNIQUE (OBJECT_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT MIGR_GENERATION_ORDER_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   ) ;
-- COMMENT --

   COMMENT ON COLUMN MIGR_GENERATION_ORDER.CONNECTION_ID_FK IS '//PARENTFIELD';
