CREATE TABLE MIGR_DATATYPE_TRANSFORM_MAP
   (	ID NUMBER NOT NULL ENABLE,
	PROJECT_ID_FK NUMBER NOT NULL ENABLE,
	MAP_NAME VARCHAR2(4000),
	SECURITY_GROUP_ID NUMBER DEFAULT 0 NOT NULL ENABLE,
	CREATED_ON DATE DEFAULT sysdate NOT NULL ENABLE,
	CREATED_BY VARCHAR2(255),
	LAST_UPDATED_ON DATE,
	LAST_UPDATED_BY VARCHAR2(255),
	 CONSTRAINT MIGR_DATATYPE_TRANSFORM_M_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   ) ;
-- COMMENT --

   COMMENT ON COLUMN MIGR_DATATYPE_TRANSFORM_MAP.ID IS 'Primary Key';
   COMMENT ON COLUMN MIGR_DATATYPE_TRANSFORM_MAP.PROJECT_ID_FK IS '//PARENTFIELD';
   COMMENT ON COLUMN MIGR_DATATYPE_TRANSFORM_MAP.MAP_NAME IS 'A name for the map';
   COMMENT ON TABLE MIGR_DATATYPE_TRANSFORM_MAP  IS 'Table for storing data type maps.  A map is simply a collection of rules';
