CREATE TABLE MLOG$_TMCS_SITES_B
   (	SITE_ID NUMBER,
	SNAPTIME$$ DATE,
	DMLTYPE$$ VARCHAR2(1),
	OLD_NEW$$ VARCHAR2(1),
	CHANGE_VECTOR$$ RAW(255),
	XID$$ NUMBER
   ) ;
-- COMMENT --

   COMMENT ON TABLE MLOG$_TMCS_SITES_B  IS 'snapshot log for master table TMCS_SITES_B';
