CREATE TABLE MLOG$_TMCS_UPDATE_MILESTONES
   (	MILESTONE_ID NUMBER,
	SNAPTIME$$ DATE,
	DMLTYPE$$ VARCHAR2(1),
	OLD_NEW$$ VARCHAR2(1),
	CHANGE_VECTOR$$ RAW(255),
	XID$$ NUMBER
   ) ;
CREATE INDEX I_MLOG$_TMCS_UPDATE_MILESTONES ON MLOG$_TMCS_UPDATE_MILESTONES (XID$$)
  ;
-- COMMENT --

   COMMENT ON TABLE MLOG$_TMCS_UPDATE_MILESTONES  IS 'snapshot log for master table TMCS_UPDATE_MILESTONES';
