CREATE TABLE MLOG$_TMCS_CLIENTS
   (	CLIENT_ID NUMBER,
	SNAPTIME$$ DATE,
	DMLTYPE$$ VARCHAR2(1),
	OLD_NEW$$ VARCHAR2(1),
	CHANGE_VECTOR$$ RAW(255),
	XID$$ NUMBER
   ) ;
-- COMMENT --

   COMMENT ON TABLE MLOG$_TMCS_CLIENTS  IS 'snapshot log for master table TMCS_CLIENTS';
