CREATE TABLE PS_TXN
   (	ID NUMBER(20,0),
	PARENTID NUMBER(20,0),
	COLLID NUMBER(10,0),
	CONTENT BLOB,
	CREATION_DATE DATE DEFAULT sysdate
   ) ;
  CREATE INDEX PS_TXN_IDX ON PS_TXN (COLLID, ID) REVERSE
  ;
ALTER TABLE PS_TXN ADD CONSTRAINT PS_TXN_PK PRIMARY KEY (COLLID, ID)
  USING INDEX PS_TXN_IDX  ENABLE;
CREATE INDEX PS_TXN_IDX ON PS_TXN (COLLID, ID) REVERSE
  ;

