CREATE TABLE TEMP_MISSING_TAS
   (	STORE_ID NUMBER,
	STORE_NUMB VARCHAR2(51),
	DESCRIPTIO VARCHAR2(64),
	MI_PRINX NUMBER(10,0),
	GEOLOC MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOLOC.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOLOC.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TEMP_MISSING_TAS_PK ON TEMP_MISSING_TAS (MI_PRINX)
  ;
ALTER TABLE TEMP_MISSING_TAS ADD CONSTRAINT TEMP_MISSING_TAS_PK PRIMARY KEY (MI_PRINX)
  USING INDEX TEMP_MISSING_TAS_PK  ENABLE;
CREATE INDEX TEMP_MISSING_TAS_SX ON TEMP_MISSING_TAS (GEOLOC)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TEMP_MISSING_TAS_PK ON TEMP_MISSING_TAS (MI_PRINX)
  ;

