CREATE TABLE TEMP_TMCS_DT_TAS
   (	ID NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	RADIUS VARCHAR2(10)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TEMP_TMCS_DT_TAS_PK ON TEMP_TMCS_DT_TAS (ID, RADIUS)
  ;
ALTER TABLE TEMP_TMCS_DT_TAS ADD CONSTRAINT TEMP_TMCS_DT_TAS_PK PRIMARY KEY (ID, RADIUS)
  USING INDEX TEMP_TMCS_DT_TAS_PK  ENABLE;
CREATE INDEX TEMP_TMCS_DT_TAS_GIDX ON TEMP_TMCS_DT_TAS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS (' WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TEMP_TMCS_DT_TAS_PK ON TEMP_TMCS_DT_TAS (ID, RADIUS)
  ;

