CREATE TABLE TEMP_PROP_AREA_100
   (	BG_ID VARCHAR2(12),
	STORE_NUMBER VARCHAR2(256),
	TOTAL_AREA NUMBER(20,0),
	GEOMETRY SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

