CREATE GLOBAL TEMPORARY TABLE TEMP_P2P_CREATE_DISAGG_TADEF
   (	GEO_ID VARCHAR2(320),
	CBSA_CLASS NUMBER,
	STORE_CLASS NUMBER,
	GEO_CLASS NUMBER,
	SL_DISTANCE NUMBER,
	DRIVE_DISTANCE NUMBER,
	DRIVE_MINUTES NUMBER,
	REGION VARCHAR2(320),
	DIRECTION VARCHAR2(5),
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	TADEF VARCHAR2(2),
	TA_TYPE VARCHAR2(32)
   ) ON COMMIT DELETE ROWS ;
  CREATE UNIQUE INDEX TEMP_P2P_DISAGG_TADEF_PK ON TEMP_P2P_CREATE_DISAGG_TADEF (GEO_ID) ;
ALTER TABLE TEMP_P2P_CREATE_DISAGG_TADEF ADD CONSTRAINT TEMP_P2P_DISAGG_TADEF_PK PRIMARY KEY (GEO_ID)
  USING INDEX TEMP_P2P_DISAGG_TADEF_PK  ENABLE;
CREATE UNIQUE INDEX TEMP_P2P_DISAGG_TADEF_PK ON TEMP_P2P_CREATE_DISAGG_TADEF (GEO_ID) ;

