CREATE TABLE TEMP_PROP_AREA_BGLEVEL
   (	BG_ID VARCHAR2(12),
	STORE_NUMBER VARCHAR2(256),
	TOTAL_AREA NUMBER(20,6),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	BG_GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB
 VARRAY BG_GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY BG_GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

