CREATE TABLE TEMP_TMCS_ALL_COMPETITORS
   (	STORE_NUMBER BINARY_DOUBLE,
	STORE_NAME VARCHAR2(255),
	C_EXT_ATTR11 VARCHAR2(255),
	ADDRESS VARCHAR2(255),
	CITY VARCHAR2(255),
	STATE VARCHAR2(255),
	ZIP VARCHAR2(255),
	LATITUDE NUMBER(17,8),
	LONGITUDE NUMBER(17,8),
	N_EXT_ATTR5 VARCHAR2(255),
	C_EXT_ATTR6 VARCHAR2(255),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	CLIENT_ID NUMBER(19,0),
	BRAND_ID NUMBER(19,0),
	COMPETITOR_ID NUMBER(19,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

