CREATE TABLE TEMP_STORE_NEWTA
   (	STORE_ID NUMBER(*,0),
	STORE_NUMBER NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	L_GEOM SDO_GEOMETRY
   )
 VARRAY L_GEOM.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY L_GEOM.SDO_ORDINATES STORE AS SECUREFILE LOB ;

