CREATE TABLE TEMP_LOOKUP_VALUES
   (	CLIENT_ID NUMBER,
	LOOKUP_CODE VARCHAR2(100),
	VALUE_CODE VARCHAR2(100),
	SEQUENCE_NO NUMBER,
	ENABLED_FLAG VARCHAR2(10),
	DESCRIPTION VARCHAR2(200),
	BU_LEVEL_LOVS VARCHAR2(20)
   ) ;

