CREATE TABLE TEMP_KETTLE_TEST
   (	ID NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	COMMENTS VARCHAR2(500)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

