CREATE TABLE TEMP_TMCS_TA_SITES
   (	SITE_ID NUMBER(22,0),
	BRAND VARCHAR2(5),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	TA_TYPE VARCHAR2(320),
	DESCRIPTION VARCHAR2(1000)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TEMP_TMCS_TA_SITES_GIDX ON TEMP_TMCS_TA_SITES (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

