CREATE TABLE TMC_CITY_METRO_MX
   (	NAME VARCHAR2(81),
	STATE VARCHAR2(41),
	STATE_ABRV VARCHAR2(7),
	STATE2CHAR VARCHAR2(3),
	METROYN VARCHAR2(2),
	METROAREA VARCHAR2(41),
	POP_2005 BINARY_DOUBLE,
	CY_POP BINARY_DOUBLE,
	HH_2005 BINARY_DOUBLE,
	CY_HH BINARY_DOUBLE,
	NSE_AB NUMBER(19,0),
	NSE_CPLS NUMBER(19,0),
	NSE_C NUMBER(19,0),
	NSE_DPLS NUMBER(19,0),
	NSE_D NUMBER(19,0),
	NSE_E NUMBER(19,0),
	NSE_VAL BINARY_DOUBLE,
	CALCNSE VARCHAR2(5),
	POPDEN BINARY_DOUBLE,
	HHDEN BINARY_DOUBLE,
	POP_GROWTH BINARY_DOUBLE,
	HH_GROWTH BINARY_DOUBLE,
	COUNT_711 BINARY_DOUBLE,
	MC_CNT BINARY_DOUBLE,
	PETRO_CNT BINARY_DOUBLE,
	LITERATE BINARY_DOUBLE,
	ECONACT BINARY_DOUBLE,
	ED_HSORTEC BINARY_DOUBLE,
	EDNOSEC_PC BINARY_DOUBLE,
	ED_COLLEGE BINARY_DOUBLE,
	BEN_IMSS_P BINARY_DOUBLE,
	BEN_ISSSTE BINARY_DOUBLE,
	BEN_PRIVAT BINARY_DOUBLE,
	SINGLHOME BINARY_DOUBLE,
	AVGAGE BINARY_DOUBLE,
	ACTUALAREA BINARY_DOUBLE,
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMC_CITY_METRO_MX_CIDX ON TMC_CITY_METRO_MX (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

