CREATE TABLE TMCS_TRANS_MRKT_RENTS
   (	MRKT_RENT_ID NUMBER DEFAULT tmcs.TMCS_TRANS_MRKT_RENTS_S.nextval,
	TRANS_ID NUMBER,
	INCLUDE_IN_ANALYSIS VARCHAR2(10),
	EXCLUSION_COMMENTS VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	STORE_ID NUMBER,
	DISTANCE_FROM_LOC NUMBER,
	 PRIMARY KEY (MRKT_RENT_ID)
  USING INDEX  ENABLE
   ) ;

