CREATE TABLE TMCS_TRANS_RENT_DETAIL
   (	RENT_DETAIL_ID NUMBER DEFAULT tmcs.TMCS_TRANS_RENT_DETAIL_S.nextval,
	TRANS_ID NUMBER,
	BUDGETED_AMOUNT NUMBER,
	NEGOTIATED_AMOUNT NUMBER,
	COMMENTS VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	LEASE_FINACIAL_ID NUMBER,
	EXISTING_YR1_RENT NUMBER,
	YR1_RENT_SAVINGS NUMBER,
	PAYMENT_TYPE VARCHAR2(150),
	 PRIMARY KEY (RENT_DETAIL_ID)
  USING INDEX  ENABLE
   ) ;

