CREATE TABLE TMCS_ADF_MENUS
   (	MENU_ID NUMBER(*,0),
	MENU_NAME VARCHAR2(50),
	MENU_TYPE VARCHAR2(50),
	FUNCTION_ID NUMBER(*,0),
	PARENT_MENU_ID NUMBER(*,0),
	ENABLED NUMBER(*,0),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	MENU_NAME_FOR_URL VARCHAR2(50),
	DISPLAY_ORDER NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_ADF_MENUS_PK ON TMCS_ADF_MENUS (MENU_ID)
  ;
ALTER TABLE TMCS_ADF_MENUS ADD CONSTRAINT TMCS_ADF_MENUS_PK PRIMARY KEY (MENU_ID)
  USING INDEX TMCS_ADF_MENUS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ADF_MENUS_PK ON TMCS_ADF_MENUS (MENU_ID)
  ;

