CREATE TABLE TMCS_SF_LOCATION_SCENARIOS
   (	LOCATION_SCENARIO_ID NUMBER DEFAULT TMCS_SF_LOCATION_SCENARIOS_S.NEXTVAL,
	SCENERIO_ID NUMBER,
	NAME VARCHAR2(100),
	TYPE VARCHAR2(50),
	ADDRESS VARCHAR2(100),
	CITY VARCHAR2(100),
	DISTANCE NUMBER,
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (LOCATION_SCENARIO_ID)
  USING INDEX  ENABLE
   ) ;

