CREATE TABLE TMCS_MAP_SERVICES_LOG
   (	LOG_ID NUMBER DEFAULT TMCS_MAP_SERVICES_LOG_S.NEXTVAL,
	ENTITY_TYPE VARCHAR2(320),
	ID NUMBER,
	JSESSION_ID VARCHAR2(320),
	SERVICE_NAME VARCHAR2(320),
	REQUEST_PARAMS CLOB,
	MESSAGE CLOB,
	RESPONSE_STATUS VARCHAR2(500),
	REQUEST_TIME TIMESTAMP (6),
	RESPONSE_TIME TIMESTAMP (6),
	DURATION INTERVAL DAY (2) TO SECOND (6),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_SERVICES_LOG_PK ON TMCS_MAP_SERVICES_LOG (LOG_ID)
  ;
ALTER TABLE TMCS_MAP_SERVICES_LOG ADD CONSTRAINT TMCS_MAP_SERVICES_LOG_PK PRIMARY KEY (LOG_ID)
  USING INDEX TMCS_MAP_SERVICES_LOG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_SERVICES_LOG_PK ON TMCS_MAP_SERVICES_LOG (LOG_ID)
  ;

