CREATE TABLE TMCS_STORE_SALES_TRANSFER
   (	SUBJECT_ID NUMBER,
	STORE_NUMBER VARCHAR2(50),
	LOCATION_TYPE VARCHAR2(50),
	SALES NUMBER,
	PCT_TA_CAPTURE NUMBER,
	TA_SALES NUMBER,
	SL_DISTANCE NUMBER,
	DRIVE_DISTANCE NUMBER,
	DRIVETIME NUMBER,
	SALES_RECAPTURED NUMBER,
	PCT_RECAPTURE NUMBER,
	NET_SALES NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	N_EXT_ATTR11 NUMBER,
	N_EXT_ATTR12 NUMBER,
	N_EXT_ATTR13 NUMBER,
	N_EXT_ATTR14 NUMBER,
	N_EXT_ATTR15 NUMBER,
	N_EXT_ATTR16 NUMBER,
	N_EXT_ATTR17 NUMBER,
	N_EXT_ATTR18 NUMBER,
	N_EXT_ATTR19 NUMBER,
	N_EXT_ATTR20 NUMBER,
	CITY VARCHAR2(50),
	STATE VARCHAR2(50),
	ZIP VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_STORE_SALES_TRANSFER_PK ON TMCS_STORE_SALES_TRANSFER (SUBJECT_ID, STORE_NUMBER)
  ;
ALTER TABLE TMCS_STORE_SALES_TRANSFER ADD CONSTRAINT TMCS_STORE_SALES_TRANSFER_PK PRIMARY KEY (SUBJECT_ID, STORE_NUMBER)
  USING INDEX TMCS_STORE_SALES_TRANSFER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_STORE_SALES_TRANSFER_PK ON TMCS_STORE_SALES_TRANSFER (SUBJECT_ID, STORE_NUMBER)
  ;

