CREATE TABLE TMCS_SEED_SEED_OD
   (	SOURCE_SEED_ID VARCHAR2(11),
	DESTION_SEED_ID VARCHAR2(11),
	SL_DISTANCE NUMBER(17,3),
	DRIVETIME NUMBER(17,3),
	DRIVEDISTANCE NUMBER(17,3),
	CLIENT_ID VARCHAR2(64),
	BRAND_ID VARCHAR2(64)
   ) ;

