CREATE TABLE TMCS_RESOURCE_BUNDLE_ENTR_BK
   (	CLIENT_ID NUMBER,
	RESOURCE_KEY VARCHAR2(500),
	RESOURCE_VALUE VARCHAR2(500),
	OBJECT_NAME VARCHAR2(50),
	TAB VARCHAR2(50),
	SECTION VARCHAR2(50),
	RES_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;

