CREATE TABLE TMCS_BUDGET_CHG_HEADER_HIST
   (	BUDGET_CHG_ID NUMBER,
	BUDGET_CHG_NUMBER VARCHAR2(100),
	PROJECT_ID NUMBER,
	CHG_REASON VARCHAR2(400),
	RELEASE_PCT NUMBER,
	STATUS VARCHAR2(50),
	CHG_ORDER_DATE DATE,
	APPROVED_BY VARCHAR2(100),
	APPROVED_DATE DATE,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CHG_REASON_DESCRIPTION VARCHAR2(1000),
	BRAND_ID NUMBER,
	WF_STATUS VARCHAR2(50),
	C_EXT_ATTR1 VARCHAR2(500)
   ) ;

