CREATE TABLE TMCS_CLIENT_CHAINXY_DATA
   (	STORENAME VARCHAR2(500),
	STORENUMBER VARCHAR2(500),
	CHAINID NUMBER,
	CHAINNAME VARCHAR2(500),
	LABEL VARCHAR2(500),
	PARENTCHAINID NUMBER,
	PARENTCHAINNAME VARCHAR2(500),
	ADDRESS VARCHAR2(500),
	ADDRESS2 VARCHAR2(500),
	CITY VARCHAR2(500),
	POSTALCODE VARCHAR2(500),
	STATE VARCHAR2(500),
	PHONENUMBER VARCHAR2(500),
	STATUS VARCHAR2(500),
	STORETYPE VARCHAR2(500),
	DISTRIBUTORNAME VARCHAR2(500),
	STOREHOURS VARCHAR2(1000),
	OTHERFIELDS VARCHAR2(1000),
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOACCURACY VARCHAR2(500),
	HASHID VARCHAR2(1000),
	LASTUPDATE TIMESTAMP (6),
	FIRSTAPPEARED VARCHAR2(500),
	SIC VARCHAR2(500),
	NAICS VARCHAR2(500),
	CATEGORIES VARCHAR2(500),
	COUNTRY_CODE VARCHAR2(500),
	COUNTRY_NAME VARCHAR2(500),
	STATE_CODE VARCHAR2(500),
	STATE_NAME VARCHAR2(500),
	CBSA_ID VARCHAR2(500),
	CBSA_NAME VARCHAR2(500),
	COUNTY_FIPS VARCHAR2(500),
	COUNTY_NAME VARCHAR2(500),
	DMA_ID VARCHAR2(500),
	DMA_NAME VARCHAR2(500),
	COUNTRY VARCHAR2(500),
	GEOMETRY SDO_GEOMETRY,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_CLIENT_CHAINXY_DATA_PK ON TMCS_CLIENT_CHAINXY_DATA (HASHID)
  ;
ALTER TABLE TMCS_CLIENT_CHAINXY_DATA ADD CONSTRAINT TMCS_CLIENT_CHAINXY_DATA_PK PRIMARY KEY (HASHID)
  USING INDEX TMCS_CLIENT_CHAINXY_DATA_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_CHAINXY_DATA_PK ON TMCS_CLIENT_CHAINXY_DATA (HASHID)
  ;
CREATE INDEX TMCS_CLIENT_CHAINXY_DATA_GIDX ON TMCS_CLIENT_CHAINXY_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

