CREATE TABLE TMCS_INST_ADDRESSES
   (	ADDRESS_ID NUMBER DEFAULT TMCS_INST_ADDRESSES_S.NEXTVAL,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(100),
	ADDRESS_TYPE VARCHAR2(50),
	ADDRESS1 VARCHAR2(200),
	ADDRESS2 VARCHAR2(200),
	ADDRESS3 VARCHAR2(200),
	CITY VARCHAR2(50),
	STATE VARCHAR2(50),
	COUNTY VARCHAR2(50),
	COUNTRY VARCHAR2(50),
	ZIP VARCHAR2(50),
	TIMEZONE VARCHAR2(50),
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	PRIMARY_PHONE VARCHAR2(50),
	PRIMARY_PHONE_EXT VARCHAR2(50),
	SECONDARY_PHONE VARCHAR2(50),
	PRIMARY_EMAIL VARCHAR2(50),
	SECONDARY_EMAIL VARCHAR2(50),
	FAX VARCHAR2(50),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	EXT_CONTACT_NUMBER VARCHAR2(50),
	IS_SYSTEM_USER VARCHAR2(1),
	USER_ID VARCHAR2(100),
	STATUS VARCHAR2(50),
	PRIMARY_FLAG VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_INST_ADDRESSES_PK ON TMCS_INST_ADDRESSES (ADDRESS_ID)
  ;
ALTER TABLE TMCS_INST_ADDRESSES ADD CONSTRAINT TMCS_INST_ADDRESSES_PK PRIMARY KEY (ADDRESS_ID)
  USING INDEX TMCS_INST_ADDRESSES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_INST_ADDRESSES_PK ON TMCS_INST_ADDRESSES (ADDRESS_ID)
  ;

