CREATE TABLE TMCS_EXT_AUTH_HEADER
   (	EXT_AUTH_ID NUMBER,
	PO_ID NUMBER,
	PROJECT_ID NUMBER,
	CHG_REASON VARCHAR2(4000),
	STATUS VARCHAR2(50),
	APPROVED_BY VARCHAR2(100),
	APPROVED_DATE DATE,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CHNG_ORDER_ID NUMBER,
	CHNG_CREATED VARCHAR2(1) DEFAULT 'N',
	BRAND_ID NUMBER,
	WF_STATUS VARCHAR2(50),
	CHANGE_REASON VARCHAR2(1000),
	DESCRIPTION VARCHAR2(4000),
	EXT_AUTH_NUMBER VARCHAR2(50),
	C_EXT_ATTR1 VARCHAR2(4000),
	SUPPLIER_ID NUMBER,
	SUPPLIER_SITE_ID NUMBER,
	TOTAL_ACCURED_TAX_AMOUNT NUMBER,
	TOTAL_VENDOR_TAX_AMOUNT NUMBER,
	TOTAL_AMOUNT NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_EXT_AUTH_HEADER_PK ON TMCS_EXT_AUTH_HEADER (EXT_AUTH_ID)
  ;
ALTER TABLE TMCS_EXT_AUTH_HEADER ADD CONSTRAINT TMCS_EXT_AUTH_HEADER_PK PRIMARY KEY (EXT_AUTH_ID)
  USING INDEX TMCS_EXT_AUTH_HEADER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_EXT_AUTH_HEADER_PK ON TMCS_EXT_AUTH_HEADER (EXT_AUTH_ID)
  ;

