CREATE TABLE TMCS_SF_DECAY_CURVES
   (	CLIENT_ID NUMBER,
	BRAND_ID VARCHAR2(30),
	COUNTRY VARCHAR2(30),
	MODEL_TYPE VARCHAR2(30),
	PARAM_NAME VARCHAR2(30),
	REGION VARCHAR2(30),
	CENSUS_DIVISION VARCHAR2(30),
	CBSA_CLASS NUMBER,
	STORE_CLASS NUMBER,
	B1 NUMBER,
	B2 NUMBER,
	B3 NUMBER,
	B4 NUMBER,
	B5 NUMBER,
	B6 NUMBER,
	C0 NUMBER,
	SWITCH NUMBER,
	MAX_UNIT NUMBER,
	MAX_FLAT_VAL NUMBER,
	MULTI NUMBER,
	MIN_UNIT NUMBER,
	MIN_FLAT_VAL NUMBER
   ) ;
CREATE INDEX TMCS_SF_DECAY_CURVES_IDX ON TMCS_SF_DECAY_CURVES (CLIENT_ID, BRAND_ID, COUNTRY, MODEL_TYPE, PARAM_NAME, CBSA_CLASS, STORE_CLASS)
  ;

