CREATE TABLE TMCS_ENTITY_INTF_MAPINGS_55
   (	INTF_MAPING_ID NUMBER,
	INTF_MAP_HEADER_ID NUMBER,
	SOURCE_COLUMN_ID NUMBER,
	SOURCE_FORMULAE VARCHAR2(4000),
	TARGET_COLUMN_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   ) ;

