CREATE TABLE TMCS_RECEIPT_DETAIL
   (	RECEIPT_DETAIL_ID NUMBER,
	RECEIPT_ID NUMBER,
	PO_ID NUMBER,
	ITEM_SEQ_NO NUMBER,
	TASK_ID NUMBER,
	PO_QTY NUMBER,
	RECEIPT_QTY NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	RECEIVED_QTY NUMBER,
	SOURCE VARCHAR2(100),
	CO_ID NUMBER,
	COMMENTS VARCHAR2(4000)
   ) ;

