CREATE TABLE TMCS_LOOKUP_VALUES_CUST_HMN97
   (	LOOKUP_VALUE_ID NUMBER(*,0) NOT NULL ENABLE,
	LANGUAGE_CODE VARCHAR2(300) NOT NULL ENABLE,
	NAME VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(240),
	CLIENT_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_ID NUMBER,
	LOOKUP_ID NUMBER,
	MULTIPLIER NUMBER,
	VERSION NUMBER,
	OLD_LOOKUP_ID NUMBER,
	OLD_LOOKUP_VALUE_ID NUMBER
   ) ;

