CREATE TABLE TMCS_DEPARTMENTS
   (	DEPARTMENT_ID NUMBER DEFAULT TMCS_DEPARTMENTS_S.NEXTVAL,
	DEPARTMENT_NAME VARCHAR2(500),
	DEPARTMENT_DESC VARCHAR2(200),
	COLOR VARCHAR2(50),
	COST_CENTER VARCHAR2(200),
	PARENT_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	BU_ID NUMBER,
	STATUS VARCHAR2(50),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin' NOT NULL ENABLE,
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	TYPE VARCHAR2(100),
	DEPARTMENT_NAME_SHORT VARCHAR2(100),
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	C_EXT_ATTR4 VARCHAR2(500),
	C_EXT_ATTR5 VARCHAR2(500),
	C_EXT_ATTR6 VARCHAR2(500),
	C_EXT_ATTR7 VARCHAR2(500),
	C_EXT_ATTR8 VARCHAR2(500),
	C_EXT_ATTR9 VARCHAR2(500),
	C_EXT_ATTR10 VARCHAR2(500),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	D_EXT_ATTR1 DATE,
	D_EXT_ATTR2 DATE,
	D_EXT_ATTR3 DATE,
	D_EXT_ATTR4 DATE,
	D_EXT_ATTR5 DATE,
	D_EXT_ATTR6 DATE,
	D_EXT_ATTR7 DATE,
	D_EXT_ATTR8 DATE,
	D_EXT_ATTR9 DATE,
	D_EXT_ATTR10 DATE,
	C_EXT_LOV1 VARCHAR2(200),
	C_EXT_LOV2 VARCHAR2(200),
	C_EXT_LOV3 VARCHAR2(200),
	C_EXT_LOV4 VARCHAR2(200),
	C_EXT_LOV5 VARCHAR2(200),
	C_EXT_LOV6 VARCHAR2(200),
	C_EXT_LOV7 VARCHAR2(200),
	C_EXT_LOV8 VARCHAR2(200),
	C_EXT_LOV9 VARCHAR2(200),
	C_EXT_LOV10 VARCHAR2(200),
	REPLACEMENT_COST_CENTER VARCHAR2(50),
	DATE_INACTIVE DATE,
	LAST_IMPORTED_DATE DATE,
	STAGING_ID NUMBER,
	PATTERN VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX TMCS_DEPARTMENTS_PK ON TMCS_DEPARTMENTS (DEPARTMENT_ID)
  ;
ALTER TABLE TMCS_DEPARTMENTS ADD CONSTRAINT TMCS_DEPARTMENTS_PK PRIMARY KEY (DEPARTMENT_ID)
  USING INDEX TMCS_DEPARTMENTS_PK  ENABLE;
CREATE INDEX TMCS_DEPARTMENTS_INDX04 ON TMCS_DEPARTMENTS (CLIENT_ID)
  ;
CREATE UNIQUE INDEX TMCS_DEPARTMENTS_PK ON TMCS_DEPARTMENTS (DEPARTMENT_ID)
  ;
CREATE INDEX TMCS_DEPARTMENTS_INDX02 ON TMCS_DEPARTMENTS (TYPE)
  ;
CREATE INDEX TMCS_DEPARTMENTS_INDX03 ON TMCS_DEPARTMENTS (PARENT_ID, CLIENT_ID)
  ;
CREATE INDEX TMCS_DEPARTMENTS_INDX01 ON TMCS_DEPARTMENTS (COST_CENTER)
  ;

