CREATE TABLE TMCS_GEO_LOCATION_COUNTS
   (	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY VARCHAR2(100),
	HIERARCHY_TYPE VARCHAR2(100),
	REGION_ID NUMBER,
	GEO_NUMBER NUMBER,
	CBSA_CLASS VARCHAR2(100),
	TARGET_COUNT NUMBER,
	SITE_COUNT NUMBER,
	STORE_COUNT NUMBER,
	PROJECT_COUNT NUMBER,
	PROSPECTS_COUNT NUMBER,
	LAST_UPDATE_DATE DATE,
	LAST_UPDATE_LOGIN NUMBER,
	LAST_UPDATED_BY VARCHAR2(50)
   ) ;

