CREATE TABLE TMCS_CLIENT_DIVISIONS
   (	DIVISION_ID NUMBER,
	DIVISION_CODE VARCHAR2(20),
	DIVISION_NAME VARCHAR2(50),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	DEF_APP_RES_LANG_CODE VARCHAR2(20),
	 PRIMARY KEY (DIVISION_ID)
  USING INDEX  ENABLE
   ) ;

