CREATE TABLE TMCS_PROGRAMS
   (	PROGRAM_ID NUMBER,
	PROGRAM_NAME VARCHAR2(100),
	PROGRAM_DESC VARCHAR2(200),
	SPONSOR VARCHAR2(50),
	START_DATE DATE,
	END_DATE DATE,
	APPROVAL_DATE DATE,
	CAPITAL_BUDGET NUMBER,
	BUDGET_ALLOCATED NUMBER,
	BUDGET_COMMITTED NUMBER,
	ACTUAL_SPENT NUMBER,
	REMAINING_BUDGET NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY VARCHAR2(100),
	STATUS VARCHAR2(50),
	BU_ID NUMBER,
	CAPITAL_BUDGET_LOCAL NUMBER,
	CAPITAL_BUDGET_BU NUMBER,
	CAPITAL_BUDGET_USD NUMBER,
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(100),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	BRANDS_ASSOSIATED VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROGRAMS_PK ON TMCS_PROGRAMS (PROGRAM_ID)
  ;
ALTER TABLE TMCS_PROGRAMS ADD CONSTRAINT TMCS_PROGRAMS_PK PRIMARY KEY (PROGRAM_ID)
  USING INDEX TMCS_PROGRAMS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROGRAMS_PK ON TMCS_PROGRAMS (PROGRAM_ID)
  ;

