CREATE TABLE TMCS_USER_SESSION_INFO
   (	USER_SESSION_INFO_ID VARCHAR2(200) NOT NULL ENABLE,
	USER_NAME VARCHAR2(200) NOT NULL ENABLE,
	LOGOUT_DATE DATE,
	IP_ADDRESS VARCHAR2(50),
	USER_AGENT_STRING VARCHAR2(1000),
	OS VARCHAR2(500),
	COMPUTER VARCHAR2(500),
	BROWSER VARCHAR2(500),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	REMARKS VARCHAR2(2000),
	CURRENT_CLIENT_ID NUMBER,
	CURRENT_COUNTRY_CODE VARCHAR2(5),
	CURRENT_LANGUAGE_CODE VARCHAR2(50),
	CURRENT_BRAND_ID NUMBER,
	CURRENT_BU_ID NUMBER,
	LOGOUT_REMARKS VARCHAR2(2000),
	IS_LOGIN_SUCCESS VARCHAR2(20) DEFAULT 'N',
	IS_SSO_LOGIN VARCHAR2(20) DEFAULT 'N',
	USER_INFO VARCHAR2(4000)
   ) ;
  CREATE UNIQUE INDEX TMCS_USER_SESSION_INFO_PK ON TMCS_USER_SESSION_INFO (USER_SESSION_INFO_ID)
  ;
ALTER TABLE TMCS_USER_SESSION_INFO ADD CONSTRAINT TMCS_USER_SESSION_INFO_PK PRIMARY KEY (USER_SESSION_INFO_ID)
  USING INDEX TMCS_USER_SESSION_INFO_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_USER_SESSION_INFO_PK ON TMCS_USER_SESSION_INFO (USER_SESSION_INFO_ID)
  ;

