CREATE TABLE TMCS_PAPA_STORE_POS
   (	STORE_NUMBER VARCHAR2(100),
	GEO_ID NUMBER,
	GEOMETRY SDO_GEOMETRY,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	 CONSTRAINT TMCS_PAPA_STORE_POS_UK UNIQUE (STORE_NUMBER, GEO_ID)
  USING INDEX  ENABLE
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

