CREATE TABLE TMCS_PROTOTYPE_CHANGE_MEMO
   (	CHANGE_MEMO_ID NUMBER NOT NULL ENABLE,
	PROTOTYPE_ID NUMBER,
	DESCRIPTION VARCHAR2(4000),
	REASON VARCHAR2(4000),
	PROJECT_IMPACT VARCHAR2(100),
	CHANGE_TYPE VARCHAR2(100),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROTOTYPE_CHANGE_MEMO_PK ON TMCS_PROTOTYPE_CHANGE_MEMO (CHANGE_MEMO_ID)
  ;
ALTER TABLE TMCS_PROTOTYPE_CHANGE_MEMO ADD PRIMARY KEY (CHANGE_MEMO_ID)
  USING INDEX TMCS_PROTOTYPE_CHANGE_MEMO_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROTOTYPE_CHANGE_MEMO_PK ON TMCS_PROTOTYPE_CHANGE_MEMO (CHANGE_MEMO_ID)
  ;

