CREATE TABLE TMCS_SEC_USER_ROLES_HIST
   (	USER_ROLE_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200),
	ENT_ROLE_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BU_ID NUMBER,
	DELETED_DATE DATE,
	DELETED_BY VARCHAR2(50),
	ACTION VARCHAR2(100)
   ) ;

