CREATE TABLE TMCS_ENTITY_EVENTS_LEASE
   (	EVENT_ID NUMBER DEFAULT TMCS_ENTITY_EVENTS_LEASE_S.NEXTVAL,
	EVENT_TYPE VARCHAR2(100) NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(100) NOT NULL ENABLE,
	ENTITY_ID NUMBER NOT NULL ENABLE,
	SUB_ENTITY_TYPE VARCHAR2(100),
	SUB_ENTITY_ID NUMBER,
	STATUS VARCHAR2(50) DEFAULT 'N',
	PROCESSING_UUID VARCHAR2(200),
	PROCESSING_MESSAGE VARCHAR2(4000),
	MODULE VARCHAR2(100),
	TRIGGERING_TABLE VARCHAR2(100),
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200) NOT NULL ENABLE,
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	OLD_VALUES_JSON CLOB,
	NEW_VALUES_JSON CLOB,
	OUTPUT_JSON CLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_ENTITY_EVENTS_LEASE_PK ON TMCS_ENTITY_EVENTS_LEASE (EVENT_ID)
  ;
ALTER TABLE TMCS_ENTITY_EVENTS_LEASE ADD CONSTRAINT TMCS_ENTITY_EVENTS_LEASE_PK PRIMARY KEY (EVENT_ID)
  USING INDEX TMCS_ENTITY_EVENTS_LEASE_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ENTITY_EVENTS_LEASE_PK ON TMCS_ENTITY_EVENTS_LEASE (EVENT_ID)
  ;

