CREATE TABLE TMCS_MILESTONE_PRED_TASKS
   (	PRDECESSOR_TASK_ID NUMBER DEFAULT TMCS_MILESTONE_PRED_TASKS_S.NEXTVAL,
	MILESTONE_ID NUMBER,
	PREDECESSOR_PROJECT_ID NUMBER,
	PREDECESSOR_TASK_NUMBER NUMBER,
	PREDECESSOR_LAG_LEAD NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (PRDECESSOR_TASK_ID)
  USING INDEX  ENABLE
   ) ;

