CREATE TABLE TMCS_GIS_ERROR_CODES
   (	ERROR_ID NUMBER DEFAULT TMCS_GIS_ERROR_CODES_S.NEXTVAL,
	ERR_NUM VARCHAR2(320),
	ERR_MESSAGE VARCHAR2(320),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(5),
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE
   ) ;
  CREATE UNIQUE INDEX TMCS_GIS_ERROR_CODES_PK ON TMCS_GIS_ERROR_CODES (ERROR_ID)
  ;
ALTER TABLE TMCS_GIS_ERROR_CODES ADD CONSTRAINT TMCS_GIS_ERROR_CODES_PK PRIMARY KEY (ERROR_ID)
  USING INDEX TMCS_GIS_ERROR_CODES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_GIS_ERROR_CODES_PK ON TMCS_GIS_ERROR_CODES (ERROR_ID)
  ;
CREATE UNIQUE INDEX TMCS_GIS_ERROR_CODES_UIDX ON TMCS_GIS_ERROR_CODES (ERR_NUM, CLIENT_ID, BRAND_ID, COUNTRY)
  ;

