CREATE TABLE TMCS_SITE_SNR
   (	SNR_ID NUMBER,
	TEMPLATE_ID NUMBER,
	SNR_NAME VARCHAR2(256),
	SITE_ID NUMBER,
	DESCRIPTION VARCHAR2(4000),
	Z_SCORE NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	STATUS VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_SNR_PK ON TMCS_SITE_SNR (SNR_ID)
  ;
ALTER TABLE TMCS_SITE_SNR ADD CONSTRAINT TMCS_SITE_SNR_PK PRIMARY KEY (SNR_ID)
  USING INDEX TMCS_SITE_SNR_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_SNR_PK ON TMCS_SITE_SNR (SNR_ID)
  ;

