CREATE TABLE TMCS_ENTITY_TABLES_PK_DATA
   (	TABLE_NAME VARCHAR2(320),
	COLUMN_NAME VARCHAR2(320),
	ENTITY_TYPE VARCHAR2(320)
   ) ;
  CREATE UNIQUE INDEX HZ_LOCATIONS_PK ON TMCS_ENTITY_TABLES_PK_DATA (TABLE_NAME)
  ;
ALTER TABLE TMCS_ENTITY_TABLES_PK_DATA ADD CONSTRAINT TMCS_ENTITY_TABLES_PK_DATA_PK PRIMARY KEY (TABLE_NAME)
  USING INDEX HZ_LOCATIONS_PK  ENABLE;
CREATE UNIQUE INDEX HZ_LOCATIONS_PK ON TMCS_ENTITY_TABLES_PK_DATA (TABLE_NAME)
  ;

