CREATE TABLE TMCS_USERS_ENTITY_MAP
   (	USERS_ENTITY_MAP_ID NUMBER DEFAULT TMCS_USERS_ENTITY_MAP_S.NEXTVAL,
	USER_NAME VARCHAR2(200),
	ENTITY_TYPE VARCHAR2(100),
	ENTITY_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(50),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	 CONSTRAINT TMCS_USERS_ENTITY_MAP_PK PRIMARY KEY (USERS_ENTITY_MAP_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_USERS_ENTITY_MAP_INDX01 ON TMCS_USERS_ENTITY_MAP (USER_NAME, CLIENT_ID)
  ;

