CREATE TABLE TMCS_LOOKUP_VALUE_DUPS
   (	CLIENT_ID NUMBER(*,0),
	LOOKUP_ID NUMBER(*,0) NOT NULL ENABLE,
	LOOKUP_TYPE_CODE VARCHAR2(50) NOT NULL ENABLE,
	LOOKUP_VALUE_CODE VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(240),
	SEQUENCE NUMBER
   ) ;

