CREATE TABLE TMCS_RESOURCE_BOUNDARIES_CUSHTARD
   (	RESOURCE_BOUNDRY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID VARCHAR2(100),
	COUNTRY VARCHAR2(100),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	N_EXT_ATTR1 NUMBER
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

