CREATE TABLE TMCS_MAP_INFO_WINDOW_CLAUSES
   (	CLAUSES_ID NUMBER NOT NULL ENABLE,
	DEFAULT_CLAUSE VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	JOIN_CLAUSE VARCHAR2(4000) NOT NULL ENABLE,
	INFO_WINDOW_ID NUMBER,
	CLIENT_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	TAB_ID NUMBER,
	BRAND_ID NUMBER,
	 CONSTRAINT TMCS_MAP_INFO_WINDOW_CLAUSESPK PRIMARY KEY (CLAUSES_ID)
  USING INDEX  ENABLE
   ) ;

