CREATE TABLE TMCS_TA_SIS_STORE_TRUC_RULES
   (	CLIENT_ID NUMBER,
	COUNTRY VARCHAR2(32),
	TA_TYPE VARCHAR2(32),
	SITE_TYPE VARCHAR2(32),
	STORE_TYPE VARCHAR2(32),
	SHADOW_ANGLE NUMBER,
	TRUNC_RATIO NUMBER
   ) ;

