CREATE TABLE TMCS_CLIENT_OAUTH_TOKENS
   (	TOKEN_ID NUMBER DEFAULT TMCS_CLIENT_OAUTH_TOKENS_S.NEXTVAL,
	PROFILE VARCHAR2(50) NOT NULL ENABLE,
	TOKEN_TYPE VARCHAR2(50) NOT NULL ENABLE,
	TOKEN VARCHAR2(4000) NOT NULL ENABLE,
	TOKEN_EXPIRY DATE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	CREATED_DATE DATE DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	 CONSTRAINT TMCS_CLIENT_OAUTH_TOKENS_PK PRIMARY KEY (TOKEN_ID)
  USING INDEX  ENABLE
   ) ;

