CREATE TABLE TMCS_CLIENT_BRANDS_AMCN
   (	CLIENT_BRAND_ID NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER(*,0),
	BRAND_NAME VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_CODE VARCHAR2(50)
   ) ;

