CREATE TABLE TMCS_JOB_RUN_DETAILS
   (	JOB_ID NUMBER,
	CLIENT_ID NUMBER,
	JOB_NAME VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	STATUS VARCHAR2(200),
	COMPLETION_MESSAGE VARCHAR2(2000),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_JOB_RUN_DETAILS_PK ON TMCS_JOB_RUN_DETAILS (JOB_ID)
  ;
ALTER TABLE TMCS_JOB_RUN_DETAILS ADD CONSTRAINT TMCS_JOB_RUN_DETAILS_PK PRIMARY KEY (JOB_ID)
  USING INDEX TMCS_JOB_RUN_DETAILS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_JOB_RUN_DETAILS_PK ON TMCS_JOB_RUN_DETAILS (JOB_ID)
  ;

