CREATE TABLE TMCS_CLIENT_CHAINXY_CONFIG
   (	CONFIG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(50),
	IS_ENABLE VARCHAR2(5),
	CHAIN_ID NUMBER,
	GROUP1_CODE VARCHAR2(50),
	GROUP2_CODE VARCHAR2(50),
	GROUP3_CODE VARCHAR2(50),
	GROUP4_CODE VARCHAR2(50),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_CHAINXY_CONFIG_PK ON TMCS_CLIENT_CHAINXY_CONFIG (CLIENT_ID, BRAND_ID, COUNTRY, CHAIN_ID)
  ;
ALTER TABLE TMCS_CLIENT_CHAINXY_CONFIG ADD CONSTRAINT TMCS_CLIENT_CHAINXY_CONFIG_PK PRIMARY KEY (CLIENT_ID, BRAND_ID, COUNTRY, CHAIN_ID)
  USING INDEX TMCS_CLIENT_CHAINXY_CONFIG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_CHAINXY_CONFIG_PK ON TMCS_CLIENT_CHAINXY_CONFIG (CLIENT_ID, BRAND_ID, COUNTRY, CHAIN_ID)
  ;

