CREATE TABLE TMCS_MODEL_DEMOG_TEMPLATES
   (	DEMOGRAPHIC_ID NUMBER,
	TEMPLATE_ID NUMBER,
	MODEL_ID NUMBER,
	DEMOGRAPHIC_COLUMN_NAME VARCHAR2(50),
	DEMOGRAPHIC_TABLE_OWNER VARCHAR2(50),
	DEMOGRAPHIC_COLUMN_DESC VARCHAR2(500),
	AGGREGATE_TYPE VARCHAR2(100),
	RECORD_ACTIVE_YN VARCHAR2(1),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	DEMOGRAPHIC_TABLE_NAME VARCHAR2(50),
	DEMOG_GEO_TYPE_YN VARCHAR2(1),
	BLK_TABLE_NAME VARCHAR2(3200),
	PROP_TYPE VARCHAR2(3200)
   ) ;
  CREATE UNIQUE INDEX TMCS_MODEL_DEMOG_TEMPLATES_PK ON TMCS_MODEL_DEMOG_TEMPLATES (DEMOGRAPHIC_ID, TEMPLATE_ID, MODEL_ID)
  ;
ALTER TABLE TMCS_MODEL_DEMOG_TEMPLATES ADD CONSTRAINT TMCS_MODEL_DEMOG_TEMPLATES_PK PRIMARY KEY (DEMOGRAPHIC_ID, TEMPLATE_ID, MODEL_ID)
  USING INDEX TMCS_MODEL_DEMOG_TEMPLATES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MODEL_DEMOG_TEMPLATES_PK ON TMCS_MODEL_DEMOG_TEMPLATES (DEMOGRAPHIC_ID, TEMPLATE_ID, MODEL_ID)
  ;

