CREATE TABLE TMCS_OUT_TEST_INTF
   (	INTERFACE_ID NUMBER,
	CLIENT_ID NUMBER,
	INTERFACE_FIELD_TYPE VARCHAR2(200),
	TMCS_DB_TABLE_NAME VARCHAR2(200),
	TMCS_DB_FIELD_NAME VARCHAR2(200),
	INTERFACE_NAME VARCHAR2(200),
	INTERFACE_FOLDER VARCHAR2(200)
   ) ;

