CREATE TABLE TMCS_SITE_TA_DISAGG
   (	SITE_ID NUMBER,
	BRAND VARCHAR2(64),
	GEO_ID VARCHAR2(16),
	GEO_CLASS VARCHAR2(5),
	DISTANCEMILES NUMBER,
	DRIVETIME NUMBER,
	TADEF VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_TA_DISAGG_PK ON TMCS_SITE_TA_DISAGG (SITE_ID, GEO_ID)
  ;
ALTER TABLE TMCS_SITE_TA_DISAGG ADD CONSTRAINT TMCS_SITE_TA_DISAGG_PK PRIMARY KEY (SITE_ID, GEO_ID)
  USING INDEX TMCS_SITE_TA_DISAGG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_TA_DISAGG_PK ON TMCS_SITE_TA_DISAGG (SITE_ID, GEO_ID)
  ;

