CREATE TABLE TMCS_SDA_ENTITY_REASSIGN
   (	GUID VARCHAR2(320),
	TID VARCHAR2(320),
	ENTITY_TYPE VARCHAR2(320),
	ENTITY_ID NUMBER,
	OLD_SDA_ID NUMBER,
	NEW_SDA_ID NUMBER,
	STATUS VARCHAR2(320),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	APPROVED_BY VARCHAR2(320),
	APPROVAL_DATE TIMESTAMP (6)
   ) ;
  CREATE UNIQUE INDEX TMCS_SDA_ENTITY_REASSIGN_PK ON TMCS_SDA_ENTITY_REASSIGN (GUID, TID, ENTITY_TYPE, ENTITY_ID)
  ;
ALTER TABLE TMCS_SDA_ENTITY_REASSIGN ADD CONSTRAINT TMCS_SDA_ENTITY_REASSIGN_PK PRIMARY KEY (GUID, TID, ENTITY_TYPE, ENTITY_ID)
  USING INDEX TMCS_SDA_ENTITY_REASSIGN_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SDA_ENTITY_REASSIGN_PK ON TMCS_SDA_ENTITY_REASSIGN (GUID, TID, ENTITY_TYPE, ENTITY_ID)
  ;

