CREATE TABLE TMCS_CLIENT_BUSINESS_UNITS_AMZN
   (	BU_ID NUMBER,
	CLIENT_ID NUMBER(*,0),
	BU_NAME VARCHAR2(50),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_ID NUMBER,
	BU_CODE VARCHAR2(20),
	DEF_APP_RES_LANG_CODE VARCHAR2(20),
	AUTOGEN_STORE_NUMBER VARCHAR2(10),
	BU_CURRENCY VARCHAR2(10),
	COST_HEALTH_THRESHOLD NUMBER,
	DIVISION_ID NUMBER,
	AUTOGEN_LEASE_NUMBER VARCHAR2(10),
	INVOICE_TOLERANCE NUMBER,
	INVOICE_CONTROL VARCHAR2(10),
	ALLOW_BUDGET_VERSION_SELECTION VARCHAR2(10),
	ALLOW_PO_CO_FOR_CHILD_PROJ VARCHAR2(100)
   ) ;

