CREATE TABLE TMCS_FOLDER_TEMPLATES
   (	FOLDER_TEMPLATE_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	TEMPLATE_NAME VARCHAR2(250),
	DESCRIPTION VARCHAR2(250),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(50),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	STATUS VARCHAR2(50),
	PROJECT_TYPE VARCHAR2(100),
	RECORD_STATUS VARCHAR2(100),
	VERSION NUMBER,
	 PRIMARY KEY (FOLDER_TEMPLATE_ID)
  USING INDEX  ENABLE
   ) ;

