CREATE TABLE TMCS_BLK_LANDUSE_DATA
   (	BLK_ID VARCHAR2(16),
	BG_ID VARCHAR2(13),
	AIRPORT NUMBER(18,8),
	BUSINESS NUMBER(18,8),
	HOTEL_MOTEL NUMBER(18,8),
	INSTITUTIONAL NUMBER(18,8),
	MILITARY NUMBER(18,8),
	RECREATION NUMBER(18,8),
	RESIDENTIAL NUMBER(18,8),
	SHOPPING NUMBER(18,8),
	TRANSIENT NUMBER(18,8),
	OTHERS NUMBER(18,8),
	SUM_AREA_SQMILE NUMBER(18,8),
	BLOCK_AREA_SQMILE NUMBER(18,8),
	GEOMETRY SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_BLK_LANDUSE_DATA_PK ON TMCS_BLK_LANDUSE_DATA (BLK_ID, BG_ID)
  ;
ALTER TABLE TMCS_BLK_LANDUSE_DATA ADD CONSTRAINT TMCS_BLK_LANDUSE_DATA_PK PRIMARY KEY (BLK_ID, BG_ID)
  USING INDEX TMCS_BLK_LANDUSE_DATA_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_BLK_LANDUSE_DATA_PK ON TMCS_BLK_LANDUSE_DATA (BLK_ID, BG_ID)
  ;

