CREATE TABLE TMCS_DMS_APPROVALS
   (	DOC_APPROVAL_ID NUMBER NOT NULL ENABLE,
	APPROVAL_ID NUMBER NOT NULL ENABLE,
	APPROVAL_USER VARCHAR2(100),
	APPROVAL_STATUS VARCHAR2(50),
	APPROVAL_ORDER NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	 CONSTRAINT TMCS_DMS_APPROVALS_PK PRIMARY KEY (DOC_APPROVAL_ID)
  USING INDEX  ENABLE
   ) ;

