CREATE TABLE TMCS_USER_REGIONS
   (	USER_REGION_ID NUMBER(19,0),
	USER_NAME VARCHAR2(100),
	REGION_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	 PRIMARY KEY (USER_REGION_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_USER_REGIONS_INDX1 ON TMCS_USER_REGIONS (LOWER(USER_NAME), REGION_ID)
  ;
CREATE INDEX TMCS_USER_REGIONS_INDX03 ON TMCS_USER_REGIONS (BRAND_ID)
  ;
CREATE INDEX TMCS_USER_REGIONS_INDX4 ON TMCS_USER_REGIONS (UPPER(USER_NAME), REGION_ID)
  ;
CREATE INDEX TMCS_USER_REGIONS_INDX02 ON TMCS_USER_REGIONS (CLIENT_ID)
  ;

