CREATE TABLE TMCS_SEED_POINTS_CANNAB
   (	SEED_ID VARCHAR2(11),
	STORE_NUMBER VARCHAR2(11),
	DRIVETIME NUMBER(17,3),
	CANNIBALIZATION_PCT NUMBER(17,6),
	SOURCE_NAME VARCHAR2(64),
	N_EXT_ATTR1 NUMBER(17,6),
	CLIENT_ID NUMBER(19,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_SEED_POINTS_CANNAB_PK ON TMCS_SEED_POINTS_CANNAB (SEED_ID, STORE_NUMBER)
  ;
ALTER TABLE TMCS_SEED_POINTS_CANNAB ADD CONSTRAINT TMCS_SEED_POINTS_CANNAB_PK PRIMARY KEY (SEED_ID, STORE_NUMBER)
  USING INDEX TMCS_SEED_POINTS_CANNAB_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SEED_POINTS_CANNAB_PK ON TMCS_SEED_POINTS_CANNAB (SEED_ID, STORE_NUMBER)
  ;

