CREATE TABLE TMCS_PROJ_BUDGET_ENTITY_DTL
   (	BUDGET_ENTITY_DTL_ID NUMBER,
	BUDGET_ENTITY_ID NUMBER,
	TASK_NAME VARCHAR2(100),
	AMOUNT NUMBER,
	DESCRIPTION VARCHAR2(500),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	COUNTRY_CODE VARCHAR2(50),
	 PRIMARY KEY (BUDGET_ENTITY_DTL_ID)
  USING INDEX  ENABLE
   ) ;

