CREATE TABLE TMCS_INVOICE_HEADER
   (	INVOICE_ID NUMBER,
	PO_ID NUMBER,
	PROJECT_ID NUMBER,
	STATUS VARCHAR2(50),
	INV_DATE DATE,
	SUBMITTED_BY VARCHAR2(100),
	APPROVED_BY VARCHAR2(100),
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	INVOICE_TYPE VARCHAR2(50),
	INVOICE_NUMBER VARCHAR2(100),
	RETAINAGE_PCT NUMBER,
	BRAND_ID NUMBER,
	PAYMENT_DATE DATE,
	CONFIRMATION_NUMBER VARCHAR2(50),
	PAYMENT_AMOUNT NUMBER,
	PAYMENT_AMOUNT_LOCAL NUMBER,
	PAYMENT_AMOUNT_BU NUMBER,
	PAYMENT_AMOUNT_USD NUMBER,
	PAYMENT_CURRENCY VARCHAR2(10),
	EXCHANGE_RATE NUMBER,
	HAS_CERT_OF_INS VARCHAR2(10),
	HAS_LEAN_WAIVER VARCHAR2(10),
	BUYER_CODE VARCHAR2(100),
	BUYER_NAME VARCHAR2(100),
	CURRENCY VARCHAR2(10),
	SUPPLIER_ID NUMBER,
	WF_STATUS VARCHAR2(50),
	SUPPLIER_SITE_ID NUMBER,
	D_EXT_ATTR1 DATE,
	PCT_INV_AMT NUMBER,
	C_EXT_ATTR1 VARCHAR2(4000),
	COMMENTS VARCHAR2(4000),
	EXPORTED_FLAG VARCHAR2(10),
	INV_GUID VARCHAR2(50),
	TOTAL_INV_AMOUNT NUMBER,
	TOTAL_NET_AMOUNT NUMBER,
	PAYMENT_TERMS VARCHAR2(100),
	STAGING_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_INVOICE_HEADER_PK ON TMCS_INVOICE_HEADER (INVOICE_ID)
  ;
ALTER TABLE TMCS_INVOICE_HEADER ADD CONSTRAINT TMCS_INVOICE_HEADER_PK PRIMARY KEY (INVOICE_ID)
  USING INDEX TMCS_INVOICE_HEADER_PK  ENABLE;
CREATE INDEX TMCS_INVOICE_HEADER_INDX02 ON TMCS_INVOICE_HEADER (PO_ID, STATUS)
  ;
CREATE UNIQUE INDEX TMCS_INVOICE_HEADER_PK ON TMCS_INVOICE_HEADER (INVOICE_ID)
  ;

