CREATE TABLE TMCS_SALES_TAXES
   (	TAX_ID NUMBER DEFAULT TMCS_SALES_TAXES_S.NEXTVAL,
	TAX_GROUP VARCHAR2(100),
	TAX_CODE VARCHAR2(100),
	DESCRIPTION VARCHAR2(4000),
	TOTAL_RATE NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (TAX_ID)
  USING INDEX  ENABLE
   ) ;

