CREATE TABLE TMCS_MAP_INFO_WINDOW_TABS
   (	TAB_ID NUMBER NOT NULL ENABLE,
	INFO_WINDOW_ID NUMBER NOT NULL ENABLE,
	TAB_ORDER NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	DB_QUERY VARCHAR2(1) DEFAULT 'N',
	BRAND_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_INFO_WINDOW_TABS_PK ON TMCS_MAP_INFO_WINDOW_TABS (CLIENT_ID, BU_ID, INFO_WINDOW_ID, TAB_ORDER)
  ;
ALTER TABLE TMCS_MAP_INFO_WINDOW_TABS ADD CONSTRAINT TMCS_MAP_INFO_WINDOW_TABS_PK PRIMARY KEY (CLIENT_ID, BU_ID, INFO_WINDOW_ID, TAB_ORDER)
  USING INDEX TMCS_MAP_INFO_WINDOW_TABS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WINDOW_TABS_PK ON TMCS_MAP_INFO_WINDOW_TABS (CLIENT_ID, BU_ID, INFO_WINDOW_ID, TAB_ORDER)
  ;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WINDOW_TABS_UK ON TMCS_MAP_INFO_WINDOW_TABS (TAB_ID)
  ;

