CREATE TABLE TMCS_TEMPLATES
   (	TEMPLATE_ID NUMBER DEFAULT TMCS_TEMPLATES_S.NEXTVAL,
	ENTITY_TYPE VARCHAR2(50),
	TEMPLATE_NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(4000),
	TEMPLATE_TYPE VARCHAR2(100),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	MILESTONE_TEMPLATE_ID NUMBER,
	RECORD_STATUS VARCHAR2(100),
	VERSION NUMBER,
	 PRIMARY KEY (TEMPLATE_ID)
  USING INDEX  ENABLE
   ) ;

