CREATE TABLE TMCS_COUNTRY_CODES
   (	COUNTRY_NAME VARCHAR2(100 CHAR),
	COUNTRY_CODE_2 VARCHAR2(4),
	COUNTRY_CODE_3 VARCHAR2(4),
	ISO_NUMBER NUMBER(3,0),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	TIMEZONE VARCHAR2(100),
	CURRENCY VARCHAR2(50)
   )
  COLUMN GEOMETRY NOT SUBSTITUTABLE AT ALL LEVELS ;
  CREATE UNIQUE INDEX PK_TMCS_COUNTRY_CODES ON TMCS_COUNTRY_CODES (COUNTRY_CODE_3)
  ;
ALTER TABLE TMCS_COUNTRY_CODES ADD CONSTRAINT PK_TMCS_COUNTRY_CODES PRIMARY KEY (COUNTRY_CODE_3)
  USING INDEX PK_TMCS_COUNTRY_CODES  ENABLE;
CREATE UNIQUE INDEX PK_TMCS_COUNTRY_CODES ON TMCS_COUNTRY_CODES (COUNTRY_CODE_3)
  ;
CREATE INDEX TMCS_COUNTRY_CODES_INDX01 ON TMCS_COUNTRY_CODES (UPPER(COUNTRY_CODE_3))
  ;
CREATE INDEX TMCS_COUNTRY_CODES_GIDX ON TMCS_COUNTRY_CODES (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

