CREATE TABLE TMCS_ASK_TANGO_CONFIG_DTL
   (	CONFIG_DTL_ID NUMBER,
	VENDOR VARCHAR2(500),
	COUNTRY VARCHAR2(500),
	VARIABLE_NAME VARCHAR2(500),
	CALC_TYPE VARCHAR2(500),
	VARIABLE_KEY VARCHAR2(500),
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE DEFAULT sysdate,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1
   ) ;
  CREATE UNIQUE INDEX TMCS_ASK_TANGO_CONFIG_DTL_PK ON TMCS_ASK_TANGO_CONFIG_DTL (VENDOR, COUNTRY, VARIABLE_NAME, CALC_TYPE)
  ;
ALTER TABLE TMCS_ASK_TANGO_CONFIG_DTL ADD CONSTRAINT TMCS_ASK_TANGO_CONFIG_DTL_PK PRIMARY KEY (VENDOR, COUNTRY, VARIABLE_NAME, CALC_TYPE)
  USING INDEX TMCS_ASK_TANGO_CONFIG_DTL_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ASK_TANGO_CONFIG_DTL_PK ON TMCS_ASK_TANGO_CONFIG_DTL (VENDOR, COUNTRY, VARIABLE_NAME, CALC_TYPE)
  ;

