CREATE TABLE TMCS_JOBS_MASTER
   (	TMCS_JOBS_MASTER_ID NUMBER,
	CLIENT_ID NUMBER,
	JOB_NAME VARCHAR2(100),
	STATUS VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_JOBS_MASTER_PK ON TMCS_JOBS_MASTER (TMCS_JOBS_MASTER_ID)
  ;
ALTER TABLE TMCS_JOBS_MASTER ADD CONSTRAINT TMCS_JOBS_MASTER_PK PRIMARY KEY (TMCS_JOBS_MASTER_ID)
  USING INDEX TMCS_JOBS_MASTER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_JOBS_MASTER_PK ON TMCS_JOBS_MASTER (TMCS_JOBS_MASTER_ID)
  ;

