CREATE TABLE TMCS_MILESTONE_TEMPLATES
   (	TEMPLATE_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	TEMPLATE_NAME VARCHAR2(200),
	DESCRIPTION VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	PROJECT_TYPE VARCHAR2(100),
	TOTAL_TASK_DURATION NUMBER,
	BU_ID NUMBER,
	AUTO_UPDATE_ENTITY_STATUS VARCHAR2(10),
	DATE_CALCULATION_FLAG VARCHAR2(50),
	LINKED_NEW_STORE_PROJ_TEMP NUMBER,
	COUNTRY VARCHAR2(100),
	RECORD_STATUS VARCHAR2(50),
	VERSION NUMBER,
	 PRIMARY KEY (TEMPLATE_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_MILESTONE_TEMPLATES_INDX2 ON TMCS_MILESTONE_TEMPLATES (CLIENT_ID, UPPER(ENTITY_TYPE), TEMPLATE_ID)
  ;

