CREATE TABLE TMCS_CUST_BRAND_OWNERSHIP
   (	BRAND_OWNERSHIP_ID NUMBER DEFAULT TMCS_CUST_BRAND_OWNERSHIP_S.NEXTVAL NOT NULL ENABLE,
	CUSTOMER_ID NUMBER,
	CUSTOMER_SITE_ID NUMBER,
	OWNERSHIP_TYPE VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	STAGING_ID NUMBER,
	 PRIMARY KEY (BRAND_OWNERSHIP_ID)
  USING INDEX  ENABLE
   ) ;

