CREATE TABLE TMCS_MAP_INFO_WINDOW_FIELDS
   (	TAB_ID NUMBER NOT NULL ENABLE,
	APP_COMPONENT_KEY VARCHAR2(300) NOT NULL ENABLE,
	INFO_FIELD_ORDER NUMBER NOT NULL ENABLE,
	INFO_FIELD_FORMATTING VARCHAR2(100),
	FIELD_ID NUMBER NOT NULL ENABLE,
	INFO_WINDOW_ID NUMBER,
	CLIENT_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	BRAND_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_INFO_WIN_FIELDS_UK ON TMCS_MAP_INFO_WINDOW_FIELDS (FIELD_ID)
  ;
ALTER TABLE TMCS_MAP_INFO_WINDOW_FIELDS ADD CONSTRAINT TMCS_MAP_INFO_WINDOW_FIELD_PK PRIMARY KEY (FIELD_ID)
  USING INDEX TMCS_MAP_INFO_WIN_FIELDS_UK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WIN_FIELDS_UK ON TMCS_MAP_INFO_WINDOW_FIELDS (FIELD_ID)
  ;

