CREATE TABLE TMCS_MARKETS_B
   (	MARKET_ID NUMBER,
	ANNUAL_PLAN NUMBER(4,0),
	CURRENT_STATUS VARCHAR2(10),
	CURRENT_VERSION NUMBER,
	TARGET_ID NUMBER,
	TARGET_SOURCE VARCHAR2(100),
	TARGET_NAME VARCHAR2(256),
	INTERSECTION VARCHAR2(100),
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	DMA VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	CITY VARCHAR2(100),
	COUNTY VARCHAR2(100),
	STATE VARCHAR2(100),
	ZIP_CODE VARCHAR2(10),
	COUNTRY VARCHAR2(100),
	REAL_ESTATE_MANAGER NUMBER,
	PROPOSED_START_DATE DATE,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	STATUS VARCHAR2(50),
	CAPITAL_EXPENSE NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_MARKETS_B_PK ON TMCS_MARKETS_B (MARKET_ID)
  ;
ALTER TABLE TMCS_MARKETS_B ADD CONSTRAINT TMCS_MARKETS_B_PK PRIMARY KEY (MARKET_ID)
  USING INDEX TMCS_MARKETS_B_PK  ENABLE;
CREATE INDEX TMCS_MARKETS_B_GIDX ON TMCS_MARKETS_B (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_MARKETS_B_PK ON TMCS_MARKETS_B (MARKET_ID)
  ;

