CREATE TABLE TMCS_ENTITY_QUESTION_ANSWERS
   (	QA_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	QUESTION_ID NUMBER,
	ANSWER_ID NUMBER,
	ANSWER_SEQ NUMBER,
	SELECTED VARCHAR2(5 CHAR) DEFAULT 'false',
	BRAND_ID NUMBER(*,0),
	CLIENT_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	QUESTION_TYPE VARCHAR2(1 CHAR) DEFAULT 'S',
	 PRIMARY KEY (QA_ID)
  USING INDEX  ENABLE
   ) ;

