CREATE TABLE TMCS_TEMPLATE_FORMULA
   (	FORMULA_ID NUMBER,
	TEMP_DETAIL_ID NUMBER,
	TEMPLATE_ID NUMBER,
	FORMULA_SEQ NUMBER,
	FORMULA_TYPE VARCHAR2(100),
	FORMULA_PART_TYPE VARCHAR2(100),
	FORMULA_PART_VALUE VARCHAR2(100),
	TABLE_NAME VARCHAR2(30),
	COLUMN_NAME VARCHAR2(30),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	FORMULA_TYPE_VALUE VARCHAR2(200),
	 PRIMARY KEY (FORMULA_ID)
  USING INDEX  ENABLE
   ) ;

