CREATE TABLE TMCS_ADF_DATA_IMPORTS
   (	IMPORT_ID NUMBER DEFAULT TMCS_ADF_DATA_IMPORTS_S.nextval,
	IMPORT_TYPE VARCHAR2(100),
	DESCRIPTION VARCHAR2(1000),
	STATUS VARCHAR2(50) DEFAULT 'N',
	FILE_NAME VARCHAR2(500),
	S3_LOCATION VARCHAR2(1000),
	NOTIFY_EMAIL VARCHAR2(1000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	GU_ID VARCHAR2(200) DEFAULT SYS_GUID(),
	PARAMS_JSON VARCHAR2(4000),
	 CONSTRAINT TMCS_ADF_DATA_IMPORTS_PK PRIMARY KEY (IMPORT_ID)
  USING INDEX  ENABLE
   ) ;

