CREATE TABLE TMCS_SEC_USER_ROLES
   (	USER_ROLE_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200),
	ENT_ROLE_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	BU_ID NUMBER,
	 PRIMARY KEY (USER_ROLE_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_SEC_USER_ROLES_INDX01 ON TMCS_SEC_USER_ROLES (USER_NAME, CLIENT_ID)
  ;
CREATE UNIQUE INDEX UK_TMCS_SEC_USER_ROLES ON TMCS_SEC_USER_ROLES (CLIENT_ID, BRAND_ID, COUNTRY_CODE, USER_NAME, ENT_ROLE_ID)
  ;
CREATE INDEX TMCS_SEC_USER_ROLES_INDX02 ON TMCS_SEC_USER_ROLES (CLIENT_ID, USER_NAME, COUNTRY_CODE)
  ;

