CREATE TABLE TMCS_SUPPLIER_SITE_CONTACTS
   (	CONTACT_ID NUMBER,
	SUPPLIER_ID NUMBER,
	SUPPLIER_SITE_ID NUMBER,
	ROLE VARCHAR2(50),
	NAME VARCHAR2(200),
	LAST_NAME VARCHAR2(100),
	BUSINESS_PHONE VARCHAR2(50),
	EXTENSION VARCHAR2(50),
	CELLPHONE VARCHAR2(50),
	EMAIL VARCHAR2(250),
	FAX VARCHAR2(50),
	COMMENTS VARCHAR2(2000),
	COMPANY VARCHAR2(150),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CONTACT_USER_ID VARCHAR2(100),
	EXT_CONTACT_NUMBER VARCHAR2(50),
	IS_SYSTEM_USER VARCHAR2(1),
	STATUS VARCHAR2(50),
	CONTACT_TYPE VARCHAR2(50),
	TITLE VARCHAR2(100),
	STAGING_ID VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_SUPPLIER_SITE_CONTACTS_PK ON TMCS_SUPPLIER_SITE_CONTACTS (CONTACT_ID)
  ;
ALTER TABLE TMCS_SUPPLIER_SITE_CONTACTS ADD CONSTRAINT TMCS_SUPPLIER_SITE_CONTACTS_PK PRIMARY KEY (CONTACT_ID)
  USING INDEX TMCS_SUPPLIER_SITE_CONTACTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SUPPLIER_SITE_CONTACTS_PK ON TMCS_SUPPLIER_SITE_CONTACTS (CONTACT_ID)
  ;

