CREATE TABLE TMCS_USER_BUSINESS_UNITS_HIST
   (	USER_BU_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200) NOT NULL ENABLE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	BU_ID NUMBER NOT NULL ENABLE,
	ROLE_SEC_TYPE VARCHAR2(20),
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ACTION VARCHAR2(50),
	HISTORY_CREATION_DATE DATE DEFAULT sysdate,
	HISTORY_CREATED_BY VARCHAR2(100)
   ) ;

