CREATE TABLE TMCS_ANALOG_STORE_TA
   (	STORE_ID NUMBER,
	STORE_NUMBER VARCHAR2(50),
	TA_TYPE NUMBER,
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	N_EXT_ATTR11 NUMBER,
	N_EXT_ATTR12 NUMBER,
	N_EXT_ATTR13 NUMBER,
	N_EXT_ATTR14 NUMBER,
	N_EXT_ATTR15 NUMBER,
	N_EXT_ATTR16 NUMBER,
	N_EXT_ATTR17 NUMBER,
	N_EXT_ATTR18 NUMBER,
	N_EXT_ATTR19 NUMBER,
	N_EXT_ATTR20 NUMBER,
	N_EXT_ATTR21 NUMBER,
	N_EXT_ATTR22 NUMBER,
	N_EXT_ATTR23 NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	N_EXT_ATTR29 NUMBER,
	N_EXT_ATTR30 NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_ANALOG_STORE_TA_PK ON TMCS_ANALOG_STORE_TA (STORE_ID, TA_TYPE)
  ;
ALTER TABLE TMCS_ANALOG_STORE_TA ADD CONSTRAINT TMCS_ANALOG_STORE_TA_PK PRIMARY KEY (STORE_ID, TA_TYPE)
  USING INDEX TMCS_ANALOG_STORE_TA_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ANALOG_STORE_TA_PK ON TMCS_ANALOG_STORE_TA (STORE_ID, TA_TYPE)
  ;
CREATE INDEX TMCS_ANALOG_STORE_TA_INDX01 ON TMCS_ANALOG_STORE_TA (STORE_ID)
  ;

