CREATE TABLE TMCS_SUPPLIER_USERS
   (	SU_ID NUMBER,
	USER_NAME VARCHAR2(200) NOT NULL ENABLE,
	SUPPLIER_ID NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	 CONSTRAINT TMCS_SUPPLIER_USERS_PK PRIMARY KEY (SU_ID)
  USING INDEX  ENABLE
   ) ;

