CREATE TABLE TMCS_LOOKUP_TYPES_HIST
   (	LOOKUP_ID NUMBER(*,0) NOT NULL ENABLE,
	LOOKUP_CODE VARCHAR2(50) NOT NULL ENABLE,
	LOOKUP_NAME VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(300) NOT NULL ENABLE,
	SECURITY_LEVEL VARCHAR2(1) NOT NULL ENABLE,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	COUNTRY VARCHAR2(20),
	BU_ID NUMBER,
	DEFAULT_VALUE VARCHAR2(300),
	DIVISION_ID NUMBER,
	COMMENTS VARCHAR2(4000),
	MODULE_NAME VARCHAR2(100)
   ) ;
CREATE INDEX LOOKUP_HIST_PK ON TMCS_LOOKUP_TYPES_HIST (LOOKUP_ID)
  ;

