CREATE TABLE TMCS_EXCHANGE_RATES_HIST_210614
   (	EXCHG_RATE_ID NUMBER(15,0),
	SOURCE_CURRENCY_CODE VARCHAR2(15),
	TO_CURRENCY_CODE VARCHAR2(15),
	EXCHANGE_RATE NUMBER,
	EXCHG_RATE_DATE DATE,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	CLIENT_ID NUMBER(*,0),
	COUNTRY VARCHAR2(100),
	BRAND_ID NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	EFFECTIVE_DATE DATE,
	END_DATE DATE,
	EXCHANGE_RATE_AVG NUMBER,
	EXCHANGE_RATES_HIST_ID NUMBER
   ) ;

