CREATE TABLE TMCS_MAP_BOOKMARKS
   (	BOOKMARK_ID NUMBER NOT NULL ENABLE,
	BOOKMARK_NAME VARCHAR2(500),
	BOOKMARK_DESC VARCHAR2(500),
	BOOKMARK_TYPE VARCHAR2(50),
	BOOKMARK_VALUE VARCHAR2(4000),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	THUMBNAIL BLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_BOOKMARKS_PK ON TMCS_MAP_BOOKMARKS (BOOKMARK_ID)
  ;
ALTER TABLE TMCS_MAP_BOOKMARKS ADD CONSTRAINT TMCS_MAP_BOOKMARKS_PK PRIMARY KEY (BOOKMARK_ID)
  USING INDEX TMCS_MAP_BOOKMARKS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_BOOKMARKS_PK ON TMCS_MAP_BOOKMARKS (BOOKMARK_ID)
  ;

