CREATE TABLE TMCS_CLIENT_HOLIDAYS
   (	HOLIDAY_ID NUMBER DEFAULT TMCS_CLIENT_HOLIDAYS_S.NEXTVAL,
	HOLIDAY_NAME VARCHAR2(100),
	HOLIDAY_DATE DATE,
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	 PRIMARY KEY (HOLIDAY_ID)
  USING INDEX  ENABLE
   ) ;

