CREATE TABLE TMCS_GEOFENCE_DATA
   (	GFENCE_ID NUMBER,
	GFENCE_NUMBER VARCHAR2(500),
	GFENCE_NAME VARCHAR2(500),
	GFENCE_DESCRIPTION VARCHAR2(500),
	GFENCE_TYPE VARCHAR2(500),
	GFENCE_UM_UID VARCHAR2(500),
	STATUS VARCHAR2(500),
	BRAND_NAME VARCHAR2(500),
	CHAIN_ID NUMBER,
	HASH_ID VARCHAR2(500),
	GEOMETRY SDO_GEOMETRY,
	START_DATE TIMESTAMP (6),
	END_DATE TIMESTAMP (6),
	LAST_REFRESH_DATE TIMESTAMP (6),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(50),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(50),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_GEOFENCE_DATA_PK ON TMCS_GEOFENCE_DATA (GFENCE_ID)
  ;
ALTER TABLE TMCS_GEOFENCE_DATA ADD CONSTRAINT TMCS_GEOFENCE_DATA_PK PRIMARY KEY (GFENCE_ID)
  USING INDEX TMCS_GEOFENCE_DATA_PK  ENABLE;
CREATE INDEX TMCS_GEOFENCE_DATA_GIDX ON TMCS_GEOFENCE_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_GEOFENCE_DATA_PK ON TMCS_GEOFENCE_DATA (GFENCE_ID)
  ;
-- COMMENT --

   COMMENT ON COLUMN TMCS_GEOFENCE_DATA.CHAIN_ID IS 'CHAIN_ID from  ChainXY table';
   COMMENT ON COLUMN TMCS_GEOFENCE_DATA.LAST_REFRESH_DATE IS 'FROM UBERMEDIA';
   COMMENT ON COLUMN TMCS_GEOFENCE_DATA.CREATED_BY IS 'UBERMEDIA / TANGO / CLIENT User';
   COMMENT ON COLUMN TMCS_GEOFENCE_DATA.LAST_UPDATE_DATE IS 'FROM TANGO SYSTEM';
   COMMENT ON COLUMN TMCS_GEOFENCE_DATA.LAST_UPDATED_BY IS '/ TANGO / CLIENT';
