CREATE TABLE TMCS_CLIENT_GROUPS
   (	GROUP_ID NUMBER,
	GROUP_NAME VARCHAR2(50) NOT NULL ENABLE,
	GROUP_DESC VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (GROUP_ID)
  USING INDEX  ENABLE
   ) ;

