CREATE TABLE TMCS_US_STATE_BOUNDARY
   (	COUNTRY NUMBER(19,0),
	GEO_ID VARCHAR2(61),
	STATE VARCHAR2(3),
	NAME VARCHAR2(91),
	LSAD VARCHAR2(8),
	CENSUSAREA NUMBER(19,0),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

