CREATE TABLE TMCS_USER_GROUPS
   (	USER_GROUP_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200),
	GROUP_ID NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	 PRIMARY KEY (USER_GROUP_ID)
  USING INDEX  ENABLE
   ) ;
CREATE UNIQUE INDEX UK_TMCS_USER_GROUPS ON TMCS_USER_GROUPS (CLIENT_ID, USER_NAME, GROUP_ID)
  ;

