CREATE TABLE TMCS_PROJECT_STORE_ASSOC
   (	ASSOC_ID NUMBER,
	PROJECT_ID NUMBER,
	STORE_ID NUMBER,
	D_EXT_ATTR01 DATE,
	D_EXT_ATTR02 DATE,
	D_EXT_ATTR03 DATE,
	D_EXT_ATTR04 DATE,
	D_EXT_ATTR05 DATE,
	D_EXT_ATTR06 DATE,
	D_EXT_ATTR07 DATE,
	D_EXT_ATTR08 DATE,
	D_EXT_ATTR09 DATE,
	D_EXT_ATTR10 DATE,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	D_EXT_ATTR11 DATE,
	D_EXT_ATTR12 DATE,
	D_EXT_ATTR13 DATE,
	D_EXT_ATTR14 DATE,
	D_EXT_ATTR15 DATE,
	D_EXT_ATTR16 DATE,
	D_EXT_ATTR17 DATE,
	D_EXT_ATTR18 DATE,
	D_EXT_ATTR19 DATE,
	D_EXT_ATTR20 DATE
   ) ;
  CREATE UNIQUE INDEX TMCS_PROJECT_STORE_ASSOC_PK ON TMCS_PROJECT_STORE_ASSOC (ASSOC_ID)
  ;
ALTER TABLE TMCS_PROJECT_STORE_ASSOC ADD CONSTRAINT TMCS_PROJECT_STORE_ASSOC_PK PRIMARY KEY (ASSOC_ID)
  USING INDEX TMCS_PROJECT_STORE_ASSOC_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROJECT_STORE_ASSOC_PK ON TMCS_PROJECT_STORE_ASSOC (ASSOC_ID)
  ;

