CREATE TABLE TMCS_FOLDER_TEMPLATE_DETAIL
   (	FOLDER_TEMPLATE_DTL_ID NUMBER DEFAULT TMCS_FOLDER_TEMPLATE_DETAIL_S.NEXTVAL,
	FOLDER_TEMPLATE_ID NUMBER,
	FOLDER_SEQUENCE NUMBER,
	FOLDER_NAME VARCHAR2(250),
	DESCRIPTION VARCHAR2(250),
	PARENT_FOLDER_ID NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(50),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	STATUS VARCHAR2(50),
	VERSION NUMBER,
	 PRIMARY KEY (FOLDER_TEMPLATE_DTL_ID)
  USING INDEX  ENABLE
   ) ;

