CREATE TABLE TMCS_EXT_AUTH_DETAIL_HIST
   (	EXT_AUTH_DETAIL_ID NUMBER,
	EXT_AUTH_ID NUMBER,
	TASK_ID NUMBER,
	CURRENCY VARCHAR2(50),
	RATE NUMBER,
	QTY NUMBER,
	UOM VARCHAR2(50),
	AMOUNT NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	PO_ID NUMBER,
	BRAND_ID NUMBER,
	ITEM_SEQ_NO NUMBER,
	STATUS VARCHAR2(250),
	RETAINAGE_PCT NUMBER
   ) ;

