CREATE TABLE TMCS_CLIENT_TERMS
   (	TERMS_ID NUMBER DEFAULT TMCS_CLIENT_TERMS_S.NEXTVAL,
	VERSION NUMBER DEFAULT 1 NOT NULL ENABLE,
	LANGUAGE_CODE VARCHAR2(10),
	TERMS CLOB,
	STATUS VARCHAR2(50),
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	USER_TYPE VARCHAR2(20) DEFAULT 'CORPORATE',
	 CONSTRAINT TMCS_CLIENT_TERMS_PK PRIMARY KEY (TERMS_ID)
  USING INDEX  ENABLE
   ) ;

