CREATE TABLE TMCS_DESIGNATEDMARKETAREAS
   (	ID VARCHAR2(25),
	NAME VARCHAR2(57),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	COUNTRY VARCHAR2(10),
	DMA_ID NUMBER NOT NULL ENABLE,
	MBR_EXTENT_COORDINATES VARCHAR2(320)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_DESIGNATEDMARKETAREAS_PK ON TMCS_DESIGNATEDMARKETAREAS (ID, COUNTRY)
  ;
ALTER TABLE TMCS_DESIGNATEDMARKETAREAS ADD CONSTRAINT TMCS_DESIGNATEDMARKETAREAS_PK PRIMARY KEY (ID, COUNTRY)
  USING INDEX TMCS_DESIGNATEDMARKETAREAS_PK  ENABLE;
CREATE INDEX TMCS_DESIGNATEDMA_GIDX ON TMCS_DESIGNATEDMARKETAREAS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_DESIGNATEDMARKETAREAS_PK ON TMCS_DESIGNATEDMARKETAREAS (ID, COUNTRY)
  ;

