CREATE TABLE TMCS_PROSPECTS_BATCH_HEADER
   (	BATCH_ID NUMBER,
	BATCH_DESC VARCHAR2(1000),
	STATUS VARCHAR2(20),
	ICON_COLOR VARCHAR2(20),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	DISPLAY_MAP VARCHAR2(320)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROSPECTS_BATCH_HEADER_PK ON TMCS_PROSPECTS_BATCH_HEADER (BATCH_ID)
  ;
ALTER TABLE TMCS_PROSPECTS_BATCH_HEADER ADD CONSTRAINT TMCS_PROSPECTS_BATCH_HEADER_PK PRIMARY KEY (BATCH_ID)
  USING INDEX TMCS_PROSPECTS_BATCH_HEADER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROSPECTS_BATCH_HEADER_PK ON TMCS_PROSPECTS_BATCH_HEADER (BATCH_ID)
  ;

