CREATE TABLE TMCS_MEETING_MINUTES
   (	MEETING_ID NUMBER,
	ORGANIZER VARCHAR2(100),
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	MEETING_DATE DATE,
	START_TIME VARCHAR2(100),
	END_TIME VARCHAR2(100),
	MEETING_TITLE VARCHAR2(250),
	OBJECTIVE VARCHAR2(1000),
	AGENDA VARCHAR2(1000),
	NOTES VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	LOCATION VARCHAR2(1000),
	WEBEX_CALL_IN VARCHAR2(100),
	NEXT_LOCATION VARCHAR2(1000),
	NEXT_WEBEX_CALL_IN VARCHAR2(100),
	DISTRIBUTION_DATE DATE,
	MEETING_NUMBER VARCHAR2(100),
	STATUS VARCHAR2(100),
	MEETING_TYPE VARCHAR2(50),
	 PRIMARY KEY (MEETING_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_MEETING_MINUTES_INDX02 ON TMCS_MEETING_MINUTES (ENTITY_TYPE, ENTITY_ID)
  ;

