CREATE TABLE TMCS_INDEX_REPORT_VALUES
   (	ENTITY_TYPE VARCHAR2(200),
	ENTITY_ID VARCHAR2(200),
	TA_TYPE VARCHAR2(200),
	STATUS VARCHAR2(200),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	DEMO_OBJ TMCS_DEMO_RPT_NT ,
	TA_ID NUMBER
   )
 NESTED TABLE DEMO_OBJ STORE AS DEMO_NTABLE
 RETURN AS VALUE;

