CREATE TABLE TMCS_RFI_NOTIFICATIONS
   (	RFI_NOTIFICATION_ID NUMBER DEFAULT TMCS_RFI_NOTIFICATIONS_S.NEXTVAL,
	RFI_ID NUMBER,
	USER_NAME VARCHAR2(200),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (RFI_NOTIFICATION_ID)
  USING INDEX  ENABLE
   ) ;

