CREATE TABLE TMCS_CLIENT_REPORT_PARAMS_1001
   (	REP_PARAM_ID NUMBER NOT NULL ENABLE,
	REPORT_ID NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	PARAM_NAME VARCHAR2(200) NOT NULL ENABLE,
	PARAM_TYPE VARCHAR2(50),
	PARAM_LOV_CODE VARCHAR2(50),
	PARAM_SEQ NUMBER,
	COUNTRY VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	PARAM_KEY VARCHAR2(50) NOT NULL ENABLE,
	LOV_TYPE VARCHAR2(20),
	LOV_QUERY VARCHAR2(4000)
   ) ;

