CREATE TABLE TMCS_DMS_APPROVAL_DOCS
   (	APPROVAL_ID NUMBER NOT NULL ENABLE,
	ENTITY_ID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(50),
	DOCUMENT_TYPE VARCHAR2(100),
	DESCRIPTION VARCHAR2(300),
	FILE_ID NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	STATUS VARCHAR2(50),
	REQUESTOR VARCHAR2(50),
	ATTACHED_BY VARCHAR2(50),
	REQUIRED VARCHAR2(10) DEFAULT 'N',
	SEQ_NO NUMBER,
	AWS_KEY VARCHAR2(500),
	AWS_VERSION_ID VARCHAR2(100),
	TEMPLATE VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX TMCS_DMS_APPROVAL_DOCS_PK ON TMCS_DMS_APPROVAL_DOCS (APPROVAL_ID)
  ;
ALTER TABLE TMCS_DMS_APPROVAL_DOCS ADD CONSTRAINT TMCS_DMS_APPROVAL_DOCS_PK PRIMARY KEY (APPROVAL_ID)
  USING INDEX TMCS_DMS_APPROVAL_DOCS_PK  ENABLE;
CREATE INDEX TMCS_DMS_APPROVAL_DOCS_INDX2 ON TMCS_DMS_APPROVAL_DOCS (ENTITY_TYPE, ENTITY_ID)
  ;
CREATE UNIQUE INDEX TMCS_DMS_APPROVAL_DOCS_PK ON TMCS_DMS_APPROVAL_DOCS (APPROVAL_ID)
  ;

