CREATE TABLE TMCS_STORE_AUDIT_LOG
   (	AUDIT_ID NUMBER DEFAULT TMCS_STORE_AUDIT_LOG_S.NEXTVAL,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	SUB_ENTITY_TYPE VARCHAR2(50),
	SUB_ENTITY_ID NUMBER,
	COMPONENT_KEY VARCHAR2(100),
	TABLE_NAME VARCHAR2(100),
	COLUMN_NAME VARCHAR2(100),
	DATA_TYPE VARCHAR2(100),
	OLD_VALUE VARCHAR2(4000),
	NEW_VALUE VARCHAR2(4000),
	OLD_VALUE_NUM VARCHAR2(4000),
	NEW_VALUE_NUM VARCHAR2(4000),
	OLD_VALUE_DATE VARCHAR2(4000),
	NEW_VALUE_DATE VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (AUDIT_ID)
  USING INDEX  ENABLE
   ) ;

