CREATE TABLE TMCS_LOOKUP_VALUES_CUST_HIST
   (	LOOKUP_VALUE_ID NUMBER(*,0) NOT NULL ENABLE,
	LANGUAGE_CODE VARCHAR2(300) NOT NULL ENABLE,
	NAME VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(240),
	CLIENT_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	BRAND_ID NUMBER,
	LOOKUP_ID NUMBER
   ) ;
CREATE INDEX TMCS_LOOKUP_VAL_CUST_IN02 ON TMCS_LOOKUP_VALUES_CUST_HIST (LOOKUP_ID, LOOKUP_VALUE_ID)
  ;

