CREATE TABLE TMCS_LANDUSE_DATA
   (	LAND_ID VARCHAR2(64),
	LAND_TYPE VARCHAR2(64),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_LANDUSE_DATA_PK ON TMCS_LANDUSE_DATA (LAND_ID, LAND_TYPE)
  ;
ALTER TABLE TMCS_LANDUSE_DATA ADD CONSTRAINT TMCS_LANDUSE_DATA_PK PRIMARY KEY (LAND_ID, LAND_TYPE)
  USING INDEX TMCS_LANDUSE_DATA_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_LANDUSE_DATA_PK ON TMCS_LANDUSE_DATA (LAND_ID, LAND_TYPE)
  ;
CREATE INDEX TMCS_LANDUSE_DATA_GIDX ON TMCS_LANDUSE_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

