CREATE TABLE TMCS_SEC_TAADMIN_ROLE_MAP
   (	ROLE_MAP_ID NUMBER DEFAULT TMCS_SEC_TAADMIN_ROLE_MAP_S.NEXTVAL,
	ENT_ROLE_NAME VARCHAR2(50) NOT NULL ENABLE,
	APP_ROLE_NAME VARCHAR2(50) NOT NULL ENABLE,
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	BU_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SEC_TAADMIN_ROLE_MAP_PK ON TMCS_SEC_TAADMIN_ROLE_MAP (ROLE_MAP_ID)
  ;
ALTER TABLE TMCS_SEC_TAADMIN_ROLE_MAP ADD PRIMARY KEY (ROLE_MAP_ID)
  USING INDEX TMCS_SEC_TAADMIN_ROLE_MAP_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SEC_TAADMIN_ROLE_MAP_PK ON TMCS_SEC_TAADMIN_ROLE_MAP (ROLE_MAP_ID)
  ;

