CREATE TABLE TMCS_ALL_STORE_FIN_HISTORY
   (	HISTORY_ID NUMBER DEFAULT tmcs.TMCS_ALL_STORE_FIN_HISTORY_S.nextval,
	STORE_ID NUMBER,
	FIN_GROUP VARCHAR2(100),
	CATEGORY VARCHAR2(100),
	FISCAL_PERIOD NUMBER,
	FISCAL_YEAR NUMBER,
	FISCAL_WEEK_NUMBER NUMBER,
	FISCAL_QUARTER NUMBER,
	START_DATE DATE,
	END_DATE DATE,
	CURRENCY_CODE VARCHAR2(100),
	AMOUNT NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	 PRIMARY KEY (HISTORY_ID)
  USING INDEX  ENABLE
   ) ;

