CREATE TABLE TMCS_USER_CONTEXT_LOG
   (	GUID VARCHAR2(100),
	USER_NAME VARCHAR2(200),
	CONTEXT_DATE DATE,
	DESCRIPTION VARCHAR2(100),
	SESSION_ID VARCHAR2(100),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(100),
	REGION_ID NUMBER,
	ORACLE_SID NUMBER
   ) ;

