CREATE TABLE TMCS_BUDGET_CHG_DETAIL_HIST
   (	BUDGET_CHG_DETAIL_ID NUMBER,
	BUDGET_CHG_ID NUMBER,
	TASK_ID NUMBER,
	INITIAL_BUDGET NUMBER,
	APPROVED_BUDGET NUMBER,
	TOTAL_APPROVED_BUDGET NUMBER,
	RELEASE_PCT NUMBER,
	RELEASE_AMOUNT NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_ID NUMBER,
	ITEM_SEQ_NO NUMBER,
	STATUS VARCHAR2(50)
   ) ;

