CREATE TABLE TMCS_SNR_BUFFER
   (	SCENARIO_ID NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SNR_BUFFER_PK ON TMCS_SNR_BUFFER (SCENARIO_ID)
  ;
ALTER TABLE TMCS_SNR_BUFFER ADD CONSTRAINT TMCS_SNR_BUFFER_PK PRIMARY KEY (SCENARIO_ID)
  USING INDEX TMCS_SNR_BUFFER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SNR_BUFFER_PK ON TMCS_SNR_BUFFER (SCENARIO_ID)
  ;
CREATE INDEX TMCS_SNR_BUFFER_GIDX ON TMCS_SNR_BUFFER (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

