CREATE TABLE TMCS_SITE_SF_SNR_SITES
   (	SFS_ID NUMBER,
	SF_ID NUMBER,
	SITE_ID NUMBER,
	SITE_NAME VARCHAR2(100),
	ADDRESS VARCHAR2(500),
	CITY VARCHAR2(100),
	STATE VARCHAR2(100),
	ZIP VARCHAR2(100),
	SALES NUMBER,
	EBITA NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	SELECT_FLAG VARCHAR2(1),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	SEC_ATTR1 VARCHAR2(50),
	SEC_ATTR2 VARCHAR2(50)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SITE_SF_SNR_SITES_PK ON TMCS_SITE_SF_SNR_SITES (SFS_ID)
  ;
ALTER TABLE TMCS_SITE_SF_SNR_SITES ADD CONSTRAINT TMCS_SITE_SF_SNR_SITES_PK PRIMARY KEY (SFS_ID)
  USING INDEX TMCS_SITE_SF_SNR_SITES_PK  ENABLE;
CREATE INDEX TMCS_SITE_SF_SNR_SITES_GIDX ON TMCS_SITE_SF_SNR_SITES (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_SITE_SF_SNR_SITES_PK ON TMCS_SITE_SF_SNR_SITES (SFS_ID)
  ;

