CREATE TABLE TMCS_BATCH_REP_HEADER_DTL
   (	BATCH_DETAIL_ID NUMBER DEFAULT ON NULL TMCS_BATCH_REP_HEADER_DTL_S.NEXTVAL NOT NULL ENABLE,
	BATCH_ID NUMBER,
	ENTITY_TYPE VARCHAR2(3200),
	ENTITY_NUMBER VARCHAR2(3200),
	COUNTRY VARCHAR2(3200),
	STATUS VARCHAR2(4000),
	MESSAGE VARCHAR2(4000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (BATCH_DETAIL_ID)
  USING INDEX  ENABLE
   ) ;

