CREATE TABLE TMCS_SEC_USER_GROUP_ASSN
   (	USER_NAME VARCHAR2(200),
	GROUP_ID NUMBER,
	CAN_EDIT VARCHAR2(50),
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SEC_USER_GROUP_ASSN_PK ON TMCS_SEC_USER_GROUP_ASSN (USER_NAME, GROUP_ID)
  ;
ALTER TABLE TMCS_SEC_USER_GROUP_ASSN ADD CONSTRAINT TMCS_SEC_USER_GROUP_ASSN_PK PRIMARY KEY (USER_NAME, GROUP_ID)
  USING INDEX TMCS_SEC_USER_GROUP_ASSN_PK  ENABLE;
CREATE INDEX TMCS_SEC_USER_GROUP_ASSN_INDX01 ON TMCS_SEC_USER_GROUP_ASSN (GROUP_ID)
  ;
CREATE UNIQUE INDEX TMCS_SEC_USER_GROUP_ASSN_PK ON TMCS_SEC_USER_GROUP_ASSN (USER_NAME, GROUP_ID)
  ;

