CREATE TABLE TMCS_SEEDS_POINTS
   (	SEED_ID VARCHAR2(11),
	SEED_NAME VARCHAR2(64),
	CITY VARCHAR2(64),
	STATE VARCHAR2(30),
	DMA NUMBER(19,0),
	CBSA_CLASS NUMBER(10,0),
	STORE_CLASS NUMBER(10,0),
	SALES_FORECAST NUMBER,
	CANNIBALIZATION NUMBER(17,3),
	GREENFIELD_FORECAST NUMBER(19,0),
	CLIENT_ID NUMBER(19,0),
	BRAND_ID NUMBER(19,0),
	C_EXT_ATTR1 VARCHAR2(254),
	C_EXT_ATTR2 VARCHAR2(254),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	ADDRESS VARCHAR2(4000),
	ZIP VARCHAR2(10),
	CBSA_NUMBER NUMBER(10,0),
	CBSA_NAME VARCHAR2(64),
	MALL_QUALITY NUMBER,
	PROTO_TYPE NUMBER,
	FLR_SQFT NUMBER(10,0),
	TOTAL_HOUSEHOLDS_TA NUMBER(10,0),
	PCT_TOTAL_25_39_YRS_TA NUMBER(8,2),
	PRED1 NUMBER(10,0),
	PRED2 NUMBER(10,0),
	RAT NUMBER(4,2),
	LATITUDE NUMBER(10,6),
	LONGITUDE NUMBER(10,6),
	SOURCE VARCHAR2(3200),
	SOURCE_ID VARCHAR2(320),
	SITE_TYPE VARCHAR2(32),
	EBITDA NUMBER,
	SALES_FORECAST_2 NUMBER,
	CANNIBALIZATION_2 NUMBER,
	GREENFIELD_FORECAST_2 NUMBER,
	STORE_SIZE NUMBER,
	ORG_ID NUMBER,
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	COUNTRY VARCHAR2(32),
	COUNTY VARCHAR2(500),
	COUNTY_FIPS VARCHAR2(500),
	DMA_NAME VARCHAR2(500),
	SEC_ATTR1 VARCHAR2(50),
	SEC_ATTR2 VARCHAR2(50)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SEEDS_POINTS_PK ON TMCS_SEEDS_POINTS (SEED_ID, CLIENT_ID, COUNTRY)
  ;
ALTER TABLE TMCS_SEEDS_POINTS ADD CONSTRAINT TMCS_SEEDS_POINTS_PK PRIMARY KEY (SEED_ID, CLIENT_ID, COUNTRY)
  USING INDEX TMCS_SEEDS_POINTS_PK  ENABLE;
CREATE INDEX TMCS_SEEDS_POINTSS_GIDX ON TMCS_SEEDS_POINTS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS (' WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_SEEDS_POINTS_PK ON TMCS_SEEDS_POINTS (SEED_ID, CLIENT_ID, COUNTRY)
  ;

