CREATE TABLE TMCS_BUDGETS_HIST
   (	BUDGET_ID NUMBER,
	ENTITY_TYPE VARCHAR2(100),
	ENTITY_ID NUMBER,
	TASK_NAME VARCHAR2(500),
	DESCRIPTION VARCHAR2(1000),
	INITIAL_BUDGET NUMBER,
	APPROVED_BUDGET NUMBER,
	COMMITMENT NUMBER,
	CHANGE_ORDER NUMBER,
	ACTUAL_COST NUMBER,
	ESTIMATED_COST NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200)
   ) ;

