CREATE TABLE TMCS_SNR
   (	SCENARIO_ID NUMBER,
	SCENARIO_NAME VARCHAR2(100),
	MARKET_ID VARCHAR2(4000),
	MARKET_NAME VARCHAR2(4000),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	DESCRIPTION VARCHAR2(2000),
	LATITUDE1 NUMBER,
	LONGITUDE1 NUMBER,
	LATITUDE2 NUMBER,
	LONGITUDE2 NUMBER,
	N_EXT_ATTR01 NUMBER,
	N_EXT_ATTR02 NUMBER,
	N_EXT_ATTR03 NUMBER,
	N_EXT_ATTR04 NUMBER,
	N_EXT_ATTR05 NUMBER,
	N_EXT_ATTR06 NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	N_EXT_ATTR07 NUMBER,
	N_EXT_ATTR08 NUMBER,
	N_EXT_ATTR09 NUMBER,
	N_EXT_ATTR10 NUMBER,
	N_EXT_ATTR11 NUMBER,
	C_EXT_ATTR01 VARCHAR2(50),
	C_EXT_ATTR02 VARCHAR2(50),
	C_EXT_ATTR03 VARCHAR2(50),
	C_EXT_ATTR04 VARCHAR2(50),
	C_EXT_ATTR05 VARCHAR2(50),
	SNR_VIEW_RESULT VARCHAR2(10),
	STATUS VARCHAR2(20),
	SELECTED_IDS VARCHAR2(4000),
	SNR_TYPE VARCHAR2(100),
	SNR_STATUS VARCHAR2(100),
	N_EXT_ATTR12 NUMBER,
	N_EXT_ATTR13 NUMBER,
	N_EXT_ATTR14 NUMBER,
	N_EXT_ATTR15 NUMBER,
	COUNTRY VARCHAR2(200),
	BRAND_ID NUMBER(*,0),
	SUM_N_ATTR1 NUMBER,
	SUM_N_ATTR2 NUMBER,
	SUM_N_ATTR3 NUMBER,
	SUM_N_ATTR4 NUMBER,
	SUM_N_ATTR5 NUMBER,
	SUM_N_ATTR6 NUMBER,
	RUN_DATE DATE,
	FILTER_TYPE VARCHAR2(500),
	SEEDPOINT_TYPE VARCHAR2(50) DEFAULT 'Standard',
	SEC_ATTR1 VARCHAR2(50),
	SEC_ATTR2 VARCHAR2(50),
	EQUATION_NAME VARCHAR2(320)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SNR_PK ON TMCS_SNR (SCENARIO_ID)
  ;
ALTER TABLE TMCS_SNR ADD CONSTRAINT TMCS_SNR_PK PRIMARY KEY (SCENARIO_ID)
  USING INDEX TMCS_SNR_PK  ENABLE;
CREATE INDEX TMCS_SNR_GIDX ON TMCS_SNR (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_SNR_PK ON TMCS_SNR (SCENARIO_ID)
  ;

