CREATE TABLE TMCS_PROJECT_SUPPLIERS
   (	PROJ_SUPP_ID NUMBER,
	PROJECT_ID NUMBER,
	SUPPLIER_ID NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(250),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	SUPPLIER_RATING NUMBER,
	DOCUMENT_ACCESS VARCHAR2(100),
	COMMENTS VARCHAR2(4000),
	STAGING_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_PROJECT_SUPPLIERS_PK ON TMCS_PROJECT_SUPPLIERS (PROJ_SUPP_ID)
  ;
ALTER TABLE TMCS_PROJECT_SUPPLIERS ADD CONSTRAINT TMCS_PROJECT_SUPPLIERS_PK PRIMARY KEY (PROJ_SUPP_ID)
  USING INDEX TMCS_PROJECT_SUPPLIERS_PK  ENABLE;
CREATE INDEX TMCS_PROJECT_SUPPLIERS_INDX01 ON TMCS_PROJECT_SUPPLIERS (PROJECT_ID, SUPPLIER_ID)
  ;
CREATE UNIQUE INDEX TMCS_PROJECT_SUPPLIERS_PK ON TMCS_PROJECT_SUPPLIERS (PROJ_SUPP_ID)
  ;

