CREATE TABLE TMCS_FTP_INTG_CONFIG_SETUP
   (	HEADER_CONFIG_ID NUMBER DEFAULT TMCS_FTP_INTG_CONFIG_SETUP_S.NEXTVAL NOT NULL ENABLE,
	INTG_NAME VARCHAR2(300) NOT NULL ENABLE,
	INTG_TYPE VARCHAR2(300),
	PACKAGE_NAME VARCHAR2(200),
	CLIENT_ID NUMBER,
	COUNTRY_CODE VARCHAR2(20),
	CREATED_DATE DATE DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	INTG_CODE VARCHAR2(100),
	STANDARD_INTG VARCHAR2(10) DEFAULT 'Y',
	 CONSTRAINT TMCS_FTP_INTG_CONFIG_SETUP_PK PRIMARY KEY (HEADER_CONFIG_ID)
  USING INDEX  ENABLE
   ) ;

