CREATE TABLE TMCS_FTP_TIMEZONES
   (	TIMEZONE_CODE VARCHAR2(100),
	TIMEZONE_NAME VARCHAR2(100),
	CREATED_BY VARCHAR2(500),
	CREATION_DATE TIMESTAMP (6),
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	LAST_UPDATED_BY VARCHAR2(500),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATE_LOGIN NUMBER
   ) ;

