CREATE TABLE TMCS_CLIENT_ASSOSIATIONS
   (	CLIENT_ASSOSIATION_ID NUMBER DEFAULT TMCS_CLIENT_ASSOSIATIONS_S.nextval,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	ASSOSIATED_CLIENT_ID NUMBER NOT NULL ENABLE,
	STATUS VARCHAR2(10) DEFAULT 'A',
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	 CONSTRAINT TMCS_CLIENT_ASSOSIATIONS_PK PRIMARY KEY (CLIENT_ASSOSIATION_ID)
  USING INDEX  ENABLE
   ) ;

