CREATE TABLE TMCS_INDEX_RPT_CONFIG
   (	ENTITY_TYPE VARCHAR2(200),
	TA_TYPE VARCHAR2(200),
	TA_RANGE NUMBER,
	TA_UNIT VARCHAR2(200),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(200),
	BU_ID NUMBER
   ) ;

