CREATE TABLE TMCS_REST_TABLE_CONFIG
   (	SERVICE_NAME VARCHAR2(250),
	SERVICE_TABLE_NAME VARCHAR2(100),
	SERVICE_COLUMN_NAME VARCHAR2(100),
	SERVICE_PARAM_NAME VARCHAR2(200),
	SERVICE_PARAM_MANDATORY VARCHAR2(1) DEFAULT 'N',
	SERVICE_PARAM_DATATYPE VARCHAR2(50),
	SERVICE_PARAM_VALUE VARCHAR2(50),
	SERVICE_PARAM_FORMAT VARCHAR2(50)
   ) ;

