CREATE TABLE TMCS_CLIENT_REPORTS
   (	REPORT_ID NUMBER DEFAULT TMCS_CLIENT_REPORTS_S.NEXTVAL NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	REPORT_NAME VARCHAR2(200) NOT NULL ENABLE,
	STATUS VARCHAR2(20) DEFAULT 'A',
	COUNTRY VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	REPORT_KEY VARCHAR2(50),
	REPORT_OUTPUT_TYPE VARCHAR2(50),
	ENTITY_TYPE VARCHAR2(50),
	BRAND_ID NUMBER,
	MAX_ALLOWED NUMBER,
	IS_BATCH VARCHAR2(10),
	BU_ID NUMBER,
	REPORT_LOCATION VARCHAR2(50),
	SEQUENCE_NUM NUMBER,
	REPORT_TYPE VARCHAR2(50),
	REPORT_SQL VARCHAR2(4000),
	REPORT_TEMPLATE_NAME VARCHAR2(200),
	ENT_ROLES_ALLOWED VARCHAR2(500)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_REPORTS_PK ON TMCS_CLIENT_REPORTS (REPORT_ID)
  ;
ALTER TABLE TMCS_CLIENT_REPORTS ADD CONSTRAINT TMCS_CLIENT_REPORTS_PK PRIMARY KEY (REPORT_ID)
  USING INDEX TMCS_CLIENT_REPORTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_REPORTS_PK ON TMCS_CLIENT_REPORTS (REPORT_ID)
  ;

