CREATE TABLE TMCS_ENTITY_STATUSES
   (	STATUS_ID NUMBER DEFAULT TMCS_ENTITY_STATUSES_S.NEXTVAL NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(50) NOT NULL ENABLE,
	STATUS_CODE VARCHAR2(50) NOT NULL ENABLE,
	STATUS VARCHAR2(50) NOT NULL ENABLE,
	STATUS_TYPE VARCHAR2(50),
	DEFAULT_STATUS VARCHAR2(5),
	DISPLAY_SEQ NUMBER,
	ENABLED_FLAG VARCHAR2(5),
	START_DATE_ACTIVE TIMESTAMP (6),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	LANGUAGE_CODE VARCHAR2(50),
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	READ_ONLY VARCHAR2(10) DEFAULT 'N',
	DISPLAY_FLAG VARCHAR2(10) DEFAULT 'Y',
	BU_ID NUMBER,
	DIVISION_ID NUMBER,
	C_EXT_ATTR1 VARCHAR2(500)
   ) ;
  CREATE UNIQUE INDEX TMCS_ENTITY_STATUSES_PK ON TMCS_ENTITY_STATUSES (STATUS_ID)
  ;
ALTER TABLE TMCS_ENTITY_STATUSES ADD CONSTRAINT TMCS_ENTITY_STATUSES_PK PRIMARY KEY (STATUS_ID)
  USING INDEX TMCS_ENTITY_STATUSES_PK  ENABLE;
CREATE INDEX TMCS_ENTITY_STATUSES_INDX ON TMCS_ENTITY_STATUSES (STATUS_CODE, CLIENT_ID)
  ;
CREATE INDEX TMCS_ENTITY_STATUSES_INDX02 ON TMCS_ENTITY_STATUSES (CLIENT_ID, COUNTRY, ENTITY_TYPE)
  ;
CREATE UNIQUE INDEX TMCS_ENTITY_STATUSES_PK ON TMCS_ENTITY_STATUSES (STATUS_ID)
  ;
CREATE INDEX TMCS_ENTITY_STATUSES_INDX1 ON TMCS_ENTITY_STATUSES (CLIENT_ID, ENTITY_TYPE, STATUS_CODE)
  ;

