CREATE TABLE TMCS_MILESTONE_TEMP_CHECKLIST
   (	CHECKLIST_ID NUMBER,
	TEMP_DETAIL_ID NUMBER,
	CHECKLIST_NAME VARCHAR2(500),
	CHECKLIST_VALUE VARCHAR2(4000),
	CHECKLIST_OPTION VARCHAR2(10),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	VERSION NUMBER,
	SEQ_NUMBER NUMBER,
	 PRIMARY KEY (CHECKLIST_ID)
  USING INDEX  ENABLE
   ) ;

