CREATE TABLE TMCS_STORE_50PCT_TA
   (	STORE_ID NUMBER(10,0),
	STORE_NUMBER VARCHAR2(31),
	SUM_SALESCAPTURE NUMBER(17,6),
	AREASQMI NUMBER(17,6),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_STORE_50PCT_TA_PK ON TMCS_STORE_50PCT_TA (STORE_ID, STORE_NUMBER)
  ;
ALTER TABLE TMCS_STORE_50PCT_TA ADD CONSTRAINT TMCS_STORE_50PCT_TA_PK PRIMARY KEY (STORE_ID, STORE_NUMBER)
  USING INDEX TMCS_STORE_50PCT_TA_PK  ENABLE;
CREATE INDEX TMCS_STORE_50PCT_TA_GIDX ON TMCS_STORE_50PCT_TA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_STORE_50PCT_TA_PK ON TMCS_STORE_50PCT_TA (STORE_ID, STORE_NUMBER)
  ;

