CREATE TABLE TMCS_MAP_QB_QUERIES_DTL
   (	QUERY_ID NUMBER,
	QUERY_NAME VARCHAR2(320),
	QUERY_DESC VARCHAR2(1000),
	QUERY_TYPE VARCHAR2(320),
	ENTITY_TYPE VARCHAR2(320),
	QUERY_CLAUSES CLOB,
	QUERY_SELECT CLOB,
	QUERY_WHERE CLOB,
	QUERY_STYLE CLOB,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	GEOM_TYPE VARCHAR2(320)
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_QB_QUERIES_PK ON TMCS_MAP_QB_QUERIES_DTL (QUERY_ID)
  ;
ALTER TABLE TMCS_MAP_QB_QUERIES_DTL ADD CONSTRAINT TMCS_MAP_QB_QUERIES_DTL_PK PRIMARY KEY (QUERY_ID)
  USING INDEX TMCS_MAP_QB_QUERIES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_QB_QUERIES_PK ON TMCS_MAP_QB_QUERIES_DTL (QUERY_ID)
  ;

