CREATE TABLE TMCS_SQ_ENTITY_HEADER
   (	SQ_ENTITY_HEADER_ID NUMBER NOT NULL ENABLE,
	SQ_HEADER_ID NUMBER NOT NULL ENABLE,
	SQ_VERSION NUMBER NOT NULL ENABLE,
	SQ_STATUS VARCHAR2(1),
	ENTITY_ID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(32),
	APPROVAL_ROLE VARCHAR2(100),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_SQ_ENTITY_HEADER_PK ON TMCS_SQ_ENTITY_HEADER (SQ_ENTITY_HEADER_ID)
  ;
ALTER TABLE TMCS_SQ_ENTITY_HEADER ADD CONSTRAINT TMCS_SQ_ENTITY_HEADER_PK PRIMARY KEY (SQ_ENTITY_HEADER_ID)
  USING INDEX TMCS_SQ_ENTITY_HEADER_PK  ENABLE;
CREATE INDEX TMCS_SQ_ENTITY_HEADER_IDX01 ON TMCS_SQ_ENTITY_HEADER (ENTITY_TYPE, ENTITY_ID, CLIENT_ID)
  ;
CREATE UNIQUE INDEX TMCS_SQ_ENTITY_HEADER_PK ON TMCS_SQ_ENTITY_HEADER (SQ_ENTITY_HEADER_ID)
  ;

