CREATE TABLE TMCS_ADOBE_SIGN_EVENTS
   (	SIGN_EVENT_ID NUMBER DEFAULT TMCS_ADOBE_SIGN_EVENTS_S.NEXTVAL,
	REQUEST_ID NUMBER NOT NULL ENABLE,
	AGREEMENT_ID VARCHAR2(100) NOT NULL ENABLE,
	EVENT_TYPE VARCHAR2(50) NOT NULL ENABLE,
	EVENT_DATE DATE NOT NULL ENABLE,
	ACTING_USERNAME VARCHAR2(100),
	ACTING_USER_EMAIL VARCHAR2(100),
	ACTING_USER_IP VARCHAR2(50),
	PARTICIPANT_EMAIL VARCHAR2(100),
	PARTICIPANT_ROLE VARCHAR2(100),
	EVENT_DESCRIPTION VARCHAR2(4000),
	EVENT_COMMENT VARCHAR2(4000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	 CONSTRAINT TMCS_ADOBE_SIGN_EVENTS_PK PRIMARY KEY (SIGN_EVENT_ID)
  USING INDEX  ENABLE
   ) ;

