CREATE TABLE TMCS_MODEL_CALC_TEMPLATES
   (	TEMPLATE_ID NUMBER,
	MODEL_ID NUMBER,
	MODEL_CALC_ID NUMBER,
	MODEL_CALC_DESC VARCHAR2(500),
	CALC_MAPPING VARCHAR2(4000),
	DEMOGRAPHIC_YN VARCHAR2(1),
	CALC_COEFFICIENT NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CALC_NAME VARCHAR2(3000),
	PARENT_NAME VARCHAR2(3000),
	DISPLAY_SEQUENCE NUMBER,
	CHART_LABEL VARCHAR2(2000)
   ) ;
  CREATE UNIQUE INDEX TMCS_MODEL_CALC_TEMPLATES_PK ON TMCS_MODEL_CALC_TEMPLATES (TEMPLATE_ID, MODEL_ID, MODEL_CALC_ID)
  ;
ALTER TABLE TMCS_MODEL_CALC_TEMPLATES ADD CONSTRAINT TMCS_MODEL_CALC_TEMPLATES_PK PRIMARY KEY (TEMPLATE_ID, MODEL_ID, MODEL_CALC_ID)
  USING INDEX TMCS_MODEL_CALC_TEMPLATES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MODEL_CALC_TEMPLATES_PK ON TMCS_MODEL_CALC_TEMPLATES (TEMPLATE_ID, MODEL_ID, MODEL_CALC_ID)
  ;

