CREATE TABLE TMCS_ENTITY_ROLES
   (	ROLE_ID NUMBER DEFAULT TMCS_ENTITY_ROLES_S.NEXTVAL,
	ENTITY_TYPE VARCHAR2(100),
	ROLE_CODE VARCHAR2(100),
	ROLE_DESC VARCHAR2(100),
	DISPLAY_SEQ NUMBER,
	ENABLED_FLAG VARCHAR2(5),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_ENTITY_ROLES_PK ON TMCS_ENTITY_ROLES (ROLE_ID)
  ;
ALTER TABLE TMCS_ENTITY_ROLES ADD CONSTRAINT TMCS_ENTITY_ROLES_PK PRIMARY KEY (ROLE_ID)
  USING INDEX TMCS_ENTITY_ROLES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ENTITY_ROLES_PK ON TMCS_ENTITY_ROLES (ROLE_ID)
  ;

