CREATE TABLE TMCS_LOOKUP_EXT_VALUES
   (	LOOKUP_VALUE_ID NUMBER(*,0) DEFAULT TMCS_LOOKUP_EXT_VALUES_S.nextval NOT NULL ENABLE,
	LOOKUP_ID NUMBER(*,0) NOT NULL ENABLE,
	LOOKUP_CODE VARCHAR2(300) NOT NULL ENABLE,
	SEQUENCE NUMBER,
	LANGUAGE_CODE VARCHAR2(300) NOT NULL ENABLE,
	NAME VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(240),
	ENABLED_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	START_DATE_ACTIVE DATE DEFAULT sysdate NOT NULL ENABLE,
	EXTATTRIBUTE_CATEGORY VARCHAR2(30),
	EXTATTRIBUTE1 VARCHAR2(4000),
	EXTATTRIBUTE2 VARCHAR2(4000),
	EXTATTRIBUTE3 VARCHAR2(4000),
	EXTATTRIBUTE4 VARCHAR2(4000),
	EXTATTRIBUTE5 VARCHAR2(4000),
	EXTATTRIBUTE6 VARCHAR2(4000),
	EXTATTRIBUTE7 VARCHAR2(4000),
	EXTATTRIBUTE8 VARCHAR2(4000),
	EXTATTRIBUTE9 VARCHAR2(4000),
	EXTATTRIBUTE10 VARCHAR2(4000),
	TAG VARCHAR2(150),
	END_DATE_ACTIVE DATE,
	REPORT_SEQUENCE NUMBER,
	CLIENT_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	BRAND_ID NUMBER
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX TMCS_LOOKUP_EXT_VALUES_PK ON TMCS_LOOKUP_EXT_VALUES (LOOKUP_VALUE_ID)
  ;
ALTER TABLE TMCS_LOOKUP_EXT_VALUES ADD CONSTRAINT TMCS_LOOKUP_EXT_VALUES_PK PRIMARY KEY (LOOKUP_VALUE_ID)
  USING INDEX TMCS_LOOKUP_EXT_VALUES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_LOOKUP_EXT_VALUES_PK ON TMCS_LOOKUP_EXT_VALUES (LOOKUP_VALUE_ID)
  ;
CREATE INDEX TMCS_LOOKUP_EXT_VALUES_INDX01 ON TMCS_LOOKUP_EXT_VALUES (LOOKUP_ID)
  ;
CREATE UNIQUE INDEX TMCS_LOOKUP_EXT_VALUES_INDX03 ON TMCS_LOOKUP_EXT_VALUES (LOOKUP_ID, LOOKUP_CODE, LANGUAGE_CODE)
  ;

