CREATE TABLE TMCS_CLIENT_SUPP_PREFS
   (	SUPP_PREF_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	GEO_REGION_ID NUMBER,
	GEO_MARKET_ID NUMBER,
	TRADES VARCHAR2(50),
	PREFERENCE1 NUMBER,
	PREFERENCE2 NUMBER,
	PREFERENCE3 NUMBER,
	ORG_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	INTERNAL_MAINT VARCHAR2(10)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_SUPP_PREFS_PK ON TMCS_CLIENT_SUPP_PREFS (SUPP_PREF_ID)
  ;
ALTER TABLE TMCS_CLIENT_SUPP_PREFS ADD PRIMARY KEY (SUPP_PREF_ID)
  USING INDEX TMCS_CLIENT_SUPP_PREFS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_SUPP_PREFS_PK ON TMCS_CLIENT_SUPP_PREFS (SUPP_PREF_ID)
  ;
CREATE INDEX TMCS_CLIENT_SUPP_PREFS_INDX ON TMCS_CLIENT_SUPP_PREFS (CLIENT_ID)
  ;

