CREATE TABLE TMCS_CONTACTS_USERS
   (	CONTACT_USER_ID NUMBER NOT NULL ENABLE,
	ROLE VARCHAR2(50),
	NAME VARCHAR2(100),
	BUSINESS_PHONE VARCHAR2(50),
	EXTENSION VARCHAR2(50),
	CELLPHONE VARCHAR2(50),
	EMAIL VARCHAR2(50),
	FAX VARCHAR2(50),
	COMMENTS VARCHAR2(2000),
	COMPANY VARCHAR2(150),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_CONTACTS_USERS_PK ON TMCS_CONTACTS_USERS (CONTACT_USER_ID)
  ;
ALTER TABLE TMCS_CONTACTS_USERS ADD CONSTRAINT TMCS_CONTACTS_USERS_PK PRIMARY KEY (CONTACT_USER_ID)
  USING INDEX TMCS_CONTACTS_USERS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CONTACTS_USERS_PK ON TMCS_CONTACTS_USERS (CONTACT_USER_ID)
  ;

