CREATE TABLE TMCS_ENTITY_INTF_MAP_COLUMNS
   (	INTF_MAP_COLUMNS_ID NUMBER,
	INTF_MAP_HEADER_ID NUMBER,
	COL_LABEL VARCHAR2(500),
	COL_ALIAS VARCHAR2(500),
	COL_ID NUMBER,
	REF_TYPE VARCHAR2(20),
	STATUS CHAR(1) DEFAULT 'Y',
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	LABEL_VALUE VARCHAR2(500),
	DISPLAY VARCHAR2(100),
	COMPONENT_KEY VARCHAR2(4000),
	RESOURCE_ID NUMBER,
	 CONSTRAINT INTF_MAP_COLUMNS_PK PRIMARY KEY (INTF_MAP_COLUMNS_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT INTF_MAP_HEADER_FK FOREIGN KEY (INTF_MAP_HEADER_ID)
	  REFERENCES TMCS_ENTITY_INTF_MAP_HEADER (INTF_MAP_HEADER_ID) ENABLE
   ) ;
CREATE INDEX TMCS_ENTITY_INTF_MAP_COLUMNS_INDX02 ON TMCS_ENTITY_INTF_MAP_COLUMNS (INTF_MAP_HEADER_ID)
  ;
CREATE INDEX TMCS_ENTITY_INTF_MAP_COLUMNS_INDX01 ON TMCS_ENTITY_INTF_MAP_COLUMNS (COL_ID, COUNTRY, COL_LABEL)
  ;

