CREATE TABLE TMCS_SQ_ENTITY_ANSWERS
   (	ENTITY_ANSWER_ID NUMBER,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(32),
	ENTITY_QID NUMBER,
	ANSWER_ID NUMBER,
	ANSWER_LABEL VARCHAR2(500),
	ANSWER_VALUE VARCHAR2(4000),
	DEFAULT_SELECTED VARCHAR2(50) DEFAULT 'FALSE',
	ANSWER_DESC VARCHAR2(256),
	SELECTED VARCHAR2(32) DEFAULT 'FALSE',
	USER_ANSWER VARCHAR2(4000),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	Q_TYPE VARCHAR2(1),
	MIN_VALUE NUMBER,
	MAX_VALUE NUMBER,
	MODEL_SHORT_CODE VARCHAR2(30),
	SQ_HEADER_ID NUMBER,
	SQ_VERSION NUMBER,
	SQ_ENTITY_HEADER_ID NUMBER,
	STAGING_ID VARCHAR2(20),
	 CONSTRAINT TMCS_SQ_ENTITY_ANSWERS_PK PRIMARY KEY (ENTITY_ANSWER_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_SQ_ENTITY_ANSWERS_IDX02 ON TMCS_SQ_ENTITY_ANSWERS (ENTITY_QID)
  ;
CREATE INDEX TMCS_SQ_ENTITY_ANSWERS_IDX01 ON TMCS_SQ_ENTITY_ANSWERS (ENTITY_ID, ENTITY_TYPE, ENTITY_QID)
  ;

