CREATE TABLE TMCS_MODEL_TEMPLATES
   (	TEMPLATE_ID NUMBER,
	TEMPLATE_TYPE VARCHAR2(50),
	MODEL_ID NUMBER,
	MODEL_NAME VARCHAR2(50),
	MODEL_COMMENTS VARCHAR2(500),
	CLIENT_ID NUMBER,
	CLIENT_COUNTRY VARCHAR2(50),
	CLIENT_BRAND_ID NUMBER,
	RECORD_YN VARCHAR2(1),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	MODEL_ATTRIBUTE_1 NUMBER,
	MODEL_ATTRIBUTE_2 NUMBER,
	TABLE_NAME VARCHAR2(320)
   ) ;
  CREATE UNIQUE INDEX TMCS_MODEL_TEMPLATES_PK ON TMCS_MODEL_TEMPLATES (TEMPLATE_ID, MODEL_ID)
  ;
ALTER TABLE TMCS_MODEL_TEMPLATES ADD CONSTRAINT TMCS_MODEL_TEMPLATES_PK PRIMARY KEY (TEMPLATE_ID, MODEL_ID)
  USING INDEX TMCS_MODEL_TEMPLATES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MODEL_TEMPLATES_PK ON TMCS_MODEL_TEMPLATES (TEMPLATE_ID, MODEL_ID)
  ;

