CREATE TABLE TMCS_USER_TERMS
   (	USER_TERMS_ID NUMBER DEFAULT TMCS_USER_TERMS_S.NEXTVAL,
	USER_NAME VARCHAR2(200) NOT NULL ENABLE,
	VERSION NUMBER NOT NULL ENABLE,
	ACCEPTED_STATUS VARCHAR2(10) NOT NULL ENABLE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	 CONSTRAINT TMCS_USER_TERMS_PK PRIMARY KEY (USER_TERMS_ID)
  USING INDEX  ENABLE
   ) ;

