CREATE TABLE TMCS_SQ_GROUP
   (	GROUP_ID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(32),
	GROUP_NAME VARCHAR2(70),
	PARENT_GROUPID NUMBER,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BU_ID NUMBER,
	HAS_CONDITION VARCHAR2(1),
	SQ_HEADER_ID NUMBER,
	SQ_VERSION NUMBER,
	 CONSTRAINT QUESTION_GROUP_PK PRIMARY KEY (GROUP_ID)
  USING INDEX (CREATE UNIQUE INDEX TMCS_SQ_GROUP_PK ON TMCS_SQ_GROUP (GROUP_ID)
  )  ENABLE
   ) ;

