CREATE TABLE TMCS_SOBYS_LEASE_LABELS
   (	LOOKUP_ID NUMBER(*,0) NOT NULL ENABLE,
	LOOKUP_VALUE_ID NUMBER(*,0) NOT NULL ENABLE,
	LANGUAGE_CODE VARCHAR2(300) NOT NULL ENABLE,
	NAME VARCHAR2(300) NOT NULL ENABLE,
	LOOKUP_CODE VARCHAR2(300) NOT NULL ENABLE,
	FRENCH_LABEL VARCHAR2(1200),
	ENGLISH_LABEL VARCHAR2(300)
   ) ;

