CREATE TABLE TMCS_INTF_ENTITY_VALID_RULES
   (	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(50),
	ATTR_NAME VARCHAR2(100),
	LOOKUP_NAME VARCHAR2(200),
	IS_MANDATORY VARCHAR2(1),
	MIN_VALUE NUMBER,
	MAX_VALUE NUMBER,
	VALIDATE_GROUP NUMBER,
	IS_UNIQUE VARCHAR2(1)
   ) ;

