CREATE TABLE TMCS_PO_DETAIL
   (	PO_ITEM_ID NUMBER,
	PO_ID NUMBER,
	ITEM_SEQ_NO NUMBER,
	TASK_ID NUMBER,
	CURRENCY VARCHAR2(50),
	RATE NUMBER,
	QTY NUMBER,
	UOM VARCHAR2(50),
	AMOUNT NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	INV_ISSUE_AMOUNT NUMBER,
	BRAND_ID NUMBER,
	RECEIVED_QUANTITY NUMBER,
	COMMENTS VARCHAR2(4000),
	DELIVERY_DATE DATE,
	AMOUNT_LOCAL NUMBER,
	AMOUNT_BU NUMBER,
	AMOUNT_USD NUMBER,
	INV_ISSUE_AMOUNT_LOCAL NUMBER,
	INV_ISSUE_AMOUNT_BU NUMBER,
	INV_ISSUE_AMOUNT_USD NUMBER,
	RECEIVED_QUANTITY_LOCAL NUMBER,
	RECEIVED_QUANTITY_BU NUMBER,
	RECEIVED_QUANTITY_USD NUMBER,
	RETAINAGE_PCT NUMBER,
	STATUS VARCHAR2(50),
	UNAPPROVED_INV_AMT NUMBER,
	INV_ISSUE_RET_AMOUNT NUMBER,
	UNAPPROVED_INV_RET_AMT NUMBER,
	TAX_GROUP VARCHAR2(100),
	TAX_RATE NUMBER,
	VENDOR_TAX_AMOUNT NUMBER,
	ACCRUED_TAX_AMOUNT NUMBER,
	SEQUENCE NUMBER,
	VENDOR_COLLECT_TAX VARCHAR2(10),
	MATERIAL_USUAGE VARCHAR2(500),
	MATERIAL_ORGIN VARCHAR2(500),
	MATERIAL_CATEGORY VARCHAR2(500),
	STAGING_ID NUMBER,
	 CONSTRAINT FK_PO_DETAIL FOREIGN KEY (PO_ID)
	  REFERENCES TMCS_PO_HEADER (PO_ID) ENABLE
   ) ;
  CREATE UNIQUE INDEX TMCS_PO_DETAIL_PK ON TMCS_PO_DETAIL (PO_ITEM_ID)
  ;
ALTER TABLE TMCS_PO_DETAIL ADD CONSTRAINT TMCS_PO_DETAIL_PK PRIMARY KEY (PO_ITEM_ID)
  USING INDEX TMCS_PO_DETAIL_PK  ENABLE;
CREATE INDEX TMCS_PO_DETAIL_INDX03 ON TMCS_PO_DETAIL (CLIENT_ID, PO_ID)
  ;
CREATE INDEX TMCS_PO_DETAIL_INDX02 ON TMCS_PO_DETAIL (PO_ID)
  ;
CREATE UNIQUE INDEX TMCS_PO_DETAIL_PK ON TMCS_PO_DETAIL (PO_ITEM_ID)
  ;
CREATE INDEX TMCS_PO_DETAIL_INDX01 ON TMCS_PO_DETAIL (PO_ID, CLIENT_ID)
  ;

