CREATE TABLE TMCS_OPTIM_CANNIB_CURVES
   (	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	PARAM_VALUE VARCHAR2(320),
	CBSA_CLASS NUMBER,
	STORE_CLASS NUMBER,
	B0 NUMBER,
	B1 NUMBER,
	B2 NUMBER,
	B3 NUMBER,
	B4 NUMBER,
	B5 NUMBER,
	B6 NUMBER,
	MAX_RADIUS NUMBER
   ) ;

