CREATE TABLE TMCS_ANALOG_HEADERS
   (	ANALOG_ID NUMBER,
	ANALOG_NAME VARCHAR2(256),
	SITE_ID NUMBER,
	TA_TYPE NUMBER,
	DESCRIPTION VARCHAR2(4000),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	MARGIN_PCT NUMBER,
	STATUS VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX TMCS_ANALOG_HEADERS_PK ON TMCS_ANALOG_HEADERS (ANALOG_ID)
  ;
ALTER TABLE TMCS_ANALOG_HEADERS ADD CONSTRAINT TMCS_ANALOG_HEADERS_PK PRIMARY KEY (ANALOG_ID)
  USING INDEX TMCS_ANALOG_HEADERS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ANALOG_HEADERS_PK ON TMCS_ANALOG_HEADERS (ANALOG_ID)
  ;

