CREATE TABLE TMCS_SEC_ENTITY_GROUP_ASSN
   (	GROUP_ID NUMBER,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SEC_ENTITY_GROUP_ASSN_PK ON TMCS_SEC_ENTITY_GROUP_ASSN (GROUP_ID, ENTITY_ID, ENTITY_TYPE)
  ;
ALTER TABLE TMCS_SEC_ENTITY_GROUP_ASSN ADD CONSTRAINT TMCS_SEC_ENTITY_GROUP_ASSN_PK PRIMARY KEY (GROUP_ID, ENTITY_ID, ENTITY_TYPE)
  USING INDEX TMCS_SEC_ENTITY_GROUP_ASSN_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SEC_ENTITY_GROUP_ASSN_PK ON TMCS_SEC_ENTITY_GROUP_ASSN (GROUP_ID, ENTITY_ID, ENTITY_TYPE)
  ;

