CREATE TABLE TMCS_SITE_SF_SNR_TARGETS
   (	SFS_ID NUMBER,
	SF_ID NUMBER,
	TARGET_ID NUMBER,
	TARGET_NUMBER VARCHAR2(100),
	TARGET_NAME VARCHAR2(100),
	ADDRESS VARCHAR2(500),
	CITY VARCHAR2(100),
	STATE VARCHAR2(100),
	ZIP VARCHAR2(100),
	SALES NUMBER,
	EBITA NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	SELECT_FLAG VARCHAR2(1),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	SITE_ID NUMBER,
	PRIMARY_SITE_STATUS VARCHAR2(500),
	PRIMARY_SITE_NUMBER VARCHAR2(500),
	SL_DIST NUMBER,
	DR_DIST NUMBER,
	DR_TIME NUMBER,
	SEC_ATTR1 VARCHAR2(50),
	SEC_ATTR2 VARCHAR2(50)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_SITE_SF_SNR_TARGETS_GIDX ON TMCS_SITE_SF_SNR_TARGETS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

