CREATE TABLE TMCS_SDA_AGMT_INCENTIVES
   (	INCENTIVE_ID NUMBER DEFAULT TMCS_SDA_AGMT_INCENTIVES_S.NEXTVAL,
	TIER_ID NUMBER,
	AGREEMENT_ID NUMBER,
	SDA_ID NUMBER,
	TIER_NUMBER NUMBER,
	INCENTIVE_TYPE VARCHAR2(20),
	AMT_WAIVED NUMBER,
	COUNT_WAIVED NUMBER,
	PERCENT_WAIVED NUMBER,
	YEARS_WAIVED NUMBER,
	BASE_SUR_AMT_WAIVED NUMBER,
	TOTAL_AMT_WAIVED NUMBER,
	REPAY_TERMS VARCHAR2(20),
	COMMENTS VARCHAR2(4000),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	 CONSTRAINT TMCS_SDA_AGMT_INCENTIVE_PK PRIMARY KEY (INCENTIVE_ID)
  USING INDEX  ENABLE
   ) ;

