CREATE TABLE TMCS_SEED_TRADEAREAS_A
   (	SEED_ID CHAR(12),
	SEED_NAME VARCHAR2(65),
	CLIENT_ID NUMBER(19,0),
	BRAND_ID NUMBER(19,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	COUNTRY VARCHAR2(64),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

