CREATE TABLE TMCS_DEPLOYMENT_CHECKLIST
   (	DEPLOYMENT_ID NUMBER DEFAULT TMCS_DEPLOYMENT_CHECKLIST_S.NEXTVAL,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	LABELS VARCHAR2(20),
	DYNAMIC_ATTRS VARCHAR2(20),
	LOVS VARCHAR2(20),
	ENTITY_STATUS VARCHAR2(20),
	ENTERPRISE_ROLES VARCHAR2(20),
	RES_BOUNDARIES VARCHAR2(20),
	RES_CONTACTS VARCHAR2(20),
	MILESTONES VARCHAR2(20),
	ANALOG VARCHAR2(20),
	DEMOGRAPHICS VARCHAR2(20),
	BUDGETS VARCHAR2(20),
	FOLDERS VARCHAR2(20),
	APPROVAL_DOCS VARCHAR2(20),
	WORKFLOW VARCHAR2(20),
	EMAIL_TEMPLATES VARCHAR2(20),
	INFO_WINDOWS VARCHAR2(20),
	MAP_MENU VARCHAR2(20),
	MAP_ICONS VARCHAR2(20),
	MAP_FORMS VARCHAR2(20),
	MAP_CONFIG VARCHAR2(20),
	REPORT_TEMPLATES VARCHAR2(20),
	GEO_ATTRIBS VARCHAR2(20),
	DEMO_CALCULATION VARCHAR2(20),
	QUESTIONNAIRE VARCHAR2(20),
	TA_INTEGRATOR VARCHAR2(20),
	DEPLOYMENT_DATE DATE,
	DEPLOYMENT_DAY VARCHAR2(100),
	COMPETITORS_CONF VARCHAR2(20),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	APPLY_BU_POLICY VARCHAR2(10),
	DEPLOYMENT_ENV VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_DEPLOYMENT_CHECKLIST_PK ON TMCS_DEPLOYMENT_CHECKLIST (DEPLOYMENT_ID)
  ;
ALTER TABLE TMCS_DEPLOYMENT_CHECKLIST ADD CONSTRAINT TMCS_DEPLOYMENT_CHECKLIST_PK PRIMARY KEY (DEPLOYMENT_ID)
  USING INDEX TMCS_DEPLOYMENT_CHECKLIST_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_DEPLOYMENT_CHECKLIST_PK ON TMCS_DEPLOYMENT_CHECKLIST (DEPLOYMENT_ID)
  ;

