CREATE TABLE TMCS_CLIENT_ADDL_SECURITY
   (	CLIENT_ADDL_SEC_ID NUMBER DEFAULT TMCS_CLIENT_ADDL_SECURITY_S.NEXTVAL,
	CLIENT_ID NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(100),
	COLUMN_NAME VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	LOOKUP_CODE VARCHAR2(200)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_ADDL_SECURITY_PK ON TMCS_CLIENT_ADDL_SECURITY (CLIENT_ADDL_SEC_ID)
  ;
ALTER TABLE TMCS_CLIENT_ADDL_SECURITY ADD CONSTRAINT TMCS_CLIENT_ADDL_SECURITY_PK PRIMARY KEY (CLIENT_ADDL_SEC_ID)
  USING INDEX TMCS_CLIENT_ADDL_SECURITY_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_ADDL_SECURITY_PK ON TMCS_CLIENT_ADDL_SECURITY (CLIENT_ADDL_SEC_ID)
  ;

