CREATE TABLE TMCS_MSFT_API
   (	ENTITY_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CLOB_DATA CLOB,
	INVOICE_STATUS VARCHAR2(100),
	INVOICE_ID NUMBER,
	BEARER_TOKEN VARCHAR2(4000),
	IDENTIFIER VARCHAR2(4000),
	LAST_UPDATE_DATE DATE,
	SUPPLIER_NAME VARCHAR2(500),
	PO_NUMBER VARCHAR2(100),
	PROCESSED_FLAG VARCHAR2(10),
	CXML CLOB
   ) ;

