CREATE TABLE TMCS_ADF_FUNCTIONS
   (	FUNCTION_ID NUMBER(*,0),
	FUNCTION_NAME VARCHAR2(50),
	FUNCTION_TYPE VARCHAR2(50),
	DISPLAY_ORDER NUMBER,
	ENABLED NUMBER(*,0),
	READ_ONLY VARCHAR2(1),
	URL VARCHAR2(1000),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_ADF_FUNCTIONS_PK ON TMCS_ADF_FUNCTIONS (FUNCTION_ID)
  ;
ALTER TABLE TMCS_ADF_FUNCTIONS ADD CONSTRAINT TMCS_ADF_FUNCTIONS_PK PRIMARY KEY (FUNCTION_ID)
  USING INDEX TMCS_ADF_FUNCTIONS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ADF_FUNCTIONS_PK ON TMCS_ADF_FUNCTIONS (FUNCTION_ID)
  ;

