CREATE TABLE TMCS_CLIENT_BUSINESS_UNITS
   (	BU_ID NUMBER,
	CLIENT_ID NUMBER(*,0),
	BU_NAME VARCHAR2(50),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BRAND_ID NUMBER,
	BU_CODE VARCHAR2(20),
	DEF_APP_RES_LANG_CODE VARCHAR2(20),
	AUTOGEN_STORE_NUMBER VARCHAR2(10),
	BU_CURRENCY VARCHAR2(10),
	COST_HEALTH_THRESHOLD NUMBER DEFAULT 0.9,
	DIVISION_ID NUMBER,
	AUTOGEN_LEASE_NUMBER VARCHAR2(10),
	INVOICE_TOLERANCE NUMBER,
	INVOICE_CONTROL VARCHAR2(10),
	ALLOW_BUDGET_VERSION_SELECTION VARCHAR2(10),
	ALLOW_PO_CO_FOR_CHILD_PROJ VARCHAR2(100),
	WF_CUMM_CO_VALIDATION VARCHAR2(10) DEFAULT 'N'
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_BUSINESS_UNITS_PK ON TMCS_CLIENT_BUSINESS_UNITS (BU_ID)
  ;
ALTER TABLE TMCS_CLIENT_BUSINESS_UNITS ADD CONSTRAINT TMCS_CLIENT_BUSINESS_UNITS_PK PRIMARY KEY (BU_ID)
  USING INDEX TMCS_CLIENT_BUSINESS_UNITS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_BUSINESS_UNITS_PK ON TMCS_CLIENT_BUSINESS_UNITS (BU_ID)
  ;

