CREATE TABLE TMCS_PROTOTYPES
   (	PROTOTYPE_ID NUMBER,
	PROTOTYPE_NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(1000),
	MAJOR_REVISION VARCHAR2(10),
	MINOR_REVISION VARCHAR2(10),
	STATUS VARCHAR2(20),
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	C_EXT_ATTR4 VARCHAR2(500),
	C_EXT_ATTR5 VARCHAR2(500),
	C_EXT_ATTR6 VARCHAR2(500),
	C_EXT_ATTR7 VARCHAR2(500),
	C_EXT_ATTR8 VARCHAR2(500),
	C_EXT_ATTR9 VARCHAR2(500),
	C_EXT_ATTR10 VARCHAR2(500),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	D_EXT_ATTR1 DATE,
	D_EXT_ATTR2 DATE,
	D_EXT_ATTR3 DATE,
	D_EXT_ATTR4 DATE,
	D_EXT_ATTR5 DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	COUNTRY VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROTOTYPES_PK ON TMCS_PROTOTYPES (PROTOTYPE_ID)
  ;
ALTER TABLE TMCS_PROTOTYPES ADD PRIMARY KEY (PROTOTYPE_ID)
  USING INDEX TMCS_PROTOTYPES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROTOTYPES_PK ON TMCS_PROTOTYPES (PROTOTYPE_ID)
  ;

