CREATE TABLE TMCS_SITE_EMAILS
   (	EMAIL_ID NUMBER NOT NULL ENABLE,
	SITE_ID NUMBER NOT NULL ENABLE,
	EMAIL_FROM VARCHAR2(500),
	EMAIL_TO VARCHAR2(500),
	SUBJECT VARCHAR2(2000),
	EMAIL_BODY VARCHAR2(2000),
	VERSION_ID NUMBER DEFAULT 1,
	LOCK_STATUS VARCHAR2(1) DEFAULT 'N',
	DESCRIPTION VARCHAR2(150),
	CURRENT_VERSION VARCHAR2(1),
	LOCKED_BY VARCHAR2(100),
	READ_ONLY VARCHAR2(1),
	DELETED VARCHAR2(1),
	SENT VARCHAR2(10),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	PRIVATE_FLAG VARCHAR2(1) DEFAULT 'N',
	TAG VARCHAR2(2000),
	AWS_VERSION_ID VARCHAR2(100),
	FILE_NAME VARCHAR2(500),
	EMAIL_CC VARCHAR2(500),
	EMAIL_DATE TIMESTAMP (6)
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_EMAILS_PK ON TMCS_SITE_EMAILS (EMAIL_ID)
  ;
ALTER TABLE TMCS_SITE_EMAILS ADD CONSTRAINT TMCS_SITE_EMAILS_PK PRIMARY KEY (EMAIL_ID)
  USING INDEX TMCS_SITE_EMAILS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_EMAILS_PK ON TMCS_SITE_EMAILS (EMAIL_ID)
  ;

