CREATE TABLE TMCS_MILESTONE_RESOURCES
   (	RESOURCE_ID NUMBER,
	MILESTONE_ID NUMBER,
	RESOURCE_NAME VARCHAR2(100),
	RESOURCE_ROLE VARCHAR2(100),
	ESCALATION_NOTIFICATION VARCHAR2(10),
	EMAIL VARCHAR2(100),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	RESOURCE_USER_NAME VARCHAR2(200),
	COMPLETION_NOTIFICATION VARCHAR2(10),
	STAGING_ID NUMBER,
	 PRIMARY KEY (RESOURCE_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_MILESTONE_RESOURCES_INDX1 ON TMCS_MILESTONE_RESOURCES (MILESTONE_ID)
  ;

