CREATE TABLE TMCS_DEMOG_LABEL_MAPPING_BKUP
   (	COLUMN_NAME VARCHAR2(100),
	STORES_COMP_KEY VARCHAR2(200),
	SITES_COMP_KEY VARCHAR2(200),
	TARGETS_COMP_KEY VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;

