CREATE TABLE TMCS_SQ_QUESTION_OPTIONS
   (	QID NUMBER DEFAULT 1 NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(32),
	OBJECT_TYPE VARCHAR2(50),
	DISP_SEQ_NO NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	SQ_HEADER_ID NUMBER,
	SQ_VERSION NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SQ_QUESTION_OPTIONS_PK ON TMCS_SQ_QUESTION_OPTIONS (QID, OBJECT_TYPE)
  ;
ALTER TABLE TMCS_SQ_QUESTION_OPTIONS ADD CONSTRAINT TMCS_SQ_QUESTION_OPTIONS_PK PRIMARY KEY (QID, OBJECT_TYPE)
  USING INDEX TMCS_SQ_QUESTION_OPTIONS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SQ_QUESTION_OPTIONS_PK ON TMCS_SQ_QUESTION_OPTIONS (QID, OBJECT_TYPE)
  ;

