CREATE TABLE TMCS_STATES
   (	NAME VARCHAR2(64),
	KEY VARCHAR2(32),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	STATE_CODE VARCHAR2(320),
	COUNTRY_CODE VARCHAR2(10)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_STATES_PK ON TMCS_STATES (NAME, COUNTRY_CODE)
  ;
ALTER TABLE TMCS_STATES ADD CONSTRAINT TMCS_STATES_PK PRIMARY KEY (NAME, COUNTRY_CODE)
  USING INDEX TMCS_STATES_PK  ENABLE;
CREATE INDEX TMCS_STATES_GIDX ON TMCS_STATES (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_STATES_PK ON TMCS_STATES (NAME, COUNTRY_CODE)
  ;

