CREATE TABLE TMCS_CLIENT_OAUTH_SETUP_H
   (	OAUTH_SETUP_H_ID NUMBER DEFAULT TMCS_CLIENT_OAUTH_SETUP_H_S.NEXTVAL,
	OAUTH_SETUP_ID NUMBER,
	PROFILE VARCHAR2(50),
	TOKEN_URL VARCHAR2(500),
	TOKEN_SEC_TYPE VARCHAR2(50),
	SCOPES VARCHAR2(1000),
	OAUTH_CLIENT_ID VARCHAR2(500),
	CLIENT_SECRET VARCHAR2(500),
	CLAIM_AUD VARCHAR2(500),
	CLAIM_EXPIRY_DAYS NUMBER,
	PRIVATE_KEY VARCHAR2(4000),
	X509_THUMBPRINT VARCHAR2(500),
	CLIENT_ID NUMBER,
	CREATED_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	HISTORY_DATE TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	DML_OPERATION VARCHAR2(10)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_OAUTH_SETUP_H_PK ON TMCS_CLIENT_OAUTH_SETUP_H (OAUTH_SETUP_H_ID)
  ;
ALTER TABLE TMCS_CLIENT_OAUTH_SETUP_H ADD CONSTRAINT TMCS_CLIENT_OAUTH_SETUP_H_PK PRIMARY KEY (OAUTH_SETUP_H_ID)
  USING INDEX TMCS_CLIENT_OAUTH_SETUP_H_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_OAUTH_SETUP_H_PK ON TMCS_CLIENT_OAUTH_SETUP_H (OAUTH_SETUP_H_ID)
  ;

