CREATE TABLE TMCS_CLIENT_MARKET_DEMOGRAPHICS
   (	MARKET_ID VARCHAR2(320),
	MARKET_NAME VARCHAR2(320),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	TEMPLATE_TYPE VARCHAR2(320),
	DEMOG_VAL CLOB,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_MARKET_DEMOGRAPHICS_PK ON TMCS_CLIENT_MARKET_DEMOGRAPHICS (MARKET_ID, CLIENT_ID, BRAND_ID, COUNTRY, TEMPLATE_TYPE)
  ;
ALTER TABLE TMCS_CLIENT_MARKET_DEMOGRAPHICS ADD CONSTRAINT TMCS_CLIENT_MARKET_DEMOGRAPHICS_PK PRIMARY KEY (MARKET_ID, CLIENT_ID, BRAND_ID, COUNTRY, TEMPLATE_TYPE)
  USING INDEX TMCS_CLIENT_MARKET_DEMOGRAPHICS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_MARKET_DEMOGRAPHICS_PK ON TMCS_CLIENT_MARKET_DEMOGRAPHICS (MARKET_ID, CLIENT_ID, BRAND_ID, COUNTRY, TEMPLATE_TYPE)
  ;

