CREATE TABLE TMCS_GIS_CLIENT_COUNTRY_SETUP
   (	CLIENT_ID VARCHAR2(10),
	TMC_FUNCTIONALITY VARCHAR2(100),
	TMC_PACKAGE VARCHAR2(500),
	GET_STATUS VARCHAR2(200),
	DEMOGRAPHICS VARCHAR2(200),
	COUNTRY VARCHAR2(200)
   ) ;
  CREATE UNIQUE INDEX TMCS_GIS_CLIENT_CNTRY_SETUP_PK ON TMCS_GIS_CLIENT_COUNTRY_SETUP (CLIENT_ID, TMC_FUNCTIONALITY, COUNTRY)
  ;
ALTER TABLE TMCS_GIS_CLIENT_COUNTRY_SETUP ADD CONSTRAINT TMCS_GIS_CLIENT_CNTRY_SETUP_PK PRIMARY KEY (CLIENT_ID, TMC_FUNCTIONALITY, COUNTRY)
  USING INDEX TMCS_GIS_CLIENT_CNTRY_SETUP_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_GIS_CLIENT_CNTRY_SETUP_PK ON TMCS_GIS_CLIENT_COUNTRY_SETUP (CLIENT_ID, TMC_FUNCTIONALITY, COUNTRY)
  ;

