CREATE TABLE TMCS_PO_CO_ALLOCATIONS
   (	ALLOCATION_ID NUMBER DEFAULT tmcs.TMCS_PO_CO_ALLOCATIONS_S.nextval,
	PO_ID NUMBER,
	CO_ID NUMBER,
	FISCAL_YEAR NUMBER,
	FISCAL_PERIOD NUMBER,
	ALLOCATED_AMOUNT NUMBER,
	INVOICED_AMOUNT NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	 PRIMARY KEY (ALLOCATION_ID)
  USING INDEX  ENABLE
   ) ;

