CREATE TABLE TMCS_ADF_ERROR_LOG
   (	ADF_LOG_ID NUMBER DEFAULT ON NULL TMCS_ADF_ERROR_LOG_S.NEXTVAL NOT NULL ENABLE,
	PAGE_NAME VARCHAR2(100),
	ACTION_TYPE VARCHAR2(100),
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	MESSAGE VARCHAR2(4000),
	USER_NAME VARCHAR2(200),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(200),
	LANGUAGE_CODE VARCHAR2(100),
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	LOG_DETAILS CLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_ADF_ERROR_LOG_PK ON TMCS_ADF_ERROR_LOG (ADF_LOG_ID)
  ;
ALTER TABLE TMCS_ADF_ERROR_LOG ADD CONSTRAINT TMCS_ADF_ERROR_LOG_PK PRIMARY KEY (ADF_LOG_ID)
  USING INDEX TMCS_ADF_ERROR_LOG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ADF_ERROR_LOG_PK ON TMCS_ADF_ERROR_LOG (ADF_LOG_ID)
  ;
CREATE INDEX TMCS_ADF_ERROR_LOG_INDX ON TMCS_ADF_ERROR_LOG (CLIENT_ID)
  ;

