CREATE TABLE TMCS_MAP_INFO_WINDOW_DETAILS
   (	CLIENT_ID NUMBER,
	COUNTRY_CODE VARCHAR2(50),
	ENTITY_TYPE VARCHAR2(50),
	INFO_ENTITY_TYPE VARCHAR2(50),
	INFO_WINDOW_ID NUMBER,
	BU_ID NUMBER,
	APP_LANGUAGE_CODE VARCHAR2(10),
	WIN_HEIGHT NUMBER DEFAULT 260,
	WIN_WIDTH NUMBER DEFAULT 330,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	DB_SCHEMA VARCHAR2(50),
	BRAND_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_INFO_WIN_DETAILS_UK ON TMCS_MAP_INFO_WINDOW_DETAILS (INFO_WINDOW_ID)
  ;
ALTER TABLE TMCS_MAP_INFO_WINDOW_DETAILS ADD CONSTRAINT TMCS_MAP_INFO_WINDOW_DETAILSPK PRIMARY KEY (INFO_WINDOW_ID)
  USING INDEX TMCS_MAP_INFO_WIN_DETAILS_UK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WINDOW_DETAI_U01 ON TMCS_MAP_INFO_WINDOW_DETAILS (CLIENT_ID, BRAND_ID, BU_ID, ENTITY_TYPE, INFO_ENTITY_TYPE, COUNTRY_CODE)
  ;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WIN_DETAILS_UK ON TMCS_MAP_INFO_WINDOW_DETAILS (INFO_WINDOW_ID)
  ;

