CREATE TABLE TMCS_CLIENT_JOBS
   (	JOB_ID NUMBER DEFAULT TMCS_CLIENT_JOBS_S.NEXTVAL,
	JOB_NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(500),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	NOTIFICATION_EVENTS VARCHAR2(2000),
	NOTIFICATION_EMAILS VARCHAR2(4000),
	 PRIMARY KEY (JOB_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT TMCS_CLIENT_JOBS_UK UNIQUE (CLIENT_ID, JOB_NAME)
  USING INDEX  ENABLE
   ) ;

