CREATE TABLE TMCS_RECEIPT_HEADER
   (	RECEIPT_ID NUMBER,
	RECEIPT_TYPE VARCHAR2(50),
	RECEIPT_NUMBER VARCHAR2(50),
	PO_ID NUMBER,
	PROJECT_ID NUMBER,
	STATUS VARCHAR2(50),
	RECEIPT_DATE DATE,
	SUBMITTED_BY VARCHAR2(100),
	APPROVED_BY VARCHAR2(100),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	RECEIPT_TOTAL_AMOUNT NUMBER,
	RECEIPT_TOTAL_AMOUNT_LOCAL NUMBER,
	RECEIPT_TOTAL_AMOUNT_BU NUMBER,
	RECEIPT_TOTAL_AMOUNT_USD NUMBER,
	 PRIMARY KEY (RECEIPT_ID)
  USING INDEX  ENABLE
   ) ;

