CREATE TABLE TMCS_COMP_EVENT_IMPCT_STORES
   (	IMPACTED_STORE_ID NUMBER,
	EVENT_ID NUMBER,
	STORE_ID NUMBER,
	SL_DISTNACE NUMBER,
	ESTIMATED_WORK_IMPACT VARCHAR2(500),
	SALES_PERCENTAGE_IMPACT NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	ACTUAL_PERCENTAGE_IMPACT NUMBER,
	 PRIMARY KEY (IMPACTED_STORE_ID)
  USING INDEX  ENABLE
   ) ;

