CREATE TABLE TMCS_ENTITY_COMMENTS
   (	COMMENT_ID NUMBER DEFAULT TMCS_ENTITY_COMMENTS_S.NEXTVAL,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(100),
	COMMENTS_CATEGORY VARCHAR2(100),
	COMMENTS VARCHAR2(4000),
	CLIENT_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	COMMENT_KEY VARCHAR2(50),
	ASSIGNED_TO VARCHAR2(50),
	COMMENT_DATE DATE,
	PARENT_COMMENT_ID NUMBER,
	MEETING_MINUTES CLOB,
	MILESTONE_ID NUMBER,
	COMMENT_TYPE VARCHAR2(50),
	BUDGET_ID NUMBER,
	SUBJECT VARCHAR2(500),
	STAGING_ID VARCHAR2(20),
	RFI_TYPE VARCHAR2(50),
	DUE_DATE DATE,
	FILE_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_ENTITY_COMMENTS_PK ON TMCS_ENTITY_COMMENTS (COMMENT_ID)
  ;
ALTER TABLE TMCS_ENTITY_COMMENTS ADD CONSTRAINT TMCS_ENTITY_COMMENTS_PK PRIMARY KEY (COMMENT_ID)
  USING INDEX TMCS_ENTITY_COMMENTS_PK  ENABLE;
CREATE INDEX TMCS_ENTITY_COMMENTS_INDX02 ON TMCS_ENTITY_COMMENTS (BUDGET_ID)
  ;
CREATE INDEX TMCS_ENTITY_COMMENTS_INDX01 ON TMCS_ENTITY_COMMENTS (CLIENT_ID, ENTITY_TYPE, ENTITY_ID)
  ;
CREATE UNIQUE INDEX TMCS_ENTITY_COMMENTS_PK ON TMCS_ENTITY_COMMENTS (COMMENT_ID)
  ;

