CREATE TABLE TMCS_USER_BRANDS_BK
   (	USER_BRAND_ID NUMBER(*,0),
	USER_NAME VARCHAR2(50),
	ENABLED VARCHAR2(10),
	BRAND_ID NUMBER(*,0),
	CLIENT_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;

