CREATE TABLE TMCS_CUST_LAYER_HEADER_DTL
   (	RECORD_ID NUMBER NOT NULL ENABLE,
	LAYER_ID NUMBER NOT NULL ENABLE,
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	REC_METADATA CLOB,
	GEOMETRY SDO_GEOMETRY,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_CUST_LAYER_HDR_DTL_PK ON TMCS_CUST_LAYER_HEADER_DTL (RECORD_ID, LAYER_ID)
  ;
ALTER TABLE TMCS_CUST_LAYER_HEADER_DTL ADD CONSTRAINT TMCS_CUST_LAYER_HDR_DTL_PK PRIMARY KEY (RECORD_ID, LAYER_ID)
  USING INDEX TMCS_CUST_LAYER_HDR_DTL_PK  ENABLE;
CREATE INDEX TMCS_CUST_LAYER_HDR_DTL_GIDX ON TMCS_CUST_LAYER_HEADER_DTL (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('WORK_TABLESPACE=SPTL_TS_INDX');
CREATE INDEX TMCS_CUST_LAYER_HEADER_DTL_IDX ON TMCS_CUST_LAYER_HEADER_DTL (LAYER_ID)
  ;
CREATE UNIQUE INDEX TMCS_CUST_LAYER_HDR_DTL_PK ON TMCS_CUST_LAYER_HEADER_DTL (RECORD_ID, LAYER_ID)
  ;

