CREATE TABLE TMCS_LEASE_STD_RPT_LABLE_KEYS
   (	REPORT_FUNCTIONALITY VARCHAR2(500),
	COMPONENT_KEY VARCHAR2(1000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	 PRIMARY KEY (REPORT_FUNCTIONALITY, COMPONENT_KEY)
  USING INDEX  ENABLE
   ) ;

