CREATE TABLE TMCS_EXCEPTION_HISTORY
   (	EXCEPTION_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	EXCEPTION_CODE VARCHAR2(500),
	EXCEPTION_DATE DATE,
	STATUS VARCHAR2(50),
	SELECTED_FLAG VARCHAR2(10),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	ERROR_CODE_IN_FIX VARCHAR2(10),
	 PRIMARY KEY (EXCEPTION_ID)
  USING INDEX  ENABLE
   ) ;

