CREATE TABLE TMCS_SQ_HEADER
   (	SQ_HEADER_ID NUMBER DEFAULT 1 NOT NULL ENABLE,
	SQ_VERSION NUMBER DEFAULT 1,
	SQ_STATUS VARCHAR2(1),
	ENTITY_TYPE VARCHAR2(32),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	APPROVAL_ROLE VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX TMCS_SQ_HEADER_PK ON TMCS_SQ_HEADER (SQ_HEADER_ID)
  ;
ALTER TABLE TMCS_SQ_HEADER ADD CONSTRAINT TMCS_SQ_HEADER_PK PRIMARY KEY (SQ_HEADER_ID)
  USING INDEX TMCS_SQ_HEADER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SQ_HEADER_PK ON TMCS_SQ_HEADER (SQ_HEADER_ID)
  ;
CREATE INDEX TMCS_SQ_HEADER_IDX01 ON TMCS_SQ_HEADER (ENTITY_TYPE, CLIENT_ID)
  ;

