CREATE TABLE TMCS_CLIENT_PASSWORD_POLICY
   (	POLICY_ID NUMBER DEFAULT TMCS_CLIENT_PASSWORD_POLICY_S.NEXTVAL NOT NULL ENABLE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	REMINDER_DAYS NUMBER,
	QUALITY_DESC CLOB,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATED_BY VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_NUMBER_VERSION NUMBER(38,0) DEFAULT 1,
	LAST_UPDATE_DATE TIMESTAMP (6),
	AGING_DAYS NUMBER,
	REGULAR_REGEX_PATTERN VARCHAR2(4000),
	REPEAT_REGEX_PATTERN VARCHAR2(4000),
	IS_PWD_REMINDER_ENABLED VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	PASSWORD_HISTORY NUMBER,
	ENABLED_MFA VARCHAR2(10),
	MFA_EXPIRY NUMBER,
	 CONSTRAINT TMCS_CLIENT_PASSWORD_POLICY_PK PRIMARY KEY (POLICY_ID)
  USING INDEX  ENABLE
   ) ;

