CREATE TABLE TMCS_MAP_TABLE_DEPENDENCIES
   (	ID NUMBER DEFAULT TMCS_MAP_TABLE_DEPENDENCIES_S.NEXTVAL,
	PRIMARY_TABLE_NAME VARCHAR2(320) NOT NULL ENABLE,
	DEPENDENCY_TABLE_NAME VARCHAR2(320) NOT NULL ENABLE,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_TABLE_DEPENDENCIES_PK ON TMCS_MAP_TABLE_DEPENDENCIES (ID)
  ;
ALTER TABLE TMCS_MAP_TABLE_DEPENDENCIES ADD CONSTRAINT TMCS_MAP_TABLE_DEPENDENCIES_PK PRIMARY KEY (ID)
  USING INDEX TMCS_MAP_TABLE_DEPENDENCIES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_TABLE_DEPENDENCIES_PK ON TMCS_MAP_TABLE_DEPENDENCIES (ID)
  ;
CREATE UNIQUE INDEX TMCS_MAP_TABLE_DEPENDENCY_UIDX ON TMCS_MAP_TABLE_DEPENDENCIES (PRIMARY_TABLE_NAME, DEPENDENCY_TABLE_NAME, ENTITY_TYPE)
  ;

