CREATE TABLE TMCS_SEC_USER_POC_ROLES
   (	USER_POC_ROLE_ID NUMBER(38,0) DEFAULT TMCS_SEC_USER_POC_ROLES_S.NEXTVAL,
	USER_NAME VARCHAR2(200) NOT NULL ENABLE,
	APP_ROLE_NAME VARCHAR2(50) NOT NULL ENABLE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10) NOT NULL ENABLE,
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	BU_ID NUMBER,
	 PRIMARY KEY (USER_POC_ROLE_ID)
  USING INDEX  ENABLE
   ) ;

