CREATE TABLE TMCS_ENTITY_CONTACTS
   (	ENTITY_CONTACT_ID NUMBER DEFAULT TMCS_ENTITY_CONTACTS_S.NEXTVAL NOT NULL ENABLE,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	PERSON_ID NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	 PRIMARY KEY (ENTITY_CONTACT_ID)
  USING INDEX  ENABLE
   ) ;

