CREATE TABLE TMCS_USER_VIEW_HISTORY
   (	HISTORY_ID NUMBER,
	USER_ID VARCHAR2(100),
	ENTITY_TYPE VARCHAR2(100),
	ENTITY_ID NUMBER,
	PAGE_VISITED VARCHAR2(500),
	VISITED_TIME DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	DESCRIPTION VARCHAR2(500),
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	SOURCE VARCHAR2(20) DEFAULT 'WEB',
	SESSION_ID VARCHAR2(100),
	 PRIMARY KEY (HISTORY_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_USER_VIEW_HISTORY_INDX03 ON TMCS_USER_VIEW_HISTORY (ENTITY_TYPE, USER_ID, CLIENT_ID, ORG_ID, ENTITY_ID)
  ;
CREATE INDEX TMCS_USER_VIEW_HISTORY_INDX02 ON TMCS_USER_VIEW_HISTORY (ENTITY_TYPE)
  ;
CREATE INDEX TMCS_USER_VIEW_HISTORY_INDX01 ON TMCS_USER_VIEW_HISTORY (USER_ID)
  ;

