CREATE TABLE TMCS_TAADMIN_ENTITYTA_LOAD
   (	ENTITYNUMBER VARCHAR2(320),
	ENTITYTYPE VARCHAR2(320),
	TATYPE VARCHAR2(320),
	TADESCRIPTION CLOB,
	BRANDID NUMBER,
	COUNTRY VARCHAR2(320),
	GEOMSTRING CLOB
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY ENTIT_TA_UPLOAD
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE SKIP 1
         STRING SIZES ARE IN BYTES
         READSIZE 99999999
         FIELDS TERMINATED BY |  OPTIONALLY ENCLOSED BY ''  LRTRIM
         MISSING FIELD VALUES ARE NULL
                 (  ENTITYNUMBER    CHAR(320)
                    ,ENTITYTYPE      CHAR(320)
                    ,TATYPE          CHAR(320)
                    ,TADESCRIPTION   CHAR (320000000)
                    ,BRANDID         CHAR(320)
                    ,COUNTRY         CHAR(320)
                    ,GEOMSTRING      CHAR (320000000)
                )
       )
      LOCATION
       ( ENTIT_TA_UPLOAD:'entity_TA_update.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;

