CREATE TABLE TMCS_SITE_MODEL_TEMPLATES
   (	TEMPLATE_ID NUMBER,
	TEMPLATE_NAME VARCHAR2(500),
	TEMPLATE_DESC VARCHAR2(500),
	STATUS VARCHAR2(500),
	NUMBER_OF_RECS NUMBER,
	CLIENT_ID NUMBER,
	BU_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	ORG_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_MODEL_TEMPLATES_PK ON TMCS_SITE_MODEL_TEMPLATES (TEMPLATE_ID)
  ;
ALTER TABLE TMCS_SITE_MODEL_TEMPLATES ADD CONSTRAINT TMCS_SITE_MODEL_TEMPLATES_PK PRIMARY KEY (TEMPLATE_ID)
  USING INDEX TMCS_SITE_MODEL_TEMPLATES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_MODEL_TEMPLATES_PK ON TMCS_SITE_MODEL_TEMPLATES (TEMPLATE_ID)
  ;

