CREATE TABLE TMCS_DATA_TEMPLATES
   (	TEMPLATE_ID NUMBER DEFAULT TMCS_DATA_TEMPLATES_S.nextval,
	TEMPLATE_NAME VARCHAR2(100) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(1000),
	MODULE_NAME VARCHAR2(500) NOT NULL ENABLE,
	TAB VARCHAR2(50),
	KEY_FIELD VARCHAR2(1000),
	DEPENDENCY VARCHAR2(100),
	LOAD_ORDER NUMBER,
	TEMPLATE_S3_PATH VARCHAR2(1000),
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
	CREATED_BY VARCHAR2(200) NOT NULL ENABLE,
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	KETTLE_CLIENT_ID VARCHAR2(100),
	KETTLE_JOB_NAME VARCHAR2(200),
	 CONSTRAINT TMCS_DATA_TEMPLATES_PK PRIMARY KEY (TEMPLATE_ID)
  USING INDEX  ENABLE
   ) ;

