CREATE TABLE TMCS_PROJECT_RENT_RENEWALS
   (	RENT_RENEWAL_ID NUMBER,
	PROJECT_ID NUMBER,
	CURRENT_STEP NUMBER,
	STEP_TYPE VARCHAR2(100),
	MONTHS NUMBER,
	MONTHLY_RENT NUMBER,
	TOTAL_RENT NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	COMMENTS VARCHAR2(4000),
	 PRIMARY KEY (RENT_RENEWAL_ID)
  USING INDEX  ENABLE
   ) ;

