CREATE TABLE TMCS_CONTACTS
   (	CONTACT_ID NUMBER DEFAULT TMCS_CONTACTS_SQ.NEXTVAL,
	ENTITY_ID NUMBER,
	ENTITY_TYPE VARCHAR2(25),
	ROLE VARCHAR2(250),
	NAME VARCHAR2(200),
	BUSINESS_PHONE VARCHAR2(50),
	EXTENSION VARCHAR2(50),
	CELLPHONE VARCHAR2(50),
	EMAIL VARCHAR2(50),
	FAX VARCHAR2(50),
	COMMENTS VARCHAR2(2000),
	COMPANY VARCHAR2(150),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CONTACT_USER_ID VARCHAR2(200),
	EXT_CONTACT_NUMBER VARCHAR2(50),
	LAST_NAME VARCHAR2(100),
	IS_SYSTEM_USER VARCHAR2(1),
	CONTACT_TYPE VARCHAR2(50),
	STATUS VARCHAR2(50),
	IS_VENDOR VARCHAR2(10),
	SEQ_NUMBER NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	WORKFLOW_CONTACT_FLAG VARCHAR2(10),
	IS_PERSON_RECORD VARCHAR2(10),
	PERSON_ID NUMBER,
	STAGING_ID VARCHAR2(4000)
   ) ;
  CREATE UNIQUE INDEX TMCS_CONTACTS_PK ON TMCS_CONTACTS (CONTACT_ID)
  ;
ALTER TABLE TMCS_CONTACTS ADD CONSTRAINT TMCS_CONTACTS_PK PRIMARY KEY (CONTACT_ID)
  USING INDEX TMCS_CONTACTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CONTACTS_PK ON TMCS_CONTACTS (CONTACT_ID)
  ;
CREATE INDEX TMCS_CONTACTS_INDX1 ON TMCS_CONTACTS (ENTITY_TYPE, ENTITY_ID)
  ;
CREATE INDEX TMCS_CONTACTS_INDX ON TMCS_CONTACTS (ENTITY_ID, CLIENT_ID)
  ;
CREATE INDEX TMCS_CONTACTS_INDX02 ON TMCS_CONTACTS (ROLE)
  ;

