CREATE TABLE TMCS_ANALOG_SEARCH_CRITERIA
   (	ANALOG_ID NUMBER,
	VARIABLE_NAME VARCHAR2(500),
	VARIABLE_VALUE VARCHAR2(4000),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	VARIABLE_VALUE_CLOB CLOB,
	SEARCH_CRITERIA_ID NUMBER
   ) ;

