CREATE TABLE TMCS_BIP_BURSTING_HDR
   (	HDR_ID NUMBER DEFAULT TMCS_BIP_BURSTING_HDR_S.NEXTVAL,
	CREATED_BY VARCHAR2(500),
	CREATION_DATE DATE,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(500),
	BU_ID NUMBER,
	STATUS VARCHAR2(50),
	XML_DATA CLOB,
	ERR_CODE NUMBER,
	ERR_MSG VARCHAR2(4000),
	BURSTING_FUNCTIONALITY VARCHAR2(500),
	JOB_NAME VARCHAR2(500),
	JOB_START_TIME TIMESTAMP (6),
	JOB_END_TIME TIMESTAMP (6),
	 CONSTRAINT TMCS_BIP_BURSTING_HDR_PK PRIMARY KEY (HDR_ID)
  USING INDEX  ENABLE
   ) ;

