CREATE TABLE TMCS_SEC_APP_ROLES
   (	APP_ROLE_ID NUMBER DEFAULT TMCS_SEC_APP_ROLES_S.NEXTVAL,
	APP_ROLE_NAME VARCHAR2(50) NOT NULL ENABLE,
	APP_ROLE_DESC VARCHAR2(4000),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	MODULE VARCHAR2(200),
	TA_ADMIN_ROLE VARCHAR2(20),
	APP_ROLE_TYPE VARCHAR2(10),
	 CONSTRAINT TMCS_SEC_APP_ROLES_UK1 UNIQUE (APP_ROLE_NAME)
  USING INDEX  ENABLE
   ) ;
  CREATE UNIQUE INDEX TMCS_SEC_APP_ROLES_PK ON TMCS_SEC_APP_ROLES (APP_ROLE_ID)
  ;
ALTER TABLE TMCS_SEC_APP_ROLES ADD PRIMARY KEY (APP_ROLE_ID)
  USING INDEX TMCS_SEC_APP_ROLES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SEC_APP_ROLES_PK ON TMCS_SEC_APP_ROLES (APP_ROLE_ID)
  ;
CREATE INDEX TMCS_SEC_APP_ROLES_IDX1 ON TMCS_SEC_APP_ROLES (UPPER(APP_ROLE_NAME), UPPER(APP_ROLE_TYPE))
  ;

