CREATE TABLE TMCS_CLIENT_MIGRATION_AUDIT
   (	LABELS VARCHAR2(20),
	LOVS VARCHAR2(20),
	STATUSES VARCHAR2(20),
	INFO_WINDOWS VARCHAR2(20),
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	MESSAGE VARCHAR2(1000),
	MIGRATE_OPTIONS VARCHAR2(2000)
   ) ;

