CREATE TABLE TMCS_ASK_TANGO_CONFIG
   (	CONFIG_ID NUMBER,
	CLIENT_ID VARCHAR2(500),
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(500),
	DEMO_SOURCE VARCHAR2(500),
	COMP_SOURCE VARCHAR2(500),
	SF_CODE VARCHAR2(500),
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE DEFAULT sysdate,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1
   ) ;
  CREATE UNIQUE INDEX TMCS_ASK_TANGO_CONFIG_PK ON TMCS_ASK_TANGO_CONFIG (CLIENT_ID, BRAND_ID, BU_ID, COUNTRY)
  ;
ALTER TABLE TMCS_ASK_TANGO_CONFIG ADD CONSTRAINT TMCS_ASK_TANGO_CONFIG_PK PRIMARY KEY (CLIENT_ID, BRAND_ID, BU_ID, COUNTRY)
  USING INDEX TMCS_ASK_TANGO_CONFIG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ASK_TANGO_CONFIG_PK ON TMCS_ASK_TANGO_CONFIG (CLIENT_ID, BRAND_ID, BU_ID, COUNTRY)
  ;

