CREATE TABLE TMCS_P2P_CREATE_DISAGG_TADEF
   (	GUID VARCHAR2(320),
	ENTITY_ID NUMBER,
	CLIENT_ID NUMBER,
	GEO_ID VARCHAR2(320),
	CBSA_CLASS NUMBER,
	STORE_CLASS NUMBER,
	GEO_CLASS NUMBER,
	SL_DISTANCE NUMBER,
	DRIVE_DISTANCE NUMBER,
	DRIVE_MINUTES NUMBER,
	LONGITUDE NUMBER,
	LATITUDE NUMBER,
	TADEF VARCHAR2(2),
	TA_TYPE VARCHAR2(32),
	REGION VARCHAR2(320)
   ) ;
  CREATE UNIQUE INDEX TMCS_P2P_DISAGG_TADEF_PK ON TMCS_P2P_CREATE_DISAGG_TADEF (GUID, ENTITY_ID, CLIENT_ID, GEO_ID)
  ;
ALTER TABLE TMCS_P2P_CREATE_DISAGG_TADEF ADD CONSTRAINT TMCS_P2P_DISAGG_TADEF_PK PRIMARY KEY (GUID, ENTITY_ID, CLIENT_ID, GEO_ID)
  USING INDEX TMCS_P2P_DISAGG_TADEF_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_P2P_DISAGG_TADEF_PK ON TMCS_P2P_CREATE_DISAGG_TADEF (GUID, ENTITY_ID, CLIENT_ID, GEO_ID)
  ;

