CREATE TABLE TMCS_REGIONS
   (	REGION_ID NUMBER(19,0),
	REGION_NUMBER VARCHAR2(256) NOT NULL ENABLE,
	REGION_NAME VARCHAR2(256),
	COUNTRY VARCHAR2(50),
	GEOMETRY SDO_GEOMETRY,
	C_EXT_ATTR1 VARCHAR2(250),
	C_EXT_ATTR2 VARCHAR2(250),
	C_EXT_ATTR3 VARCHAR2(250),
	C_EXT_ATTR4 VARCHAR2(250),
	C_EXT_ATTR5 VARCHAR2(250),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (REGION_ID)
  USING INDEX  ENABLE
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_REGIONS_INDX1 ON TMCS_REGIONS (COUNTRY, CLIENT_ID)
  ;
CREATE INDEX TMCS_REGIONS_INDX02 ON TMCS_REGIONS (UPPER(COUNTRY))
  ;
CREATE INDEX TMCS_REGIONS_GIDX ON TMCS_REGIONS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('WORK_TABLESPACE=SPTL_TS_INDX');
CREATE INDEX TMCS_REGIONS_INDX01 ON TMCS_REGIONS (CLIENT_ID)
  ;

