CREATE TABLE TMCS_SUPPLIER_STATE_TAX
   (	SUPPLIER_STATE_ID NUMBER DEFAULT TMCS_SUPPLIER_STATE_TAX_S.NEXTVAL,
	SUPPLIER_ID NUMBER,
	STATE VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	COUNTRY VARCHAR2(100),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	ORG_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 0,
	 PRIMARY KEY (SUPPLIER_STATE_ID)
  USING INDEX  ENABLE
   ) ;

