CREATE TABLE TMCS_US_CENSUS_REGIONS
   (	STATE_ID VARCHAR2(2),
	STATE_CODE VARCHAR2(2),
	STATE_NAME VARCHAR2(30),
	CENSUS_REGION VARCHAR2(30),
	CENSUS_DIVISION VARCHAR2(30),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_US_CENSUS_REGIONS_PK ON TMCS_US_CENSUS_REGIONS (STATE_ID)
  ;
ALTER TABLE TMCS_US_CENSUS_REGIONS ADD CONSTRAINT TMCS_US_CENSUS_REGIONS_PK PRIMARY KEY (STATE_ID)
  USING INDEX TMCS_US_CENSUS_REGIONS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_US_CENSUS_REGIONS_PK ON TMCS_US_CENSUS_REGIONS (STATE_ID)
  ;
CREATE INDEX TMCS_US_CENSUS_REGIONS_GIDX ON TMCS_US_CENSUS_REGIONS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

