CREATE TABLE TMCS_LABR_BG_CUST_DATA
   (	BG_ID VARCHAR2(321),
	POPF_18P_C NUMBER(17,6),
	LIFESTYLE NUMBER(17,6),
	MALL NUMBER(17,6),
	OUTLET NUMBER(17,6),
	STRIP_CENTER NUMBER(17,6),
	OVERALL NUMBER(6,2),
	EFF_POP_LS NUMBER(17,6),
	EFF_POP_MA NUMBER(17,6),
	EFF_POP_OU NUMBER(17,6),
	EFF_POP_SC NUMBER(17,6),
	EFF_POP_OVERALL NUMBER(17,6),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_LABR_BG_CUST_DATA_GIDX ON TMCS_LABR_BG_CUST_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

