CREATE TABLE TMCS_USER_QUERIES_QB
   (	QUERY_ID NUMBER,
	USER_NAME VARCHAR2(100),
	QUERY_TEXT CLOB,
	DESCRIPTION VARCHAR2(1000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	BU_ID NUMBER,
	COUNTRY VARCHAR2(100),
	TABLE_NAME VARCHAR2(100),
	 PRIMARY KEY (QUERY_ID)
  USING INDEX  ENABLE
   ) ;

