CREATE TABLE TMCS_FOLDER_TEMPLATE_DTL_TEMP
   (	FOLDER_TEMPLATE_DTL_ID NUMBER,
	FOLDER_TEMPLATE_ID NUMBER,
	FOLDER_SEQUENCE NUMBER,
	FOLDER_NAME VARCHAR2(250),
	DESCRIPTION VARCHAR2(250),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(50),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	PARENT_FOLDER_ID NUMBER,
	STATUS VARCHAR2(50)
   ) ;

