CREATE TABLE TMCS_USER_OTP
   (	OTP_ID NUMBER DEFAULT TMCS_USER_OTP_S.NEXTVAL NOT NULL ENABLE,
	USER_NAME VARCHAR2(100),
	OTP VARCHAR2(10),
	OTP_SENT_TIME TIMESTAMP (6),
	METHOD_SELECTED VARCHAR2(10),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	EXPIRY_TIME TIMESTAMP (6),
	OTP_TYPE VARCHAR2(20)
   ) ;

