CREATE TABLE TMCS_THAI_DISTRICTS
   (	DISTRICT_ID NUMBER(19,0),
	DISTRICT_NAME VARCHAR2(75),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	POPULATION NUMBER,
	HOUSEHOLD NUMBER
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_THAI_DISTRICTS_PK ON TMCS_THAI_DISTRICTS (DISTRICT_ID)
  ;
ALTER TABLE TMCS_THAI_DISTRICTS ADD CONSTRAINT TMCS_THAI_DISTRICTS_PK PRIMARY KEY (DISTRICT_ID)
  USING INDEX TMCS_THAI_DISTRICTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_THAI_DISTRICTS_PK ON TMCS_THAI_DISTRICTS (DISTRICT_ID)
  ;
CREATE INDEX TMCS_THAI_DISTRICTS_GIDX ON TMCS_THAI_DISTRICTS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

