CREATE TABLE TMCS_CAN_CD
   (	GEO_ID VARCHAR2(32),
	GEO_NAME VARCHAR2(102),
	HH_2011 NUMBER(10,0),
	LANDAREA NUMBER(10,2),
	POP_2011 NUMBER(19,0),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	MKT_CLASS NUMBER(10,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_CAN_CD_PK ON TMCS_CAN_CD (GEO_ID)
  ;
ALTER TABLE TMCS_CAN_CD ADD CONSTRAINT TMCS_CAN_CD_PK PRIMARY KEY (GEO_ID)
  USING INDEX TMCS_CAN_CD_PK  ENABLE;
CREATE INDEX TMCS_CAN_CD_GIDX ON TMCS_CAN_CD (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_CAN_CD_PK ON TMCS_CAN_CD (GEO_ID)
  ;

