CREATE TABLE TMCS_SDA_AGMTS
   (	AGREEMENT_ID NUMBER DEFAULT TMCS_SDA_AGMTS_S.NEXTVAL,
	SDA_ID NUMBER,
	AGREEMENT_NUMBER VARCHAR2(50),
	STATUS VARCHAR2(30),
	AGREEMENT_START_DATE DATE,
	AGREEMENT_END_DATE DATE,
	COUNTRIES VARCHAR2(1000),
	COMMENTS VARCHAR2(4000),
	TOTAL_UNIT_COMMITMENT NUMBER,
	RECOVERY_INCENTIVE VARCHAR2(100),
	PREPAY_INITIAL_FEE VARCHAR2(100),
	ESTIMATED_AUV NUMBER,
	PER_UNIT_PENALTY NUMBER,
	SIGNED VARCHAR2(20),
	CURE_PERIOD VARCHAR2(20),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	CONFIDENTIALITY VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_SDA_AGMTS_PK ON TMCS_SDA_AGMTS (AGREEMENT_ID)
  ;
ALTER TABLE TMCS_SDA_AGMTS ADD CONSTRAINT TMCS_SDA_AGMTS_PK PRIMARY KEY (AGREEMENT_ID)
  USING INDEX TMCS_SDA_AGMTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SDA_AGMTS_PK ON TMCS_SDA_AGMTS (AGREEMENT_ID)
  ;

