CREATE TABLE TMCS_FOLDER_TEMPL_DTL_ROLES
   (	FOLDER_TEMPL_DTL_ROLE_ID NUMBER DEFAULT tmcs.tmcs_folder_templ_dtl_roles_s.nextval,
	FOLDER_TEMPLATE_DTL_ID NUMBER,
	FOLDER_ROLE VARCHAR2(250),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(50),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (FOLDER_TEMPL_DTL_ROLE_ID)
  USING INDEX  ENABLE
   ) ;

