CREATE TABLE TMCS_PROJ_BUDGET_ENTITIES
   (	BUDGET_ENTITY_ID NUMBER,
	PROJECT_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	INVOICE_NUMBER VARCHAR2(50),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	COUNTRY_CODE VARCHAR2(50),
	 PRIMARY KEY (BUDGET_ENTITY_ID)
  USING INDEX  ENABLE
   ) ;

