CREATE TABLE TMCS_TARGET_ENCROACHMENTS
   (	ENCR_ID NUMBER(*,0) NOT NULL ENABLE,
	TARGET_ID NUMBER(*,0) NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(30),
	ENTITY_NAME VARCHAR2(50),
	ENTITY_NUMBER VARCHAR2(50),
	DISTANCE NUMBER,
	SALES NUMBER,
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	C_EXT_ATTR4 VARCHAR2(500),
	C_EXT_ATTR5 VARCHAR2(500),
	D_EXT_ATTR1 DATE,
	D_EXT_ATTR2 DATE,
	D_EXT_ATTR3 DATE,
	D_EXT_ATTR4 DATE,
	D_EXT_ATTR5 DATE
   ) ;
  CREATE UNIQUE INDEX TMCS_TARGET_ENCROACHMENTS_PK ON TMCS_TARGET_ENCROACHMENTS (ENCR_ID)
  ;
ALTER TABLE TMCS_TARGET_ENCROACHMENTS ADD CONSTRAINT TMCS_TARGET_ENCROACHMENTS_PK PRIMARY KEY (ENCR_ID)
  USING INDEX TMCS_TARGET_ENCROACHMENTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_TARGET_ENCROACHMENTS_PK ON TMCS_TARGET_ENCROACHMENTS (ENCR_ID)
  ;

