CREATE TABLE TMCS_INVOICE_TAX_RATES
   (	TAX_RATE_ID NUMBER DEFAULT tmcs.TMCS_INVOICE_TAX_RATES_S.nextval,
	INVOICE_ID NUMBER,
	TAX_TYPE VARCHAR2(100),
	TAX_RATE NUMBER,
	AMOUNT NUMBER,
	TAX NUMBER,
	COMMENTS VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	 PRIMARY KEY (TAX_RATE_ID)
  USING INDEX  ENABLE
   ) ;

