CREATE TABLE TMCS_CUST_SHARE_HOLDERS
   (	SHARE_HOLDER_ID NUMBER DEFAULT TMCS_CUST_SHARE_HOLDERS_S.NEXTVAL NOT NULL ENABLE,
	CUSTOMER_ID NUMBER,
	CUSTOMER_SITE_ID NUMBER,
	SHARE_HOLDER_NUMBER VARCHAR2(100),
	SHARE_HOLDER_NAME VARCHAR2(500),
	SHARE_HOLDER_TYPE VARCHAR2(50),
	VOTING_CLASS VARCHAR2(100),
	NON_VOTING_CLASS VARCHAR2(100),
	OWNERSHIP_PCT NUMBER,
	OFFICER_POS_HELP VARCHAR2(500),
	START_DATE DATE,
	END_DATE DATE,
	STATUS VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	STAGING_ID NUMBER,
	 PRIMARY KEY (SHARE_HOLDER_ID)
  USING INDEX  ENABLE
   ) ;

