CREATE TABLE TMCS_CLIENT_PROFILE_VALUES
   (	CLIENT_ID NUMBER,
	PROFILE_CODE VARCHAR2(200),
	SELECTED VARCHAR2(1),
	COUNTRY_CODE VARCHAR2(200),
	BRAND_ID NUMBER,
	OPTI_BUFFER NUMBER,
	UNIT VARCHAR2(200),
	 CONSTRAINT TMCS_CLIENT_PROFILE_VALUES_U01 UNIQUE (CLIENT_ID, BRAND_ID, PROFILE_CODE, COUNTRY_CODE)
  USING INDEX  ENABLE
   ) ;

