CREATE TABLE TMCS_ADHOC_TASKS_NOTIFY_USERS
   (	ADHOC_TASK_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	USER_NAME VARCHAR2(200),
	FIRST_NAME VARCHAR2(500),
	LAST_NAME VARCHAR2(500),
	EMAIL_ADDRESS VARCHAR2(500),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	TMCS_ADHOC_TASKS_NOTIFY_SEQ NUMBER DEFAULT TMCS_ADHOC_TASKS_NOTIFY_S.NEXTVAL,
	 PRIMARY KEY (ADHOC_TASK_ID, EMAIL_ADDRESS)
  USING INDEX  ENABLE
   ) ;

