CREATE TABLE TMCS_DEMO_RPT_VINTAGE
   (	LINE_NUMBER NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(200),
	BU_ID NUMBER,
	VINTAGE_CODE VARCHAR2(100),
	VINTAGE_DESC VARCHAR2(500),
	 PRIMARY KEY (LINE_NUMBER)
  USING INDEX  ENABLE
   ) ;

