CREATE TABLE TMCS_REPORT_FILES
   (	FILE_ID NUMBER(*,0) NOT NULL ENABLE,
	FILE_NAME VARCHAR2(100),
	FILE_CONTENT BLOB,
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(50),
	REPORT_TYPE VARCHAR2(50),
	IS_S3_REPORT VARCHAR2(10) DEFAULT 'N',
	REPORT_PARAMS CLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_REPORT_FILES_PK ON TMCS_REPORT_FILES (FILE_ID)
  ;
ALTER TABLE TMCS_REPORT_FILES ADD CONSTRAINT TMCS_REPORT_FILES_PK PRIMARY KEY (FILE_ID)
  USING INDEX TMCS_REPORT_FILES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_REPORT_FILES_PK ON TMCS_REPORT_FILES (FILE_ID)
  ;

