CREATE TABLE TMCS_CUST_LAYER_SHARE_DTL
   (	LAYER_SHARE_ID NUMBER NOT NULL ENABLE,
	LAYER_ID NUMBER NOT NULL ENABLE,
	SHARED_BY VARCHAR2(320),
	SHARED_TO VARCHAR2(320),
	ACCESS_LEVEL VARCHAR2(320),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BU_ID NUMBER,
	FULLNAME VARCHAR2(320)
   ) ;

