CREATE TABLE TMCS_ADMIN_BULK_USER_UPLOAD
   (	BATCH_ID NUMBER,
	FIRST_NAME VARCHAR2(200) NOT NULL ENABLE,
	LAST_NAME VARCHAR2(200) NOT NULL ENABLE,
	EMAIL VARCHAR2(200) NOT NULL ENABLE,
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRANDS VARCHAR2(2000) NOT NULL ENABLE,
	COUNTRIES VARCHAR2(2000) NOT NULL ENABLE,
	REGIONS VARCHAR2(2000),
	SECURITY_ROLES VARCHAR2(2000),
	MOBILE_ACCESS VARCHAR2(1) DEFAULT 'N',
	CREATED_DATE DATE DEFAULT sysdate,
	PROCESSED VARCHAR2(1),
	STATUS_MSG VARCHAR2(2000),
	COPY_FROM VARCHAR2(200),
	USER_TYPE VARCHAR2(20) DEFAULT 'CORPORATE',
	SUPPLIER_ID NUMBER,
	PREFERRED_LOCALE VARCHAR2(20)
   ) ;

