CREATE TABLE TMCS_TARGETS_B_DETAIL
   (	TARGET_ID NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	SF_EXT_ATTR1 NUMBER,
	SF_EXT_ATTR2 NUMBER,
	SF_EXT_ATTR3 NUMBER,
	SF_EXT_ATTR4 NUMBER,
	SF_EXT_ATTR5 NUMBER,
	SF_EXT_ATTR6 NUMBER,
	SF_EXT_ATTR7 NUMBER,
	SF_EXT_ATTR8 NUMBER,
	SF_EXT_ATTR9 NUMBER,
	SF_EXT_ATTR10 NUMBER,
	SF_EXT_ATTR11 NUMBER,
	SF_EXT_ATTR12 NUMBER,
	SF_EXT_ATTR13 NUMBER,
	SF_EXT_ATTR14 NUMBER,
	SF_EXT_ATTR15 NUMBER,
	SF_EXT_ATTR16 NUMBER,
	SF_EXT_ATTR17 NUMBER,
	SF_EXT_ATTR18 NUMBER,
	SF_EXT_ATTR19 NUMBER,
	SF_EXT_ATTR20 NUMBER,
	SF_EXT_ATTR21 NUMBER,
	SF_EXT_ATTR22 NUMBER,
	SF_EXT_ATTR23 NUMBER,
	SF_EXT_ATTR24 NUMBER,
	SF_EXT_ATTR25 NUMBER,
	SF_EXT_ATTR26 NUMBER,
	SF_EXT_ATTR27 NUMBER,
	SF_EXT_ATTR28 NUMBER,
	SF_EXT_ATTR29 NUMBER,
	SF_EXT_ATTR30 NUMBER,
	SF_EXT_ATTR31 NUMBER,
	SF_EXT_ATTR32 NUMBER,
	SF_EXT_ATTR33 NUMBER,
	SF_EXT_ATTR34 NUMBER,
	SF_EXT_ATTR35 NUMBER,
	SF_EXT_ATTR36 NUMBER,
	SF_EXT_ATTR37 NUMBER,
	SF_EXT_ATTR38 NUMBER,
	SF_EXT_ATTR39 NUMBER,
	SF_EXT_ATTR40 NUMBER,
	T_EXT_ATTR1 VARCHAR2(500),
	T_EXT_ATTR2 VARCHAR2(500),
	T_EXT_ATTR3 VARCHAR2(500),
	T_EXT_ATTR4 VARCHAR2(500),
	T_EXT_ATTR5 VARCHAR2(500),
	T_EXT_ATTR6 VARCHAR2(500),
	T_EXT_ATTR7 VARCHAR2(500),
	T_EXT_ATTR8 VARCHAR2(500),
	T_EXT_ATTR9 VARCHAR2(500),
	T_EXT_ATTR10 VARCHAR2(500)
   )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX TMCS_TARGETS_B_DETAIL_PK ON TMCS_TARGETS_B_DETAIL (TARGET_ID)
  ;
ALTER TABLE TMCS_TARGETS_B_DETAIL ADD CONSTRAINT TMCS_TARGETS_B_DETAIL_PK PRIMARY KEY (TARGET_ID)
  USING INDEX TMCS_TARGETS_B_DETAIL_PK  ENABLE;
CREATE INDEX TMCS_TARGETS_B_DETAIL_INDX ON TMCS_TARGETS_B_DETAIL (CLIENT_ID)
  ;
CREATE INDEX TMCS_TARGETS_B_DETAIL_INDX1 ON TMCS_TARGETS_B_DETAIL (CLIENT_ID, BRAND_ID, ORG_ID)
  ;
CREATE UNIQUE INDEX TMCS_TARGETS_B_DETAIL_PK ON TMCS_TARGETS_B_DETAIL (TARGET_ID)
  ;

