CREATE TABLE TMCS_CAN_CSD
   (	CSDUID VARCHAR2(50),
	CSDNAME VARCHAR2(250),
	CSDTYPE VARCHAR2(250),
	PRUID VARCHAR2(10),
	PRNAME VARCHAR2(250),
	CDUID VARCHAR2(25),
	CDNAME VARCHAR2(250),
	CDTYPE VARCHAR2(250),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_CAN_CSD_GIDX ON TMCS_CAN_CSD (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

