CREATE TABLE TMCS_INVOICE_PAYMENTS
   (	PAYMENT_ID NUMBER,
	PAYMENT_NUMBER VARCHAR2(100),
	INVOICE_ID NUMBER,
	INVOICE_AMOUNT NUMBER,
	COMMENTS VARCHAR2(4000),
	REF_PAYMENT_ID NUMBER,
	VENDOR_ID NUMBER,
	STATUS VARCHAR2(50),
	PAYMENT_METHOD VARCHAR2(100),
	PAYMENT_REFERENCE VARCHAR2(1000),
	PAYMENT_DATE DATE,
	PAYMENT_AMOUNT NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	APPLIED_AMOUNT NUMBER,
	 PRIMARY KEY (PAYMENT_ID)
  USING INDEX  ENABLE
   ) ;

