CREATE TABLE TMCS_STORE_CUST
   (	STORE_NUMBER VARCHAR2(11),
	CUSTOMER_ID VARCHAR2(11),
	LAT NUMBER(17,6),
	LON NUMBER(17,6),
	SALES NUMBER(10,0),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_STORE_CUST_GIDX ON TMCS_STORE_CUST (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

