CREATE TABLE TMCS_SURVEY_QUESTION
   (	QUESTION_ID NUMBER(*,0),
	QUESTION_NUMBER NUMBER(*,0),
	SURVEY_ID NUMBER(*,0),
	QUESTION_TITLE VARCHAR2(255),
	QUESTION_DESCRIPTION VARCHAR2(2048),
	QUESTION_TYPE_ID VARCHAR2(2048),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	 PRIMARY KEY (QUESTION_ID)
  USING INDEX  ENABLE
   ) ;

