CREATE TABLE TMCS_APP_RESOURCE_METADATA_UDF
   (	RESOURCE_METADATA_ID NUMBER DEFAULT TMCS_RESOURCE_METADATA_ID_S.NEXTVAL,
	COMPONENT_KEY VARCHAR2(500),
	COMPONENT_TYPE VARCHAR2(50),
	REF_COMPONENT_KEY VARCHAR2(500),
	PARENT_KEY VARCHAR2(500),
	COMPONENT_KEY_OLD VARCHAR2(500),
	DEPRECATED VARCHAR2(20) DEFAULT 'FALSE',
	MOBILE_ENABLED VARCHAR2(20),
	TABLE_NAME VARCHAR2(30),
	COLUMN_NAME VARCHAR2(30),
	COLUMN_TYPE VARCHAR2(30),
	LOOKUP_CODE VARCHAR2(30),
	APP_ROLES VARCHAR2(1000),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	MODULE_NAME VARCHAR2(500),
	SUB_MODULE_NAME VARCHAR2(500),
	VQB_TABLE_NAME VARCHAR2(30),
	VQB_COLUMN_NAME VARCHAR2(30),
	VQB_COLUMN_TYPE VARCHAR2(30)
   ) ;
  CREATE UNIQUE INDEX TMCS_APP_RESOURCE_METADATA_UDF_PK ON TMCS_APP_RESOURCE_METADATA_UDF (RESOURCE_METADATA_ID)
  ;
ALTER TABLE TMCS_APP_RESOURCE_METADATA_UDF ADD CONSTRAINT TMCS_APP_RESOURCE_METADATA_UDF_PK PRIMARY KEY (RESOURCE_METADATA_ID)
  USING INDEX TMCS_APP_RESOURCE_METADATA_UDF_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_APP_RESOURCE_METADATA_UDF_UK ON TMCS_APP_RESOURCE_METADATA_UDF (COMPONENT_KEY)
  ;
CREATE UNIQUE INDEX TMCS_APP_RESOURCE_METADATA_UDF_PK ON TMCS_APP_RESOURCE_METADATA_UDF (RESOURCE_METADATA_ID)
  ;

