CREATE TABLE TMCS_MAP_BOOKMARK_SHARE_DTL
   (	BOOKMARK_SHARE_ID NUMBER NOT NULL ENABLE,
	BOOKMARK_ID NUMBER NOT NULL ENABLE,
	SHARED_BY VARCHAR2(50),
	SHARED_TO VARCHAR2(50),
	ACCESS_LEVEL VARCHAR2(50),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(32),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN VARCHAR2(500),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	FULLNAME VARCHAR2(200),
	BU_ID NUMBER,
	 CONSTRAINT FK_TMCS_MAP_BOOKMARK_SHARE_DTL FOREIGN KEY (BOOKMARK_ID)
	  REFERENCES TMCS_MAP_BOOKMARKS (BOOKMARK_ID) ON DELETE CASCADE ENABLE
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_BOOKMARK_SHARE_DTL_PK ON TMCS_MAP_BOOKMARK_SHARE_DTL (BOOKMARK_SHARE_ID)
  ;
ALTER TABLE TMCS_MAP_BOOKMARK_SHARE_DTL ADD CONSTRAINT TMCS_MAP_BOOKMARK_SHARE_DTL_PK PRIMARY KEY (BOOKMARK_SHARE_ID)
  USING INDEX TMCS_MAP_BOOKMARK_SHARE_DTL_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_BOOKMARK_SHARE_DTL_PK ON TMCS_MAP_BOOKMARK_SHARE_DTL (BOOKMARK_SHARE_ID)
  ;

