CREATE TABLE TMCS_MAP_FORM_HEADERS
   (	FORM_ID NUMBER,
	FORM_NAME VARCHAR2(320),
	BU_ID NUMBER,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_FORM_HEADERS_PK ON TMCS_MAP_FORM_HEADERS (FORM_ID)
  ;
ALTER TABLE TMCS_MAP_FORM_HEADERS ADD CONSTRAINT TMCS_MAP_FORM_HEADERS_PK PRIMARY KEY (FORM_ID)
  USING INDEX TMCS_MAP_FORM_HEADERS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_FORM_HEADERS_PK ON TMCS_MAP_FORM_HEADERS (FORM_ID)
  ;

