CREATE TABLE TMCS_DATA_IMPORTS
   (	IMPORT_ID NUMBER DEFAULT TMCS_DATA_IMPORTS_S.nextval,
	FILE_NAME VARCHAR2(500) NOT NULL ENABLE,
	STATUS VARCHAR2(50),
	VALIDATION_RESULT VARCHAR2(1000),
	RECORD_PROCESSED NUMBER,
	RECORD_FAILED NUMBER,
	S3_LOCATION VARCHAR2(1000),
	S3_URL VARCHAR2(4000),
	CLIENT_ID NUMBER NOT NULL ENABLE,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
	CREATED_BY VARCHAR2(200) NOT NULL ENABLE,
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	TEMPLATE_ID NUMBER NOT NULL ENABLE,
	PROCESSING_MSG VARCHAR2(4000),
	BATCH_ID NUMBER,
	 CONSTRAINT TMCS_DATA_IMPORTS_PK PRIMARY KEY (IMPORT_ID)
  USING INDEX  ENABLE
   ) ;

