CREATE TABLE TMCS_STORE_ZIPCODE_SALES
   (	STORE_ZIPCODE_ID NUMBER,
	STORE_ID NUMBER,
	ZIPCODE VARCHAR2(50),
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	C_EXT_ATTR4 VARCHAR2(500),
	C_EXT_ATTR5 VARCHAR2(500),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	D_EXT_ATTR1 DATE,
	D_EXT_ATTR2 DATE,
	D_EXT_ATTR3 DATE,
	D_EXT_ATTR4 DATE,
	D_EXT_ATTR5 DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 CONSTRAINT TMCS_STORE_ZIPCODE_SALES_PK PRIMARY KEY (STORE_ZIPCODE_ID) DISABLE
   ) ;
CREATE UNIQUE INDEX TMCS_STORE_ZIPCODE_SALES_PK ON TMCS_STORE_ZIPCODE_SALES (STORE_ZIPCODE_ID)
  ;

