CREATE TABLE TMCS_SITE_SNR_DETAIL
   (	SNR_DETAIL_ID NUMBER,
	SNR_ID NUMBER,
	TEMPLATE_ID NUMBER,
	SITE_ID NUMBER,
	SITE_COMPONENT_KEY VARCHAR2(500),
	COL_VALUE VARCHAR2(500),
	COL_WEIGHT NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	STATUS VARCHAR2(1),
	STORE_TABLE_NAME VARCHAR2(100),
	STORE_COLUMN_NAME VARCHAR2(100),
	STORE_COLUMN_MEAN NUMBER,
	STORE_COLUMN_STDDIV NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_SNR_DETAIL_PK ON TMCS_SITE_SNR_DETAIL (SNR_DETAIL_ID)
  ;
ALTER TABLE TMCS_SITE_SNR_DETAIL ADD CONSTRAINT TMCS_SITE_SNR_DETAIL_PK PRIMARY KEY (SNR_DETAIL_ID)
  USING INDEX TMCS_SITE_SNR_DETAIL_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_SNR_DETAIL_PK ON TMCS_SITE_SNR_DETAIL (SNR_DETAIL_ID)
  ;

