CREATE TABLE TMCS_PICTURES
   (	PIC_ID NUMBER(*,0) DEFAULT TMCS_PICTURES_SQ.NEXTVAL NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER(*,0),
	PIC_NAME VARCHAR2(100),
	PIC_URL VARCHAR2(100),
	PIC_DESC VARCHAR2(300),
	PIC_CONTENT BLOB,
	PIC_DISABLED NUMBER(*,0) DEFAULT 0,
	STATUS VARCHAR2(50),
	CAPITAL_EXPENSE NUMBER,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	AWS_KEY VARCHAR2(500),
	AWS_VERSION_ID VARCHAR2(100),
	AQ_RESOURCE_IMAGE_SYS_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_PICTURES_PK ON TMCS_PICTURES (PIC_ID)
  ;
ALTER TABLE TMCS_PICTURES ADD CONSTRAINT TMCS_PICTURES_PK PRIMARY KEY (PIC_ID)
  USING INDEX TMCS_PICTURES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PICTURES_PK ON TMCS_PICTURES (PIC_ID)
  ;

