CREATE TABLE TMCS_COUNTRY_COUNTY
   (	COUNTRY_CODE_3 VARCHAR2(200),
	COUNTRY VARCHAR2(200),
	COUNTY_CODE VARCHAR2(200),
	COUNTY_NAME VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	POPULATION NUMBER,
	MEDHHINC NUMBER
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_COUNTRY_COUNTY_PK ON TMCS_COUNTRY_COUNTY (COUNTRY_CODE_3, COUNTY_CODE)
  ;
ALTER TABLE TMCS_COUNTRY_COUNTY ADD CONSTRAINT TMCS_COUNTRY_COUNTY_PK PRIMARY KEY (COUNTRY_CODE_3, COUNTY_CODE)
  USING INDEX TMCS_COUNTRY_COUNTY_PK  ENABLE;
CREATE BITMAP INDEX TMCS_COUNTRY_COUNTY_BIDX ON TMCS_COUNTRY_COUNTY (COUNTRY_CODE_3)
  ;
CREATE UNIQUE INDEX TMCS_COUNTRY_COUNTY_PK ON TMCS_COUNTRY_COUNTY (COUNTRY_CODE_3, COUNTY_CODE)
  ;
CREATE INDEX TMCS_COUNTRY_COUNTY_GIDX ON TMCS_COUNTRY_COUNTY (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

