CREATE TABLE TMCS_LOOKUP_LANGUAGES
   (	CLIENT_ID NUMBER(*,0),
	BU_ID NUMBER,
	COUNTRY VARCHAR2(20),
	LANGUAGE_CODE VARCHAR2(300),
	ORG_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	DIVISION_ID NUMBER
   ) ;
CREATE INDEX TMCS_LOOKUP_LANGUAGES_IDX0 ON TMCS_LOOKUP_LANGUAGES (CLIENT_ID, BU_ID, COUNTRY, LANGUAGE_CODE)
  ;

