CREATE TABLE TMCS_IFA_INCENTIVE
   (	IFA_INC_ID NUMBER,
	IFA_ID NUMBER,
	FIN_CATEGORY VARCHAR2(50),
	FIN_TYPE VARCHAR2(100),
	DESCRIPTION VARCHAR2(200),
	START_DATE DATE,
	END_DATE DATE,
	AMOUNT_TYPE VARCHAR2(100),
	PERCENTAGE NUMBER,
	AMOUNT NUMBER,
	COMMENTS VARCHAR2(2000),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	C_EXT_ATTR01 VARCHAR2(500),
	C_EXT_ATTR02 VARCHAR2(500),
	C_EXT_ATTR03 VARCHAR2(500),
	N_EXT_ATTR01 NUMBER,
	N_EXT_ATTR02 NUMBER,
	N_EXT_ATTR03 NUMBER,
	C_EXT_LOV1 VARCHAR2(200),
	C_EXT_LOV2 VARCHAR2(200),
	C_EXT_LOV3 VARCHAR2(200)
   ) ;
  CREATE UNIQUE INDEX TMCS_IFA_INCENTIVE_PK ON TMCS_IFA_INCENTIVE (IFA_INC_ID)
  ;
ALTER TABLE TMCS_IFA_INCENTIVE ADD CONSTRAINT TMCS_IFA_INCENTIVE_PK PRIMARY KEY (IFA_INC_ID)
  USING INDEX TMCS_IFA_INCENTIVE_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_IFA_INCENTIVE_PK ON TMCS_IFA_INCENTIVE (IFA_INC_ID)
  ;

