CREATE TABLE TMCS_ADOBE_SIGN_REQUESTS
   (	REQUEST_ID NUMBER DEFAULT TMCS_ADOBE_SIGN_REQUESTS_S.NEXTVAL,
	CONTRACT_TYPE VARCHAR2(50),
	CONTRACT_ID NUMBER,
	EMAILS VARCHAR2(500),
	FILE_ID NUMBER,
	REQUEST_JSON VARCHAR2(4000),
	AGREEMENT_ID VARCHAR2(100),
	DOCUMENT_ID VARCHAR2(1000),
	ETAG VARCHAR2(100),
	STATUS VARCHAR2(100),
	ERROR_MESSAGE VARCHAR2(4000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	ORG_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER DEFAULT 1,
	FILE_NAME VARCHAR2(500),
	 CONSTRAINT TMCS_ADOBE_SIGN_REQUESTS_PK PRIMARY KEY (REQUEST_ID)
  USING INDEX  ENABLE
   ) ;

