CREATE TABLE TMCS_MAP_INFO_WINDOW_TABNAMES
   (	TABNAME_ID NUMBER,
	TAB_NAME VARCHAR2(100) NOT NULL ENABLE,
	LANGUAGE VARCHAR2(21) NOT NULL ENABLE,
	INFO_WINDOW_ID NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	BU_ID NUMBER NOT NULL ENABLE,
	TAB_ID NUMBER NOT NULL ENABLE,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	BRAND_ID NUMBER,
	 CONSTRAINT TMCS_MAP_INFO_WINDOW_TABNAM_PK PRIMARY KEY (TABNAME_ID, INFO_WINDOW_ID, TAB_ID)
  USING INDEX  ENABLE
   ) ;
CREATE UNIQUE INDEX TMCS_MAP_INFO_WIN_TABNAMES_UK ON TMCS_MAP_INFO_WINDOW_TABNAMES (TABNAME_ID)
  ;

