CREATE TABLE TMCS_SITE_SF_CANNIBALIZED
   (	SF_ID NUMBER,
	ENTITY_TYPE VARCHAR2(20),
	ENTITY_ID VARCHAR2(20),
	ENTITY_NAME VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	CITY VARCHAR2(100),
	STATE VARCHAR2(100),
	ZIP VARCHAR2(100),
	CANNIBALIZED NUMBER,
	ADJ_CANNIBALIZED NUMBER,
	TOTAL_SALES NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	N_EXT_ATTR01 NUMBER,
	N_EXT_ATTR02 NUMBER,
	N_EXT_ATTR03 NUMBER,
	N_EXT_ATTR04 NUMBER,
	N_EXT_ATTR05 NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	C_EXT_ATTR01 VARCHAR2(150),
	C_EXT_ATTR02 VARCHAR2(150),
	C_EXT_ATTR03 VARCHAR2(150),
	C_EXT_ATTR04 VARCHAR2(150),
	C_EXT_ATTR05 VARCHAR2(150),
	SL_DISTANCE NUMBER,
	DRIVE_DISTANCE NUMBER,
	DRIVE_MINUTES NUMBER,
	PCT_IMPACT NUMBER,
	STORE_CLASS NUMBER,
	CBSA_CLASS NUMBER,
	LOC_TYPE VARCHAR2(200),
	GEOMETRY SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SITE_SF_CANNIBALIZED_PK ON TMCS_SITE_SF_CANNIBALIZED (SF_ID, ENTITY_ID)
  ;
ALTER TABLE TMCS_SITE_SF_CANNIBALIZED ADD CONSTRAINT TMCS_SITE_SF_CANNIBALIZED_PK PRIMARY KEY (SF_ID, ENTITY_ID)
  USING INDEX TMCS_SITE_SF_CANNIBALIZED_PK  ENABLE;
CREATE INDEX TMCS_SITE_SF_CANNIBALIZED_GIDX ON TMCS_SITE_SF_CANNIBALIZED (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_SITE_SF_CANNIBALIZED_PK ON TMCS_SITE_SF_CANNIBALIZED (SF_ID, ENTITY_ID)
  ;

