CREATE TABLE TMCS_CLIENT_KEY_METRICS
   (	METRIC_ID NUMBER,
	CLIENT_ID NUMBER,
	STORE_NUMBER VARCHAR2(500),
	SITE_NUMBER VARCHAR2(500),
	METRIC_CODE VARCHAR2(500),
	METRIC_VALUE NUMBER,
	GEOMETRY_TYPE VARCHAR2(500),
	GEOM_CODE VARCHAR2(500),
	GEOM_DESC VARCHAR2(500),
	C_EXT_ATTR1 VARCHAR2(500),
	C_EXT_ATTR2 VARCHAR2(500),
	C_EXT_ATTR3 VARCHAR2(500),
	C_EXT_ATTR4 VARCHAR2(500),
	C_EXT_ATTR5 VARCHAR2(500),
	N_EXT_ATTR1 NUMBER,
	N_EXT_ATTR2 NUMBER,
	N_EXT_ATTR3 NUMBER,
	N_EXT_ATTR4 NUMBER,
	N_EXT_ATTR5 NUMBER,
	N_EXT_ATTR6 NUMBER,
	N_EXT_ATTR7 NUMBER,
	N_EXT_ATTR8 NUMBER,
	N_EXT_ATTR9 NUMBER,
	N_EXT_ATTR10 NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_CLIENT_KEY_METRICS_PK ON TMCS_CLIENT_KEY_METRICS (METRIC_ID)
  ;
ALTER TABLE TMCS_CLIENT_KEY_METRICS ADD CONSTRAINT TMCS_CLIENT_KEY_METRICS_PK PRIMARY KEY (METRIC_ID)
  USING INDEX TMCS_CLIENT_KEY_METRICS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CLIENT_KEY_METRICS_PK ON TMCS_CLIENT_KEY_METRICS (METRIC_ID)
  ;

