CREATE TABLE TMCS_CHG_ORDER_DETAIL
   (	CHG_ORDER_DETAIL_ID NUMBER,
	CHG_ORDER_ID NUMBER,
	TASK_ID NUMBER,
	CURRENCY VARCHAR2(50),
	RATE NUMBER,
	QTY NUMBER,
	UOM VARCHAR2(50),
	AMOUNT NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	PO_ID NUMBER,
	BRAND_ID NUMBER,
	ITEM_SEQ_NO NUMBER,
	AMOUNT_LOCAL NUMBER,
	AMOUNT_BU NUMBER,
	AMOUNT_USD NUMBER,
	RECEIVED_QUANTITY NUMBER,
	RETAINAGE_PCT NUMBER,
	STATUS VARCHAR2(50),
	INV_ISSUE_AMOUNT_LOCAL NUMBER,
	INV_ISSUE_AMOUNT_BU NUMBER,
	INV_ISSUE_AMOUNT_USD NUMBER,
	INV_ISSUE_AMOUNT NUMBER,
	UNAPPROVED_INV_AMT NUMBER,
	COMMENTS VARCHAR2(4000),
	TAX_GROUP VARCHAR2(100),
	TAX_RATE NUMBER,
	VENDOR_TAX_AMOUNT NUMBER,
	ACCRUED_TAX_AMOUNT NUMBER,
	SEQUENCE NUMBER,
	DELIVERY_DATE DATE,
	VENDOR_COLLECT_TAX VARCHAR2(10),
	MATERIAL_USUAGE VARCHAR2(500),
	MATERIAL_ORGIN VARCHAR2(500),
	MATERIAL_CATEGORY VARCHAR2(500),
	STAGING_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_CHG_ORDER_DETAIL_PK ON TMCS_CHG_ORDER_DETAIL (CHG_ORDER_DETAIL_ID)
  ;
ALTER TABLE TMCS_CHG_ORDER_DETAIL ADD CONSTRAINT TMCS_CHG_ORDER_DETAIL_PK PRIMARY KEY (CHG_ORDER_DETAIL_ID)
  USING INDEX TMCS_CHG_ORDER_DETAIL_PK  ENABLE;
CREATE INDEX TMCS_CHG_ORDER_DETAIL_INDX02 ON TMCS_CHG_ORDER_DETAIL (CLIENT_ID, CHG_ORDER_ID, PO_ID)
  ;
CREATE UNIQUE INDEX TMCS_CHG_ORDER_DETAIL_PK ON TMCS_CHG_ORDER_DETAIL (CHG_ORDER_DETAIL_ID)
  ;
CREATE INDEX TMCS_CHG_ORDER_DETAIL_INDX03 ON TMCS_CHG_ORDER_DETAIL (PO_ID, CLIENT_ID, UPPER(STATUS))
  ;

