CREATE TABLE TMCS_INTERFACES
   (	INTERFACE_ID NUMBER,
	CLIENT_ID NUMBER,
	INTERFACE_NAME VARCHAR2(300),
	INTERFACE_COMMENTS VARCHAR2(500),
	INTERFACE_TYPE VARCHAR2(10),
	NUMBER_OF_FIELDS NUMBER,
	INTERFACE_WHERE_CLAUSE VARCHAR2(500),
	INTERFACE_UNPROCESSED_FILE_PTH VARCHAR2(500),
	INTERFACE_PROCESSED_FILE_PTH VARCHAR2(500),
	INTERFACE_PRIMARY_FIELD_NO NUMBER,
	INTERFACE_PRIMARY_FIELD_NM VARCHAR2(50),
	INTERFACE_FILE_FOLDER VARCHAR2(500),
	INTERFACE_FILE_TYPE VARCHAR2(50),
	INTERFACE_RECORD_DELIMITER VARCHAR2(1),
	INTERFACE_PROCESS_FIRST_REC_YN VARCHAR2(1),
	INTERFACE_INSERT_RECORD_YN VARCHAR2(1),
	INTERFACE_STRING_LENGTH NUMBER,
	PRIMARY_TABLE_NAME VARCHAR2(50),
	PRE_SQL VARCHAR2(1000),
	POST_SQL VARCHAR2(1000),
	INSERT_PRIMARY_FIELD_NUMBER NUMBER,
	CLIENT_COUNTRY VARCHAR2(50),
	CLIENT_BRAND VARCHAR2(100),
	RECORD_ACTIVE_YN VARCHAR2(1),
	DATE_CREATED DATE,
	CREATED_BY VARCHAR2(100),
	PRE_SQL_LEVEL VARCHAR2(50),
	POST_SQL_LEVEL VARCHAR2(50),
	DEFAULT_CONTEXT_USER VARCHAR2(100),
	ADDITIONAL_VAL VARCHAR2(1000),
	ADDITIONAL_VAL_NO NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_INTERFACES_PK ON TMCS_INTERFACES (INTERFACE_ID)
  ;
ALTER TABLE TMCS_INTERFACES ADD CONSTRAINT TMCS_INTERFACES_PK PRIMARY KEY (INTERFACE_ID)
  USING INDEX TMCS_INTERFACES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_INTERFACES_PK ON TMCS_INTERFACES (INTERFACE_ID)
  ;

