CREATE TABLE TMCS_MSTONE_BLINE_BDGT_ALLOC
   (	ALLOCATION_ID NUMBER,
	BASELINE_VERSION_ID NUMBER,
	FISCAL_YEAR NUMBER,
	FISCAL_PERIOD NUMBER,
	PERCENTAGE NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (ALLOCATION_ID)
  USING INDEX  ENABLE
   ) ;

