CREATE TABLE TMCS_GIS_ERROR_LOG
   (	ERROR_ID NUMBER,
	ENTITY_TYPE VARCHAR2(400),
	FUNCTIONALITY VARCHAR2(4000),
	ERROR_CODE VARCHAR2(4000),
	TMC_MESSAGE VARCHAR2(4000),
	ERROR_MESSAGE VARCHAR2(4000),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	COUNTRY VARCHAR2(320)
   ) ;

