CREATE TABLE TMCS_USER_COUNTRIES
   (	USER_COUNTRY_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200),
	COUNTRY_CODE VARCHAR2(10),
	BRAND_ID NUMBER(*,0),
	CLIENT_ID NUMBER,
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	BU_ID NUMBER,
	 PRIMARY KEY (USER_COUNTRY_ID)
  USING INDEX  ENABLE
   ) ;
CREATE UNIQUE INDEX UK_TMCS_USER_COUNTRIES ON TMCS_USER_COUNTRIES (USER_NAME, CLIENT_ID, BRAND_ID, BU_ID, COUNTRY_CODE)
  ;
CREATE INDEX TMCS_USER_COUNTRIES_INDX02 ON TMCS_USER_COUNTRIES (USER_NAME, CLIENT_ID, COUNTRY_CODE)
  ;
CREATE INDEX TMCS_USER_COUNTRIES_INDX01 ON TMCS_USER_COUNTRIES (CLIENT_ID)
  ;
CREATE INDEX TMCS_USER_COUNTRIES_INDX05 ON TMCS_USER_COUNTRIES (UPPER(USER_NAME), CLIENT_ID)
  ;

