CREATE TABLE TMCS_CAN_CMA
   (	NAME VARCHAR2(64),
	KEY VARCHAR2(32),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_CAN_CMA_PK ON TMCS_CAN_CMA (KEY)
  ;
ALTER TABLE TMCS_CAN_CMA ADD CONSTRAINT TMCS_CAN_CMA_PK PRIMARY KEY (KEY)
  USING INDEX TMCS_CAN_CMA_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CAN_CMA_PK ON TMCS_CAN_CMA (KEY)
  ;
CREATE INDEX TMCS_CAN_CMA_GIDX ON TMCS_CAN_CMA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

