CREATE TABLE TMCS_SERVICE_LOG_BKP1
   (	PROGRAM_NAME VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	FILE_NAME VARCHAR2(200),
	MESSAGE_CODE NUMBER,
	MESSAGE VARCHAR2(4000),
	LOG_USER VARCHAR2(200),
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_NUMBER VARCHAR2(100),
	STATUS VARCHAR2(50),
	SERVICE_DATA CLOB,
	SERVICE_LOG_ID NUMBER NOT NULL ENABLE
   ) ;

