CREATE TABLE TMCS_MAP_TABLE_CLAUSES_JOIN
   (	ID NUMBER DEFAULT TMCS_MAP_TABLE_CLAUSES_JOIN_S.NEXTVAL,
	PRIMARY_TABLE_NAME VARCHAR2(50),
	PRIMARY_COLUMN_NAME VARCHAR2(50),
	FOREIGN_TABLE_NAME VARCHAR2(50),
	FOREIGN_COLUMN_NAME VARCHAR2(50),
	ADD_CLAUSES VARCHAR2(1000),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(50)
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_TABLE_CLAUSES_JOIN_PK ON TMCS_MAP_TABLE_CLAUSES_JOIN (PRIMARY_TABLE_NAME, PRIMARY_COLUMN_NAME, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_NAME, ENTITY_TYPE)
  ;
ALTER TABLE TMCS_MAP_TABLE_CLAUSES_JOIN ADD CONSTRAINT TMCS_MAP_TABLE_CLAUSES_JOIN_PK PRIMARY KEY (PRIMARY_TABLE_NAME, PRIMARY_COLUMN_NAME, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_NAME, ENTITY_TYPE)
  USING INDEX TMCS_MAP_TABLE_CLAUSES_JOIN_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_TABLE_CLAUSES_JOIN_PK ON TMCS_MAP_TABLE_CLAUSES_JOIN (PRIMARY_TABLE_NAME, PRIMARY_COLUMN_NAME, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_NAME, ENTITY_TYPE)
  ;

