CREATE TABLE TMCS_SITE_SF_SNR_STORES
   (	SFS_ID NUMBER,
	SF_ID NUMBER,
	STORE_ID NUMBER,
	STORE_NUMBER VARCHAR2(100),
	STORE_NAME VARCHAR2(100),
	ADDRESS VARCHAR2(500),
	CITY VARCHAR2(100),
	STATE VARCHAR2(100),
	ZIP VARCHAR2(100),
	SALES NUMBER,
	EBITA NUMBER,
	LATITUDE NUMBER,
	LONGITUDE NUMBER,
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	SELECT_FLAG VARCHAR2(1),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	DMA_ID NUMBER,
	DMA_NAME VARCHAR2(250),
	CBSA_ID NUMBER,
	CBSA_NAME VARCHAR2(250),
	STORE_TYPE VARCHAR2(200),
	SITE_TYPE VARCHAR2(200),
	CBSA_CLASS VARCHAR2(50),
	STORE_CLASS VARCHAR2(50),
	SL_DIST NUMBER,
	DR_DIST NUMBER,
	DR_TIME NUMBER,
	FACILITY_TYPE VARCHAR2(500),
	LOCATION_TYPE_CODE VARCHAR2(500),
	SEC_ATTR1 VARCHAR2(50),
	SEC_ATTR2 VARCHAR2(50)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SITE_SF_SNR_STORES_PK ON TMCS_SITE_SF_SNR_STORES (SFS_ID)
  ;
ALTER TABLE TMCS_SITE_SF_SNR_STORES ADD CONSTRAINT TMCS_SITE_SF_SNR_STORES_PK PRIMARY KEY (SFS_ID)
  USING INDEX TMCS_SITE_SF_SNR_STORES_PK  ENABLE;
CREATE INDEX TMCS_SITE_SF_SNR_STORES_GIDX ON TMCS_SITE_SF_SNR_STORES (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');
CREATE UNIQUE INDEX TMCS_SITE_SF_SNR_STORES_PK ON TMCS_SITE_SF_SNR_STORES (SFS_ID)
  ;

