CREATE TABLE TMCS_STORE_HOURS_HIST
   (	STORE_HOUR_HIST_ID NUMBER DEFAULT TMCS_STORE_HOURS_HIST_S.NEXTVAL NOT NULL ENABLE,
	STORE_ID NUMBER,
	OPNE_DAY VARCHAR2(50),
	OPEN_TIME_HH NUMBER,
	OPEN_TIME_MM NUMBER,
	CLOSE_TIME_HH NUMBER,
	CLOSE_TIME_MM NUMBER,
	OPEN_TIME_HH_LOV NUMBER,
	OPEN_TIME_MM_LOV NUMBER,
	CLOSE_TIME_HH_LOV NUMBER,
	CLOSE_TIME_MM_LOV NUMBER,
	COMMENTS VARCHAR2(500),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	EXCEPTION_DATE DATE,
	EXCEPTION_FLAG VARCHAR2(10),
	 PRIMARY KEY (STORE_HOUR_HIST_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX UK_TMCS_STORE_HOURS_HIST ON TMCS_STORE_HOURS_HIST (STORE_ID)
  ;

