CREATE TABLE TMCS_FFE_BUDGET_VERSIONS
   (	BUDGET_VERSION_ID NUMBER,
	ENTITY_TYPE VARCHAR2(100),
	ENTITY_ID NUMBER,
	VERSION_NUMBER NUMBER,
	DESCRIPTION VARCHAR2(1000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	COMMENTS VARCHAR2(4000),
	TEMPLATE_ID NUMBER,
	CURRENT_FLAG VARCHAR2(10),
	STATUS VARCHAR2(50),
	 PRIMARY KEY (BUDGET_VERSION_ID)
  USING INDEX  ENABLE
   ) ;

