CREATE TABLE TMCS_REPORTS_PARAMS
   (	REP_PARAM_ID NUMBER DEFAULT TMCS_REPORTS_PARAMS_S.NEXTVAL NOT NULL ENABLE,
	REPORT_ID NUMBER NOT NULL ENABLE,
	CLIENT_ID NUMBER,
	PARAM_NAME VARCHAR2(200) NOT NULL ENABLE,
	PARAM_TYPE VARCHAR2(50),
	PARAM_LOV_CODE VARCHAR2(50),
	PARAM_SEQ NUMBER,
	COUNTRY VARCHAR2(100) DEFAULT sysdate,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	PARAM_KEY VARCHAR2(50) NOT NULL ENABLE,
	LOV_TYPE VARCHAR2(20),
	LOV_QUERY VARCHAR2(4000),
	REQUIRED VARCHAR2(20) DEFAULT 'N',
	DEFAULT_VALUE VARCHAR2(500),
	EDITABLE VARCHAR2(20) DEFAULT 'Y',
	VALIDATE_EXPRESSION VARCHAR2(500),
	VALIDATE_MESSAGE VARCHAR2(500),
	CHILD_PARAM_ID VARCHAR2(200),
	ENABLED VARCHAR2(20) DEFAULT 'Y',
	COMPONENT_KEY VARCHAR2(500),
	SAME_LEVEL_CHILD VARCHAR2(200)
   ) ;
  CREATE UNIQUE INDEX TMCS_REPORTS_PARAMS_PK ON TMCS_REPORTS_PARAMS (REP_PARAM_ID)
  ;
ALTER TABLE TMCS_REPORTS_PARAMS ADD CONSTRAINT TMCS_REPORTS_PARAMS_PK PRIMARY KEY (REP_PARAM_ID)
  USING INDEX TMCS_REPORTS_PARAMS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_REPORTS_PARAMS_PK ON TMCS_REPORTS_PARAMS (REP_PARAM_ID)
  ;

