CREATE TABLE TMCS_PROJECT_GANTT
   (	TASK_ID NUMBER(*,0) NOT NULL ENABLE,
	SITE_ID NUMBER(*,0) NOT NULL ENABLE,
	START_TIME DATE,
	END_TIME DATE,
	ACTUAL_START DATE,
	ACTUAL_END DATE,
	COMPLETED_THROUGH DATE,
	IF_CRITICAL NUMBER(*,0),
	PERCENT_COMPLETE NUMBER(*,0),
	TASK_TYPE VARCHAR2(20),
	TASK_NAME VARCHAR2(40),
	TASK_DESC VARCHAR2(200),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROJECT_GANTT_PK ON TMCS_PROJECT_GANTT (TASK_ID)
  ;
ALTER TABLE TMCS_PROJECT_GANTT ADD CONSTRAINT TMCS_PROJECT_GANTT_PK PRIMARY KEY (TASK_ID)
  USING INDEX TMCS_PROJECT_GANTT_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROJECT_GANTT_PK ON TMCS_PROJECT_GANTT (TASK_ID)
  ;

