CREATE TABLE TMCS_MAP_FORMS_CONFIG
   (	FORM_ID NUMBER DEFAULT TMCS_MAP_FORMS_CONFIG_S.NEXTVAL,
	CLIENT_CODE VARCHAR2(50),
	BU_CODE VARCHAR2(50),
	COUNTRY_CODE VARCHAR2(50),
	FORM_NAME VARCHAR2(500),
	FORM_VALUE CLOB,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	HTML_JSON CLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_MAP_FORMS_CONFIG_PK ON TMCS_MAP_FORMS_CONFIG (FORM_ID)
  ;
ALTER TABLE TMCS_MAP_FORMS_CONFIG ADD CONSTRAINT TMCS_MAP_FORMS_CONFIG_PK PRIMARY KEY (FORM_ID)
  USING INDEX TMCS_MAP_FORMS_CONFIG_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_MAP_FORMS_CONFIG_PK ON TMCS_MAP_FORMS_CONFIG (FORM_ID)
  ;
CREATE UNIQUE INDEX TMCS_MAP_FORMS_CONFIG_UIDX ON TMCS_MAP_FORMS_CONFIG (CLIENT_CODE, BU_CODE, COUNTRY_CODE, FORM_NAME)
  ;

