CREATE TABLE TMCS_TRANS_STORE_LANDLORDS
   (	STORE_LANDLORD_ID NUMBER DEFAULT tmcs.TMCS_TRANS_STORE_LANDLORDS_S.nextval,
	TRANS_ID NUMBER,
	VICINITY VARCHAR2(500),
	STORE_ID NUMBER,
	RELATIONSHIP VARCHAR2(4000),
	ISSUES VARCHAR2(4000),
	NOTICE_DATE DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	LEASE_ID NUMBER,
	 PRIMARY KEY (STORE_LANDLORD_ID)
  USING INDEX  ENABLE
   ) ;

