CREATE TABLE TMCS_DMS_FOLDERS
   (	FOLDER_ID NUMBER NOT NULL ENABLE,
	FOLDER_NAME VARCHAR2(100) NOT NULL ENABLE,
	ENTITY_ID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(50),
	PUBLIC_FOLDER VARCHAR2(1),
	PARENT_FOLDER_ID NUMBER,
	FOLDER_TYPE VARCHAR2(50),
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	FOLDER_TEMPLATE_DTL_ID NUMBER,
	FOLDER_SEQUENCE NUMBER DEFAULT null,
	STAGING_ID NUMBER,
	DESCRIPTION VARCHAR2(250),
	FILE_COUNT NUMBER DEFAULT 0,
	 CONSTRAINT TMCS_DMS_FOLDERS_PK PRIMARY KEY (FOLDER_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_DMS_FOLDERS_INDX2 ON TMCS_DMS_FOLDERS (ENTITY_TYPE, ENTITY_ID)
  ;
CREATE INDEX TMCS_DMS_FOLDERS_INDX3 ON TMCS_DMS_FOLDERS (ENTITY_ID, UPPER(ENTITY_TYPE))
  ;

