CREATE TABLE TMCS_TEMP_DUKB_RADIUS
   (	STORE_ID NUMBER,
	STORE_NUMBER VARCHAR2(50),
	BRAND_ID NUMBER,
	RADIUS NUMBER,
	UNITS VARCHAR2(50),
	MESSAGE VARCHAR2(500),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;

