CREATE TABLE TMCS_BULK_PROJ_CREATE_INTF
   (	PROJ_CREATE_ID NUMBER DEFAULT tmcs.tmcs_bulk_proj_create_intf_s.nextval,
	BATCH_ID NUMBER,
	STORE_ID NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(50),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(50),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	STATUS VARCHAR2(100),
	 PRIMARY KEY (PROJ_CREATE_ID)
  USING INDEX  ENABLE
   ) ;

