CREATE TABLE TMCS_SITE_MODEL_TEMPLATE_DTL
   (	TEMPLATE_DTL_ID NUMBER,
	TEMPLATE_ID NUMBER,
	CLIENT_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	LANGUAGE_CODE VARCHAR2(50),
	SITE_COMPONENT_KEY VARCHAR2(500),
	STORE_COMPONENT_KEY VARCHAR2(500),
	DISPLAY_FLAG VARCHAR2(10),
	WEIGHTAGE_FLAG VARCHAR2(10),
	SITE_TABLE_NAME VARCHAR2(40),
	SITE_COLUMN_NAME VARCHAR2(40),
	DISPLAY_SEQ NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER,
	RESULT_DISP_SEQ NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_MODEL_TMPL_DTL_PK ON TMCS_SITE_MODEL_TEMPLATE_DTL (TEMPLATE_DTL_ID)
  ;
ALTER TABLE TMCS_SITE_MODEL_TEMPLATE_DTL ADD CONSTRAINT TMCS_SITE_MODEL_TMPL_DTL_PK PRIMARY KEY (TEMPLATE_DTL_ID)
  USING INDEX TMCS_SITE_MODEL_TMPL_DTL_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_MODEL_TMPL_DTL_PK ON TMCS_SITE_MODEL_TEMPLATE_DTL (TEMPLATE_DTL_ID)
  ;

