CREATE TABLE TMCS_MEETING_ATTENDEES
   (	ATTENDEE_ID NUMBER,
	MEETING_ID NUMBER,
	NAME VARCHAR2(100),
	EMAIL_ADDRESS VARCHAR2(100),
	ROLE VARCHAR2(100),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	LAST_NAME VARCHAR2(200),
	ATTENDANCE_FLAG VARCHAR2(50) DEFAULT 'TRUE',
	 PRIMARY KEY (ATTENDEE_ID)
  USING INDEX  ENABLE
   ) ;

