CREATE TABLE TMCS_USER_ADDL_SECURITY
   (	USER_ADDL_SEC_ID NUMBER DEFAULT TMCS_USER_ADDL_SECURITY_S.NEXTVAL,
	CLIENT_ID NUMBER(*,0),
	ENTITY_TYPE VARCHAR2(100),
	COLUMN_NAME VARCHAR2(100),
	COL_VALUE VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	USER_NAME VARCHAR2(200),
	CAN_EDIT VARCHAR2(50) DEFAULT 'Y',
	COUNTRY VARCHAR2(20),
	BU_ID NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_USER_ADDL_SECURITY_PK ON TMCS_USER_ADDL_SECURITY (USER_ADDL_SEC_ID)
  ;
ALTER TABLE TMCS_USER_ADDL_SECURITY ADD CONSTRAINT TMCS_USER_ADDL_SECURITY_PK PRIMARY KEY (USER_ADDL_SEC_ID)
  USING INDEX TMCS_USER_ADDL_SECURITY_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_USER_ADDL_SECURITY_PK ON TMCS_USER_ADDL_SECURITY (USER_ADDL_SEC_ID)
  ;

