CREATE TABLE TMCS_PO_SIGNATURE_CONTACTS
   (	PO_SIGNATURE_CONTACT_ID NUMBER DEFAULT TMCS_PO_SIGNATURE_CONTACTS_S.NEXTVAL,
	PROJECT_ID NUMBER,
	PO_ID NUMBER,
	CONTACT_ID NUMBER,
	CONTACT_TYPE VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(250),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_PO_SIGNATURE_CONTACTS_PK ON TMCS_PO_SIGNATURE_CONTACTS (PO_SIGNATURE_CONTACT_ID)
  ;
ALTER TABLE TMCS_PO_SIGNATURE_CONTACTS ADD CONSTRAINT TMCS_PO_SIGNATURE_CONTACTS_PK PRIMARY KEY (PO_SIGNATURE_CONTACT_ID)
  USING INDEX TMCS_PO_SIGNATURE_CONTACTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PO_SIGNATURE_CONTACTS_PK ON TMCS_PO_SIGNATURE_CONTACTS (PO_SIGNATURE_CONTACT_ID)
  ;

