CREATE TABLE TMCS_USER_BRANDS
   (	USER_BRAND_ID NUMBER(*,0),
	USER_NAME VARCHAR2(200),
	ENABLED VARCHAR2(10),
	BRAND_ID NUMBER(*,0),
	CLIENT_ID NUMBER,
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	 PRIMARY KEY (USER_BRAND_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_USER_BRANDS_INDX01 ON TMCS_USER_BRANDS (USER_NAME, CLIENT_ID)
  ;
CREATE INDEX TMCS_USER_BRANDS_INDX02 ON TMCS_USER_BRANDS (CLIENT_ID, LOWER(USER_NAME))
  ;

