CREATE TABLE TMCS_CUST_LAYER_HEADERS
   (	LAYER_ID NUMBER NOT NULL ENABLE,
	LAYER_NAME VARCHAR2(320) NOT NULL ENABLE,
	LAYER_STATUS VARCHAR2(320) NOT NULL ENABLE,
	METADATA CLOB,
	LAYER_LABEL VARCHAR2(320),
	LAYER_CLUSTER VARCHAR2(320),
	LAYER_STYLE CLOB,
	LAYER_HOVER CLOB,
	LAYER_SQL CLOB,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(320),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	BU_ID NUMBER,
	LAYER_MENU_DATA CLOB
   ) ;
  CREATE UNIQUE INDEX TMCS_CUST_LAYER_HEADERS_PK ON TMCS_CUST_LAYER_HEADERS (LAYER_ID)
  ;
ALTER TABLE TMCS_CUST_LAYER_HEADERS ADD CONSTRAINT TMCS_CUST_LAYER_HEADERS_PK PRIMARY KEY (LAYER_ID)
  USING INDEX TMCS_CUST_LAYER_HEADERS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_CUST_LAYER_HEADERS_PK ON TMCS_CUST_LAYER_HEADERS (LAYER_ID)
  ;

