CREATE TABLE TMCS_USER_STAGE_CREATE
   (	FIRST_NAME VARCHAR2(200) NOT NULL ENABLE,
	LAST_NAME VARCHAR2(200) NOT NULL ENABLE,
	EMAIL VARCHAR2(200) NOT NULL ENABLE,
	REGION VARCHAR2(200),
	CREATED VARCHAR2(1),
	STATUS_MSG VARCHAR2(500),
	CLIENT_ID NUMBER NOT NULL ENABLE,
	CREATED_DATE DATE DEFAULT sysdate,
	BATCH_ID NUMBER,
	GROUPS VARCHAR2(200) DEFAULT 'FM',
	COUNTRY VARCHAR2(200),
	DEF_LANGUAGE VARCHAR2(20) DEFAULT 'en-US',
	MOBILE_ACCESS VARCHAR2(20) DEFAULT 'N',
	DEF_BRAND_ID NUMBER,
	BRANDS VARCHAR2(200),
	DEF_COUNTRY VARCHAR2(200)
   ) ;

