CREATE TABLE TMCS_MEETING_FOLLOWUPS
   (	FOLLOWUP_ID NUMBER,
	MEETING_ID NUMBER,
	ISSUE_TYPE VARCHAR2(100),
	ITEM_ID NUMBER,
	TITLE VARCHAR2(100),
	DESCRIPTION VARCHAR2(4000),
	RISK_LEVEL VARCHAR2(100),
	FOLLOWUP_NEEDED VARCHAR2(10),
	FOLLOWUP_DATE DATE,
	RESOLVED VARCHAR2(10),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (FOLLOWUP_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_MEETING_FOLLOWUPS_INDX01 ON TMCS_MEETING_FOLLOWUPS (MEETING_ID)
  ;

