CREATE TABLE TMCS_UOM_CONVERSIONS
   (	UOM_CONVERSION_ID NUMBER DEFAULT TMCS_UOM_CONVERSIONS_S.NEXTVAL NOT NULL ENABLE,
	UOM_TYPE VARCHAR2(50),
	FROM_UOM VARCHAR2(100),
	TO_UOM VARCHAR2(100),
	CONV_FACTOR NUMBER,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	 PRIMARY KEY (UOM_CONVERSION_ID)
  USING INDEX  ENABLE
   ) ;

