CREATE TABLE TMCS_CLIENT_JOBS_DTL
   (	JOB_DTL_ID NUMBER DEFAULT TMCS_CLIENT_JOBS_DTL_S.NEXTVAL,
	JOB_ID NUMBER,
	ORACLE_LOG_ID VARCHAR2(100),
	STATUS VARCHAR2(500),
	JOB_DETAIL VARCHAR2(4000),
	START_TIME DATE,
	END_TIME DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(100),
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	 PRIMARY KEY (JOB_DTL_ID)
  USING INDEX  ENABLE
   ) ;

