CREATE TABLE TMCS_TA_P2P_DT_RULES
   (	CLIENT_ID NUMBER(19,0),
	COUNTRY VARCHAR2(64),
	CBSA_CLASS NUMBER(19,0),
	STORE_CLASS NUMBER(19,0),
	GEO_CLASS NUMBER(19,0),
	TA_TYPE VARCHAR2(10),
	MAX_DT NUMBER,
	CENSUS_DIVISION VARCHAR2(32),
	PROTECTED_RADIUS NUMBER,
	MAX_DT_PCT NUMBER
   ) ;
  CREATE UNIQUE INDEX TMCS_TA_P2P_DT_RULES_PK ON TMCS_TA_P2P_DT_RULES (CLIENT_ID, COUNTRY, CBSA_CLASS, STORE_CLASS, GEO_CLASS, TA_TYPE, CENSUS_DIVISION)
  ;
ALTER TABLE TMCS_TA_P2P_DT_RULES ADD CONSTRAINT TMCS_TA_P2P_DT_RULES_PK PRIMARY KEY (CLIENT_ID, COUNTRY, CBSA_CLASS, STORE_CLASS, GEO_CLASS, TA_TYPE, CENSUS_DIVISION)
  USING INDEX TMCS_TA_P2P_DT_RULES_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_TA_P2P_DT_RULES_PK ON TMCS_TA_P2P_DT_RULES (CLIENT_ID, COUNTRY, CBSA_CLASS, STORE_CLASS, GEO_CLASS, TA_TYPE, CENSUS_DIVISION)
  ;

