CREATE TABLE TMCS_LOOKUP_TYPES
   (	LOOKUP_ID NUMBER(*,0) DEFAULT TMCS_LOOKUP_TYPES_ID.nextval NOT NULL ENABLE,
	LOOKUP_CODE VARCHAR2(50) NOT NULL ENABLE,
	LOOKUP_NAME VARCHAR2(300) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(300) NOT NULL ENABLE,
	SECURITY_LEVEL VARCHAR2(1) NOT NULL ENABLE,
	ORG_ID NUMBER(*,0),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	COUNTRY VARCHAR2(20),
	BU_ID NUMBER,
	DEFAULT_VALUE VARCHAR2(300),
	DIVISION_ID NUMBER,
	COMMENTS VARCHAR2(4000),
	MODULE_NAME VARCHAR2(100),
	IS_SYSTEM_LOV_CODE VARCHAR2(10),
	VERSION NUMBER,
	RECORD_STATUS VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX LOOKUP_PK ON TMCS_LOOKUP_TYPES (LOOKUP_ID)
  ;
ALTER TABLE TMCS_LOOKUP_TYPES ADD CONSTRAINT LOOKUP_PK PRIMARY KEY (LOOKUP_ID)
  USING INDEX LOOKUP_PK  ENABLE;
CREATE UNIQUE INDEX LOOKUP_PK ON TMCS_LOOKUP_TYPES (LOOKUP_ID)
  ;
CREATE INDEX TMCS_LOOKUP_TYPES_INDX ON TMCS_LOOKUP_TYPES (LOOKUP_CODE, CLIENT_ID, COUNTRY)
  ;
CREATE INDEX TMCS_LOOKUP_TYPES_INDX02 ON TMCS_LOOKUP_TYPES (UPPER(LOOKUP_CODE), COUNTRY, CLIENT_ID)
  ;

