CREATE TABLE TMCS_ROLLOUT_PROJECT_LABELS
   (	ROLLOUT_PROJ_ID NUMBER DEFAULT TMCS_ROLLOUT_PROJECT_LABELS_S.NEXTVAL,
	PROJECT_ID NUMBER,
	COMPONENT_KEY VARCHAR2(100),
	COLUMN_NAME VARCHAR2(100),
	COLUMN_LABEL VARCHAR2(100),
	DISPLAY VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER,
	 PRIMARY KEY (ROLLOUT_PROJ_ID)
  USING INDEX  ENABLE
   ) ;

