CREATE TABLE TMCS_BULK_PROJ_CREATEIONS
   (	CREATION_ID NUMBER DEFAULT tmcs.TMCS_BULK_PROJ_CREATEIONS_s.nextval,
	P_QUERY CLOB,
	CLIENT_ID NUMBER(38,0),
	CREATION_DATE DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(500),
	 PRIMARY KEY (CREATION_ID)
  USING INDEX  ENABLE
   ) ;

