CREATE TABLE TMCS_ORGS
   (	ORG_ID NUMBER(*,0),
	ORG_CODE VARCHAR2(50),
	ORG_NAME VARCHAR2(100),
	ORG_TYPE VARCHAR2(50),
	CLIENT_ID NUMBER(*,0),
	BRAND_ID NUMBER(*,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_ORGS_PK ON TMCS_ORGS (ORG_ID)
  ;
ALTER TABLE TMCS_ORGS ADD CONSTRAINT TMCS_ORGS_PK PRIMARY KEY (ORG_ID)
  USING INDEX TMCS_ORGS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_ORGS_PK ON TMCS_ORGS (ORG_ID)
  ;

