CREATE TABLE TMCS_SNR_CUSTOM_POLY
   (	CUSTOM_POLY_ID NUMBER NOT NULL ENABLE,
	GEO_NAME VARCHAR2(100),
	GEO_NUMBER VARCHAR2(100),
	GEO_TYPE VARCHAR2(100),
	GEOMETRY MDSYS.SDO_GEOMETRY ,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY VARCHAR2(100)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SNR_CUSTOM_POLY_PK ON TMCS_SNR_CUSTOM_POLY (CUSTOM_POLY_ID)
  ;
ALTER TABLE TMCS_SNR_CUSTOM_POLY ADD CONSTRAINT TMCS_SNR_CUSTOM_POLY_PK PRIMARY KEY (CUSTOM_POLY_ID)
  USING INDEX TMCS_SNR_CUSTOM_POLY_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SNR_CUSTOM_POLY_PK ON TMCS_SNR_CUSTOM_POLY (CUSTOM_POLY_ID)
  ;
CREATE INDEX TMCS_SNR_CUSTOM_POLY_GIDX ON TMCS_SNR_CUSTOM_POLY (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

