CREATE TABLE TMCS_ENTITY_DYN_ATTRIBUTES
   (	FORM_TEMPLATE_ID NUMBER,
	ENTITY_TYPE VARCHAR2(100),
	FORM_NAME VARCHAR2(100),
	LABEL_VALUE VARCHAR2(320),
	COMPONENT_KEY VARCHAR2(320),
	PARENT_KEY VARCHAR2(320),
	COMPONENT_TYPE VARCHAR2(320),
	TABLE_NAME VARCHAR2(320),
	COLUMN_NAME VARCHAR2(320),
	LOOKUP_CODE VARCHAR2(320),
	COLUMN_TYPE VARCHAR2(320),
	LANGUAGE_CODE VARCHAR2(320),
	VQ_SEQUENCE NUMBER,
	SEQ_ROLES VARCHAR2(1000),
	DISPLAY_IN_VQB VARCHAR2(320),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATION_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	CREATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_DATE TIMESTAMP (6) DEFAULT SYSDATE,
	LAST_UPDATED_BY VARCHAR2(200) DEFAULT 'sysadmin',
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0) DEFAULT 1,
	DIVISION_ID NUMBER,
	TABLE_TYPE VARCHAR2(500),
	ENTITY_DYN_ATTRIBUTE_ID NUMBER DEFAULT tmcs.TMCS_ENTITY_DYN_ATTRIBUTES_S.nextval,
	 PRIMARY KEY (ENTITY_DYN_ATTRIBUTE_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_ENTITY_DYN_ATTRIBUTES_IDX ON TMCS_ENTITY_DYN_ATTRIBUTES (CLIENT_ID, ENTITY_TYPE)
  ;

