CREATE TABLE TMCS_PROJ_BASELINE_DETAIL
   (	DETAIL_ID NUMBER,
	BASELINE_ID NUMBER,
	TASK_NAME VARCHAR2(500),
	APPROVED_AMOUNT NUMBER,
	ORG_ID NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER,
	OBJECT_VERSION_NUMBER NUMBER,
	COUNTRY_CODE VARCHAR2(50),
	TASK_TYPE VARCHAR2(100),
	COMMITMENT_AMOUNT NUMBER,
	APPROVE_BUDGET NUMBER,
	CHANGE_ORDER NUMBER,
	ACTUALS NUMBER,
	TASK_NUMBER NUMBER,
	LINE_ITEM_SEQ NUMBER,
	TOTAL_APPROVED_BUDGET NUMBER,
	SUB_TASK_TYPE VARCHAR2(250),
	DESCRIPTION VARCHAR2(1000),
	DIVISION VARCHAR2(100),
	NCALC_ATTR1 NUMBER,
	NCALC_ATTR2 NUMBER,
	NCALC_ATTR3 NUMBER,
	NCALC_ATTR4 NUMBER,
	NCALC_ATTR5 NUMBER,
	BUDGET_ID NUMBER,
	INITIAL_TEMPLATE_AMOUNT NUMBER,
	 PRIMARY KEY (DETAIL_ID)
  USING INDEX  ENABLE
   ) ;
CREATE INDEX TMCS_PROJ_BASELINE_DTL_IND01 ON TMCS_PROJ_BASELINE_DETAIL (BASELINE_ID)
  ;

