CREATE TABLE TMCS_REPORTS_TEMPLATE
   (	TEMPLATE_ID NUMBER DEFAULT TMCS_REPORTS_TEMPLATE_S.NEXTVAL NOT NULL ENABLE,
	REPORT_KEY VARCHAR2(50),
	REPORT_OUTPUT_TYPE VARCHAR2(50),
	REPORT_TEMPLATE_NAME VARCHAR2(200),
	TEMPLATE_NAME VARCHAR2(200),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	COUNTRY VARCHAR2(100),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	 CONSTRAINT TMCS_REPORTS_TEMPLATE_PK PRIMARY KEY (TEMPLATE_ID)
  USING INDEX  ENABLE
   ) ;

