CREATE TABLE TMCS_SQ_QUESTION_OPTIONS_BKUP_344
   (	QID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(32),
	OBJECT_TYPE VARCHAR2(50),
	DISP_SEQ_NO NUMBER,
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	SQ_HEADER_ID NUMBER,
	SQ_VERSION NUMBER
   ) ;

