CREATE TABLE TMCS_GEOFENCE_CUSTOMER_DATA
   (	VISIT_ID VARCHAR2(500),
	DEVICE_ID VARCHAR2(500),
	GFENCE_ID NUMBER,
	VISITSDAY VARCHAR2(500),
	WEEKDAY VARCHAR2(500),
	NEAREST_PING VARCHAR2(500),
	NEAREST_DIST VARCHAR2(500),
	DAYPART VARCHAR2(500),
	GEO_ID VARCHAR2(500),
	GENERATOR_TYPE VARCHAR2(500),
	GEOMETRY SDO_GEOMETRY,
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(50),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(50),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_GEOFENCE_CUSTOMER_PK ON TMCS_GEOFENCE_CUSTOMER_DATA (VISIT_ID)
  ;
ALTER TABLE TMCS_GEOFENCE_CUSTOMER_DATA ADD CONSTRAINT TMCS_GEOFENCE_CUSTOMER_PK PRIMARY KEY (VISIT_ID)
  USING INDEX TMCS_GEOFENCE_CUSTOMER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_GEOFENCE_CUSTOMER_PK ON TMCS_GEOFENCE_CUSTOMER_DATA (VISIT_ID)
  ;
CREATE INDEX TMCS_GEOFENCE_CUSTOMER_GIDX ON TMCS_GEOFENCE_CUSTOMER_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('WORK_TABLESPACE=SPTL_TS_INDX');

