CREATE TABLE TMCS_TRF_CNT_DATA
   (	GEOID VARCHAR2(16),
	STREET VARCHAR2(65),
	TRAFFIC1 NUMBER(10,0),
	CNTTYPE1 VARCHAR2(30),
	CNT1YEAR VARCHAR2(4),
	CROSSST VARCHAR2(65),
	CROSSDIR VARCHAR2(2),
	CROSSDIST NUMBER(9,5),
	TRAFFIC2 NUMBER(10,0),
	CNTTYPE2 VARCHAR2(30),
	CNT2YEAR VARCHAR2(4),
	TRAFFIC3 NUMBER(10,0),
	CNTTYPE3 VARCHAR2(30),
	CNT3YEAR VARCHAR2(4),
	TRAFFIC4 NUMBER(10,0),
	CNTTYPE4 VARCHAR2(30),
	CNT4YEAR VARCHAR2(4),
	TRAFFIC5 NUMBER(10,0),
	CNTTYPE5 VARCHAR2(30),
	CNT5YEAR VARCHAR2(4),
	LONGITUDE NUMBER(17,6),
	LATITUDE NUMBER(17,6),
	GEOMETRY MDSYS.SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
CREATE INDEX TMCS_TRF_CNT_DATA_GIDX ON TMCS_TRF_CNT_DATA (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

