CREATE TABLE TMCS_PROJECT_SUPPLIER_CONTACTS
   (	PROJ_SUPP_CONT_ID NUMBER DEFAULT TMCS_PROJECT_SUPP_CONTACTS_S.NEXTVAL,
	PROJECT_ID NUMBER,
	SUPPLIER_ID NUMBER,
	SUPPLIER_SITE_ID NUMBER,
	CONTACT_ID NUMBER,
	ROLE VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(250),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_PROJECT_SUPP_CONTACTS_PK ON TMCS_PROJECT_SUPPLIER_CONTACTS (PROJ_SUPP_CONT_ID)
  ;
ALTER TABLE TMCS_PROJECT_SUPPLIER_CONTACTS ADD CONSTRAINT TMCS_PROJECT_SUPP_CONTACTS_PK PRIMARY KEY (PROJ_SUPP_CONT_ID)
  USING INDEX TMCS_PROJECT_SUPP_CONTACTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_PROJECT_SUPP_CONTACTS_PK ON TMCS_PROJECT_SUPPLIER_CONTACTS (PROJ_SUPP_CONT_ID)
  ;

