CREATE TABLE TMCS_SEED_TRADEAREAS
   (	SEED_ID NUMBER,
	SEED_NAME VARCHAR2(100),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	COUNTRY VARCHAR2(50),
	GEOMETRY SDO_GEOMETRY
   )
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEOMETRY.SDO_ORDINATES STORE AS SECUREFILE LOB ;
  CREATE UNIQUE INDEX TMCS_SEED_TRADEAREAS_PK ON TMCS_SEED_TRADEAREAS (SEED_ID, CLIENT_ID, BRAND_ID, COUNTRY)
  ;
ALTER TABLE TMCS_SEED_TRADEAREAS ADD CONSTRAINT TMCS_SEED_TRADEAREAS_PK PRIMARY KEY (SEED_ID, CLIENT_ID, BRAND_ID, COUNTRY)
  USING INDEX TMCS_SEED_TRADEAREAS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SEED_TRADEAREAS_PK ON TMCS_SEED_TRADEAREAS (SEED_ID, CLIENT_ID, BRAND_ID, COUNTRY)
  ;
CREATE INDEX TMCS_SEED_TRADEAREAS_GIDX ON TMCS_SEED_TRADEAREAS (GEOMETRY)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2  PARAMETERS ('SDO_RTR_PCTFREE=0 WORK_TABLESPACE=SPTL_TS_INDX');

