CREATE TABLE TMCS_DOC_SIGNATURE_CONTACTS
   (	DOC_SIGNATURE_CONTACT_ID NUMBER DEFAULT TMCS_DOC_SIGNATURE_CONTACTS_S.NEXTVAL,
	ENTITY_ID NUMBER NOT NULL ENABLE,
	ENTITY_TYPE VARCHAR2(100) NOT NULL ENABLE,
	CONTACT_ID NUMBER,
	CONTACT_TYPE VARCHAR2(50),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0) NOT NULL ENABLE,
	BRAND_ID NUMBER(38,0),
	COUNTRY VARCHAR2(250),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	IS_SIGNER VARCHAR2(50),
	IS_NOTIFIER VARCHAR2(50),
	SIGNER_SEQ NUMBER,
	IS_SAFE VARCHAR2(10),
	THRESHOLD NUMBER,
	ERROR_MESSAGE VARCHAR2(4000),
	ROLE VARCHAR2(500)
   ) ;
  CREATE UNIQUE INDEX TMCS_DOC_SIGNATURE_CONTACTS_PK ON TMCS_DOC_SIGNATURE_CONTACTS (DOC_SIGNATURE_CONTACT_ID)
  ;
ALTER TABLE TMCS_DOC_SIGNATURE_CONTACTS ADD CONSTRAINT TMCS_DOC_SIGNATURE_CONTACTS_PK PRIMARY KEY (DOC_SIGNATURE_CONTACT_ID)
  USING INDEX TMCS_DOC_SIGNATURE_CONTACTS_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_DOC_SIGNATURE_CONTACTS_PK ON TMCS_DOC_SIGNATURE_CONTACTS (DOC_SIGNATURE_CONTACT_ID)
  ;

