CREATE TABLE TMCS_SEC_CLIENT_ENT_ROLES_HIST
   (	ENT_ROLE_ID NUMBER,
	ENT_ROLE_NAME VARCHAR2(50) NOT NULL ENABLE,
	ENT_ROLE_DESC VARCHAR2(200),
	CREATION_DATE TIMESTAMP (6),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	COUNTRY_CODE VARCHAR2(10),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	BU_ID NUMBER,
	USER_TYPE VARCHAR2(20),
	EDGE_ROLE VARCHAR2(50),
	ACTION VARCHAR2(50),
	HISTORY_CREATION_DATE DATE DEFAULT sysdate,
	HISTORY_CREATED_BY VARCHAR2(100)
   ) ;

