CREATE TABLE TMCS_RESOURCE_BUNDLE_ENTRIES
   (	CLIENT_ID NUMBER,
	RESOURCE_KEY VARCHAR2(500),
	RESOURCE_VALUE VARCHAR2(500),
	OBJECT_NAME VARCHAR2(50),
	TAB VARCHAR2(50),
	SECTION VARCHAR2(50),
	RES_ID NUMBER NOT NULL ENABLE,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX TMCS_RESOURCE_BUNDLE_ENTRIESPK ON TMCS_RESOURCE_BUNDLE_ENTRIES (RES_ID)
  ;
ALTER TABLE TMCS_RESOURCE_BUNDLE_ENTRIES ADD CONSTRAINT TMCS_RESOURCE_BUNDLE_ENTRIESPK PRIMARY KEY (RES_ID)
  USING INDEX TMCS_RESOURCE_BUNDLE_ENTRIESPK  ENABLE;
CREATE UNIQUE INDEX TMCS_RES_BUNDLE_ENTRIES_UK01 ON TMCS_RESOURCE_BUNDLE_ENTRIES (CLIENT_ID, RESOURCE_KEY)
  ;
CREATE UNIQUE INDEX TMCS_RESOURCE_BUNDLE_ENTRIESPK ON TMCS_RESOURCE_BUNDLE_ENTRIES (RES_ID)
  ;

