CREATE TABLE TMCS_REPORTS_HEADER
   (	REPORT_ID NUMBER DEFAULT TMCS_REPORTS_HEADER_S.NEXTVAL NOT NULL ENABLE,
	REPORT_TYPE VARCHAR2(50),
	ENTITY_TYPE VARCHAR2(50),
	REPORT_GROUP VARCHAR2(50),
	REPORT_NAME VARCHAR2(200) NOT NULL ENABLE,
	REPORT_OUTPUT_TYPE VARCHAR2(50),
	SEQ_NUM NUMBER,
	STATUS VARCHAR2(20) DEFAULT 'A',
	IS_ASYNC VARCHAR2(10) DEFAULT 'N',
	IS_TA_ADMIN VARCHAR2(10) DEFAULT 'N',
	MAX_ALLOWED NUMBER,
	COUNTRY VARCHAR2(100),
	REPORT_KEY VARCHAR2(50),
	REPORT_LOCATION VARCHAR2(50),
	REPORT_SQL VARCHAR2(4000),
	REPORT_TEMPLATE_NAME VARCHAR2(200),
	CLIENT_ID NUMBER,
	BRAND_ID NUMBER,
	BU_ID NUMBER,
	CREATION_DATE TIMESTAMP (6) DEFAULT sysdate,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	ENT_ROLES_ALLOWED VARCHAR2(500),
	IS_GLOBAL_REPORT VARCHAR2(10) DEFAULT 'N',
	IS_STANDARD CHAR(1),
	IS_LABELIZED CHAR(1),
	IS_EMAIL_NEEDED VARCHAR2(10)
   ) ;
  CREATE UNIQUE INDEX TMCS_REPORTS_HEADER_PK ON TMCS_REPORTS_HEADER (REPORT_ID)
  ;
ALTER TABLE TMCS_REPORTS_HEADER ADD CONSTRAINT TMCS_REPORTS_HEADER_PK PRIMARY KEY (REPORT_ID)
  USING INDEX TMCS_REPORTS_HEADER_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_REPORTS_HEADER_PK ON TMCS_REPORTS_HEADER (REPORT_ID)
  ;

