CREATE TABLE TMCS_ANSWERS
   (	ANSWER_ID NUMBER,
	QUESTION_ID NUMBER,
	ANSWER VARCHAR2(500),
	ANSWER_SEQ NUMBER,
	BRAND_ID NUMBER(*,0),
	CLIENT_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(*,0),
	OBJECT_VERSION_NUMBER NUMBER(*,0),
	 PRIMARY KEY (ANSWER_ID)
  USING INDEX  ENABLE
   ) ;

