CREATE TABLE TMCS_SITE_PKG_ENTITY_NN
   (	SITE_ID NUMBER,
	STORE_ID NUMBER,
	STORE_NUMBER VARCHAR2(50),
	SL_DISTANCE NUMBER,
	DRIVETIME NUMBER,
	DRIVEDISTANCEMILES NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	STORE_NAME VARCHAR2(500)
   ) ;
  CREATE UNIQUE INDEX TMCS_SITE_PKG_ENTITY_NN_PK ON TMCS_SITE_PKG_ENTITY_NN (SITE_ID, STORE_ID, ENTITY_TYPE)
  ;
ALTER TABLE TMCS_SITE_PKG_ENTITY_NN ADD CONSTRAINT TMCS_SITE_PKG_ENTITY_NN_PK PRIMARY KEY (SITE_ID, STORE_ID, ENTITY_TYPE)
  USING INDEX TMCS_SITE_PKG_ENTITY_NN_PK  ENABLE;
CREATE UNIQUE INDEX TMCS_SITE_PKG_ENTITY_NN_PK ON TMCS_SITE_PKG_ENTITY_NN (SITE_ID, STORE_ID, ENTITY_TYPE)
  ;

