CREATE TABLE TMCS_EXCEPTION_CODES
   (	EXCEPTION_ID NUMBER,
	EXCEPTION_CODE VARCHAR2(50),
	DESCRIPTION VARCHAR2(500),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	 PRIMARY KEY (EXCEPTION_ID)
  USING INDEX  ENABLE
   ) ;

