CREATE TABLE TMCS_MILESTONE_USER_VIEW_HDR
   (	USER_VIEW_HDR_ID NUMBER,
	USER_NAME VARCHAR2(100),
	VIEW_NAME VARCHAR2(100),
	TEMPLATE_ID NUMBER,
	DESCRIPTION VARCHAR2(4000),
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	DEFAULT_FLAG VARCHAR2(10),
	ENTITY_TYPE VARCHAR2(50),
	PROJECT_TYPE VARCHAR2(100),
	 PRIMARY KEY (USER_VIEW_HDR_ID)
  USING INDEX  ENABLE
   ) ;

