CREATE TABLE TMCS_MILESTONES_BASELINES
   (	BASE_LINE_ID NUMBER,
	ENTITY_TYPE VARCHAR2(50),
	ENTITY_ID NUMBER,
	VERSION_NUMBER NUMBER,
	BASE_LINE_DATE DATE,
	PROJECTED_OPEN_DATE DATE,
	ORG_ID NUMBER(38,0),
	CLIENT_ID NUMBER(38,0),
	BRAND_ID NUMBER(38,0),
	CREATION_DATE TIMESTAMP (6),
	CREATED_BY VARCHAR2(200),
	LAST_UPDATE_DATE TIMESTAMP (6),
	LAST_UPDATED_BY VARCHAR2(200),
	LAST_UPDATE_LOGIN NUMBER(38,0),
	OBJECT_VERSION_NUMBER NUMBER(38,0),
	COMMENTS VARCHAR2(4000),
	REMAINING_BUDGET_AMOUNT NUMBER,
	PHASE VARCHAR2(50),
	DELAY_REASON VARCHAR2(50),
	 PRIMARY KEY (BASE_LINE_ID)
  USING INDEX  ENABLE
   ) ;

