CREATE TABLE TOAD_PLAN_SQL
   (	USERNAME VARCHAR2(30),
	STATEMENT_ID VARCHAR2(32),
	TIMESTAMP DATE,
	STATEMENT VARCHAR2(2000)
   ) ;
CREATE UNIQUE INDEX TPSQL_IDX ON TOAD_PLAN_SQL (STATEMENT_ID)
  ;

