CREATE TABLE TRACTS_TEMP
   (	TRACT_ID VARCHAR2(15),
	MKT_CLASS NUMBER(*,0),
	GEO_CLASS NUMBER(*,0),
	GEO_CENTROID MDSYS.SDO_GEOMETRY ,
	PW_CENTROID MDSYS.SDO_GEOMETRY ,
	PW_LATITUDE NUMBER(15,7),
	PW_LONGITUDE NUMBER(15,7)
   )
 VARRAY GEO_CENTROID.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY GEO_CENTROID.SDO_ORDINATES STORE AS SECUREFILE LOB
 VARRAY PW_CENTROID.SDO_ELEM_INFO STORE AS SECUREFILE LOB
 VARRAY PW_CENTROID.SDO_ORDINATES STORE AS SECUREFILE LOB ;

