CREATE TABLE YUM_CUSTOMER_RELATIONS
   (	CUSTOMER_ID NUMBER,
	CUSTOMER_NUMBER VARCHAR2(500),
	ENTITY_ID NUMBER,
	ENTITY_NUMBER VARCHAR2(500),
	RELATIONSHIP_NAME VARCHAR2(500),
	LEFT_ROLE VARCHAR2(500),
	RIGHT_ROLE VARCHAR2(500),
	LEFT_ENTITY VARCHAR2(500),
	RIGHT_ENTITY VARCHAR2(500)
   ) ;

