CREATE TABLE YUM_PEOPLE_RELATIONS
   (	PERSON_ID NUMBER,
	PERSON_NUMBER VARCHAR2(500),
	ENTITY_ID NUMBER,
	ENTITY_NUMBER VARCHAR2(500),
	RELATIONSHIP_NAME VARCHAR2(500),
	LEFT_ROLE VARCHAR2(500),
	RIGHT_ROLE VARCHAR2(500),
	LEFT_ENTITY VARCHAR2(500),
	RIGHT_ENTITY VARCHAR2(500)
   ) ;

