CREATE OR REPLACE EDITIONABLE PACKAGE MIGRATE_CLIENT_MAP_MENU_TEST
AS
-- multiprd.tangoanalytics.com     MULTI PROD
-- DNKNPRD.TANGOANALYTICS.COM      DUKB  PROD
-- yumprd.TANGOANALYTICS.COM       YUMB  PROD
-- CUSHPRD                         CUSH  PROD

-- General DBLINK for all TEST instances
-- PROD   ALL ENVIRONMENTS

PROCEDURE MIGRATE_MAP_CONFIG(p_CLIENT_ID NUMBER
                             ,P_FUNCTIONALITY VARCHAR2 DEFAULT 'N');

PROCEDURE MIGRATE_BU_MAP_MENU(P_BU_ID NUMBER);

PROCEDURE MIGRATE_MAP_MENU(p_CLIENT_ID NUMBER);

PROCEDURE MIGRATE_COMP_CONFIG(p_CLIENT_ID NUMBER);

PROCEDURE MIGRATE_BU_INFOWINDOW(P_BU_ID NUMBER);

PROCEDURE MIGRATE_CLIENT_INFOWINDOW(P_CLIENTID NUMBER);

END;
/

