CREATE OR REPLACE FORCE EDITIONABLE VIEW GCTR_SF_RPT_MAIN_V (SF_ID, SF_ID1, SITE_ID, SITE_NUMBER, SITE_NAME, ADDRESS, SITE_CITY_STATE, CITY, STATE, ZIP_CODE, RUN_DATE, SCENARIO_NAME, LATITUDE, LONGITUDE, DMA_NAME, CBSA_NAME, CBSA_CLASS, STORE_CLASS, SQ_FT, FORMAT, STUDIOS, GC_PRO, RENTAL, SALES_FORECAST, SNR1, SNR2, SNR3, SNR4, SNR5, SNR6, SNR7, SNR8, SNR9, SNR10, SNR11, SNR12, SNR13, SNR14, SNR15, SNR16, SNR17, SNR18, SNR19, SNR20, SNR21, SNR22, SNR23, SNR24, SNR25, SNR26, SNR27, SNR28, SNR29, SNR30, SNR31, SNR32, SNR33, SNR34, SNR35, SNR36, SNR37, SNR38, SNR39, SNR40, SNR41, SNR42, SNR43, SNR44, SNR45, SNR46, SNR47, SNR48, SNR49, SNR50, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TA9, TA10, TA11, TA12, TA13, TA14, TA15, TA16, TA17, TA18, TA19, TA20, TA21, TA22, TA23, TA24, TA25, TA26, TA27, TA28, TA29, TA30, TA31, TA32, TA33, TA34, TA35, TA36, TA37, TA38, TA39, TA40, TA_SCORE1, TA_SCORE2, OPEN_DATE, CENSUS_REGION, CENSUS_DIVISION, DMA_ID, CBSA_ID) AS
  SELECT snr.sf_id, snr.sf_id sf_id1,
          site.site_id site_id,
          site.site_number site_number,
          site.site_name site_name,
          site.address address,
          site.city || ', ' || site.state site_city_state,
          site.city city,
          site.state,
          site.zip_code,
          TO_CHAR (SYSDATE, 'MM/DD/YYYY') run_date,
          snr.snr_name scenario_name,
          site.latitude latitude,
          site.longitude longitude,
          site.dma_name,
          site.cbsa_name,
          site.cbsa_class,
          site.store_class,
          --site.sq_ft sq_ft,
          site.N_EXT_ATTR19 sq_ft,
          tmcs_adf_pkg.get_lov_value (site.site_type, 'Site Type') format,
          tmcs_adf_pkg.get_lov_value (detail.C_EXT_LOV16, 'SITELOV16')
             studios,
          tmcs_adf_pkg.get_lov_value (detail.C_EXT_LOV17, 'SITELOV17') gc_pro,
          tmcs_adf_pkg.get_lov_value (detail.C_EXT_LOV18, 'SITELOV18') rental,
          -- snr.n_ext_attr1 yr1_forecast,
          -- snr.n_ext_attr2 yr2_forecast,
          -- snr.n_ext_attr3 yr3_forecast,
          -- snr.n_ext_attr4 yr4_forecast,
          --  snr.n_ext_attr5 ta_forecast,
          -- snr.n_ext_attr6 ta_capture,
          -- snr.n_ext_attr7 tapct_per_effhh,
          -- snr.n_ext_attr8 beyond_forecast,
          --  snr.n_ext_attr9 retail_slaes,
          -- snr.n_ext_attr10 live_dj_sales,
          -- snr.n_ext_attr11 studio_sales,
          -- snr.n_ext_attr12 gc_pro_sales,
          snr.sales_forecast,
          snr.n_ext_attr1 snr1,
          snr.n_ext_attr2 snr2,
          snr.n_ext_attr3 snr3,
          snr.n_ext_attr4 snr4,
          snr.n_ext_attr5 snr5,
          snr.n_ext_attr6 snr6,
          snr.n_ext_attr7 snr7,
          snr.n_ext_attr8 snr8,
          snr.n_ext_attr9 snr9,
          snr.n_ext_attr10 snr10,
          snr.n_ext_attr11 snr11,
          snr.n_ext_attr12 snr12,
          snr.n_ext_attr13 snr13,
          snr.n_ext_attr14 snr14,
          snr.n_ext_attr15 snr15,
          snr.n_ext_attr16 snr16,
          snr.n_ext_attr17 snr17,
          snr.n_ext_attr18 snr18,
          snr.n_ext_attr19 snr19,
          snr.n_ext_attr20 snr20,
          snr.n_ext_attr21 snr21,
          snr.n_ext_attr22 snr22,
          snr.n_ext_attr23 snr23,
          snr.n_ext_attr24 snr24,
          snr.n_ext_attr25 snr25,
          snr.n_ext_attr26 snr26,
          snr.n_ext_attr27 snr27,
          snr.n_ext_attr28 snr28,
          snr.n_ext_attr29 snr29,
          snr.n_ext_attr30 snr30,
          snr.n_ext_attr31 snr31,
          snr.n_ext_attr32 snr32,
          snr.n_ext_attr33 snr33,
          snr.n_ext_attr34 snr34,
          snr.n_ext_attr35 snr35,
          snr.n_ext_attr36 snr36,
          snr.n_ext_attr37 snr37,
          snr.n_ext_attr38 snr38,
          snr.n_ext_attr39 snr39,
          snr.n_ext_attr40 snr40,
          snr.n_ext_attr40 snr41,
          snr.n_ext_attr40 snr42,
          snr.n_ext_attr40 snr43,
          snr.n_ext_attr40 snr44,
          snr.n_ext_attr40 snr45,
          snr.n_ext_attr40 snr46,
          snr.n_ext_attr40 snr47,
          snr.n_ext_attr40 snr48,
          snr.n_ext_attr40 snr49,
          snr.n_ext_attr40 snr50,
          ta.n_ext_attr1 ta1,
          ta.n_ext_attr2 ta2,
          ta.n_ext_attr3 ta3,
          ta.n_ext_attr4 ta4,
          ta.n_ext_attr5 ta5,
          ta.n_ext_attr6 ta6,
          ta.n_ext_attr7 ta7,
          ta.n_ext_attr8 ta8,
          ta.n_ext_attr9 ta9,
          ta.n_ext_attr10 ta10,
          ta.n_ext_attr11 ta11,
          ta.n_ext_attr12 ta12,
          ta.n_ext_attr13 ta13,
          ta.n_ext_attr14 ta14,
          ta.n_ext_attr15 ta15,
          ta.n_ext_attr16 ta16,
          ta.n_ext_attr17 ta17,
          ta.n_ext_attr18 ta18,
          ta.n_ext_attr19 ta19,
          ta.n_ext_attr20 ta20,
          ta.n_ext_attr21 ta21,
          ta.n_ext_attr22 ta22,
          ta.n_ext_attr23 ta23,
          ta.n_ext_attr24 ta24,
          ta.n_ext_attr25 ta25,
          ta.n_ext_attr26 ta26,
          ta.n_ext_attr27 ta27,
          ta.n_ext_attr28 ta28,
          ta.n_ext_attr29 ta29,
          ta.n_ext_attr30 ta30,
          ta.n_ext_attr31 ta31,
          ta.n_ext_attr32 ta32,
          ta.n_ext_attr33 ta33,
          ta.n_ext_attr34 ta34,
          ta.n_ext_attr35 ta35,
          ta.n_ext_attr36 ta36,
          ta.n_ext_attr37 ta37,
          ta.n_ext_attr38 ta38,
          ta.n_ext_attr39 ta39,
          ta.n_ext_attr40 ta40,
          ta.score1 ta_score1,
          ta.score2 ta_score2,
          TO_CHAR (site.PROPOSED_START_DATE, 'MM/DD/YYYY') open_date,
          site.census_region,
          site.census_division,
          site.dma_id,
          site.cbsa_id
     FROM tmcs_sites_b site,
          tmcs_site_sf_snr snr,
          tmcs_tradeareas_sites ta,
          tmcs_sites_b_detail detail
    WHERE     snr.SITE_ID = site.site_id(+)
          AND site.site_id = detail.site_id(+)
          AND snr.trade_area_id = ta.tradearea_id(+)
          AND site.site_id IS NOT NULL;

