CREATE OR REPLACE FORCE EDITIONABLE VIEW TMCS_SQ_ANSWERS_V (ENTITY_ANSWER_ID, QID, Q_SEQ_NO, ENTITY_ID, ENTITY_TYPE, SELECTED, QUESTION, ANSWER_LABEL, USER_ANSWER, ANSWER_DESC, Q_TYPE, GROUP_ID, ANSWER_ID) AS
  SELECT C.ENTITY_ANSWER_ID,
            A.QID,
            A.Q_SEQ_NO,
            C.ENTITY_ID,
            C.ENTITY_TYPE,
            C.SELECTED,
            A.QUESTION,
            C.ANSWER_LABEL,
            C.ANSWER_VALUE,
            C.ANSWER_DESC,
            A.Q_TYPE,
            A.GROUP_ID,
            C.ANSWER_ID
       FROM TMCS_SQ_ENTITY_QUESTIONS A, TMCS_SQ_ENTITY_ANSWERS C
      WHERE A.ENTITY_QID = C.ENTITY_QID AND A.Q_STATUS = 'A'
   ORDER BY A.Q_SEQ_NO;

