CREATE OR REPLACE EDITIONABLE TYPE SDO_GEOMETRY_CHAR AS OBJECT (
SDO_GTYPE_CHAR      VARCHAR2(255),
SDO_SRID          NUMBER,
--SDO_POINT       MDSYS.SDO_POINT_TYPE,
SDO_ELEM_INFO_CHAR  SDO_ELEM_INFO_ARRAY_CHAR,
SDO_ORDINATES_CHAR  SDO_ORDINATE_ARRAY_CHAR);
/

